### ISSUE TITLE
dev/staging/productionでアイコンを変えたい

### ISSUE THREAD

**Issue by wifeofvillon** [otiai10/kanColleWidget#1003]
# 問題の概要

v2、v3alpha、v3ローカルブランチのどのkcwなのかわかりやすくしたい

![2018-09-29 9 58 49](https://user-images.githubusercontent.com/24819529/46239116-e7891480-c3ce-11e8-963d-62142a2ae0d2.png)
![2018-09-29 9 59 32](https://user-images.githubusercontent.com/24819529/46239118-ee178c00-c3ce-11e8-9b61-cc25dae86cbe.png)

# ひとこと

webpack.config.jsのDefinePluginを見て表示するアイコンを切り替える

FYI: [Chrome拡張機能でアイコンを変更してみる - yk5656 diary](http://d.hatena.ne.jp/yk5656/20140917/1411735701)

**Comment by otiai10** [comment]
↑
この画像使わせてもらっていいですか

**Comment by wifeofvillon** [comment]
@otiai10 やっつけで作ったのでちょっときれいにしてPR送ります

**Comment by wifeofvillon** [comment]
アイコン切り替えの実装方針について

FYI: https://github.com/otiai10/kanColleWidget/pull/1007#issuecomment-426119921

**Comment by otiai10** [comment]
こっちにコメントするべきだった。すみません

**Comment by otiai10** [comment]
じゃあこれ僕巻き取りますね。わりとプロジェクト自体の設定タスクですし。
いつもありがとうございます。

**Comment by otiai10** [comment]
たぶんイケてると思います。ご確認お願いします
