### ISSUE TITLE
ウィジェット画面の最前面固定

### ISSUE THREAD

**Issue by naoto-seki** [otiai10/kanColleWidget#1021]
ウィジェット起動時に立ち上がるウィンドをブラウザのほかウィンドやその他アプリケーションの下に隠れないように最前面で固定したい。音声on/offやスクショボタンのように画面右上に切り替えボタンとして実装されると嬉しい。

# 解決される問題

ゲーム実況の録画時やLive配信時に関係ない画面が映り込む問題

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

バージョン

> 2.1.9

**Comment by otiai10** [comment]
→ https://github.com/otiai10/kanColleWidget/issues/118
2013年からの念願なんですけど、なかなか実現できませんね...

**「艦これウィジェット」はブラウザのランチャーであって専ブラではない**、という立場を守りたいですが、それを逸脱してデスクトップアプリかなんかにしちゃえば、実現可能かもしれないです。

**Comment by naoto-seki** [comment]
わざわざ返答ありがとうございます。
やっぱりブラウザ側だけの機能だと難しいんですね。
「最前面でポーズ」のアプリ自体は知っていたのですが、ウィジェット側だけで完結できたら嬉しいなと思い送らせていただきました。
v3の開発がんばってください！
