### ISSUE TITLE
ウィジェットアイコンの時間表示

### ISSUE THREAD

**Issue by qsx0** [otiai10/kanColleWidget#1022]
# 画面

ウィジェットアイコン

# 観測される問題

タイマーの残り時間が一番少ないものが、ウィジェットアイコンに表示されない

# 期待される挙動

タイマーの残り時間が一番少ないものが、ウィジェットアイコンに表示される

# 再現方法

クロックモードへ手動入力した場合、タイマーを自動取得した場合のどちらでも発生。例えばクロックモードの手動入力で遠征時間を、第二：3h、第三：2h、第四：1hと入力すると、アイコンには3hが表示される。

-------

環境

> Chrome/70.0.3538.67

バージョン

> 2.1.9

**Comment by otiai10** [comment]
@qsx0 これいつまで動いてましたか？

**Comment by qsx0** [comment]
1week前までは、期待される挙動でした。

**Comment by otiai10** [comment]
v2は更新していないはずなので、あんまり艦これウィジェット起因とは考えにくいです...

v3を頑張っているので、v3で頑張りたいです（語彙）

**Comment by otiai10** [comment]
v3でやります
