### ISSUE TITLE
スクショのリサイズを1200x720にして欲しい

### ISSUE THREAD

**Issue by hisamek** [otiai10/kanColleWidget#1030]
# 画面

スクショ

# 観測される問題

旧仕様の800x480へのリサイズになっている？

# 期待される挙動

プレイ中のウィンドウの縦横比に関わらず、ゲームの画面だけを切り抜いて1200x720ドットの画像にして保存する

# 再現方法

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36

バージョン

> 2.1.9

**Comment by otiai10** [comment]
v3で改めてやります
