### ISSUE TITLE
ミュート機能の不具合

### ISSUE THREAD

**Issue by sasasa147852369** [otiai10/kanColleWidget#1035]
# 画面

最初のロード画面

# 観測される問題

右上にあるミュートボタンをONにした状態でゲームを閉じて再度起動するとボタンの表示はONなのに音が出ています

# 期待される挙動

ミュート状態をちゃんとゲームを閉じても引き継ぐように欲しいです

# 再現方法

ゲーム画面設定のゲーム画面右上にミュートなどのボタンを表示するをONにしてゲームをミュート状態にした状態でゲームを閉じて再度起動してください(通知からの起動だとちゃんとミュート機能は反映されますのでそれ以外の方法で起動してください)

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

バージョン

> 2.1.9

**Comment by otiai10** [comment]
v2はメンテしていないのでv3にご期待ください

**Comment by sasasa147852369** [comment]
返信ありがとうございます。
V3楽しみに待ってます
