### ISSUE TITLE
連合艦隊編成時の大破進軍防止窓（別窓表示）に艦隊状況が表示されない。

### ISSUE THREAD

**Issue by strisk** [otiai10/kanColleWidget#1037]
# 画面

戦闘終了後表示される大破進軍防止窓（別窓表示）。

# 観測される問題

ｖ１では戦闘終了後自動で第一艦隊のスクショをとり、画面をクリックしたら第二艦隊のスクショをとって別窓に表示されていたのですが、ｖ２になってから青い背景のまま何も表示されません。
今更ではありますが、報告されていないのかと思い投稿しました。

# 期待される挙動

戦闘終了後自動で第一艦隊のスクショをとり、画面クリック後第二艦隊のスクショをとって別窓に並べて表示する。

# 再現方法

大破進軍防止窓（別窓表示）をオンにして連合艦隊編成で戦闘を終了する。

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

バージョン

> 2.1.9

**Comment by otiai10** [comment]
v2なのでいったんcloseします
