### ISSUE TITLE
タイマーについて

### ISSUE THREAD

**Issue by kurokuro0316** [otiai10/kanColleWidget#1039]
# 画面

windowsの更新のためpcを再起動してから遠征や入渠等のタイマーの登録ボタンが消えて時間の設定ができなくなってしまいました

# 観測される問題

タイマーの登録ボタンの消失

# 期待される挙動

登録ボタンはどうしたら使えるようになりますか？

# 再現方法

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36

バージョン

> 2.1.9

**Comment by kurokuro0316** [comment]
再度インストールしようとしたのですがchromeストアから消えてしまっていて困ってしました
どうしたらよいのでしょうか？

**Comment by otiai10** [comment]
ちょっと時間がなくて何もできてないですが、まずはストアを復活させたいです。すみません

**Comment by otiai10** [comment]
@kurokuro0316 もしよかったらv3テスターグループに参加しませんか？

**Comment by otiai10** [comment]
ここで返信無いのでここはcloseします
