### ISSUE TITLE
ダッシュボードのコンパクト表示

### ISSUE THREAD

**Issue by otiai10** [otiai10/kanColleWidget#1050]

**Comment by xia-sava** [comment]
![SS_20200613_180655](https://user-images.githubusercontent.com/679532/84566137-d736ea00-ada9-11ea-82c9-56da8a1bb096.jpg)

現状の v3 表示だと同じくらいの情報量でも専有面積が広くてなんならゲーム本体よりも高さ使う勢いなので，v2 のような最小面積で全情報を俯瞰できる表示形態もあったらいいなって思います！
