### ISSUE TITLE
スクショダウンロードフォルダ指定（というかスクショ画面のいろいろ）

### ISSUE THREAD

**Issue by otiai10** [otiai10/kanColleWidget#1052]

**Comment by otiai10** [comment]
@xia-sava これって、スクショ直ダウンロードとかも含まれてますか？

**Comment by xia-sava** [comment]
自分の利用形態では直ダウンロードは使っておらず，いったん編集画面？（文字を書き込んだりできるやつ）に行ってから保存ボタンでフォルダに保存してますね．
装備やメモ代わりにスクショだけ撮っといて保存はせず，用が済んだら編集画面のタブを閉じる……みたいな使い方もしています．

**Comment by otiai10** [comment]
@xia-sava フォルダ名だけじゃなくて、ファイル名ってどうなってましたっけ？設定で変更可能なんでしたっけ？

**Comment by xia-sava** [comment]
v2 では，フォルダは Chrome のダウンロードフォルダからの相対指定，ファイル名をテンプレート文字列で任意指定＆ファイル形式を選択式で jpeg or png 指定ですね．

![SS_20200707_164929](https://user-images.githubusercontent.com/679532/86741935-b98c3600-c072-11ea-803d-e6af8da49c8b.jpg)

v2 有能すぎてヤバいですね……ｗ

**Comment by xia-sava** [comment]
せっかくなので v2 設定画面の全体キャプチャも（妙に横長になってしまったけど）撮っときました．

![chrome-extension___iachoklpnnjfgmldgelflgifhdaebnol_dest_html_options html](https://user-images.githubusercontent.com/679532/86742373-096afd00-c073-11ea-8116-4016c90e3f59.png)
