### ISSUE TITLE
任務着手忘れアラート機能がほしい

### ISSUE THREAD

**Issue by xia-sava** [otiai10/kanColleWidget#1057]
地味～に便利なんですよねー

**Comment by otiai10** [comment]
これ、デイリー任務の進捗を管理するモデルが必要になってきますね

**Comment by wifeofvillon** [comment]
v2ってOCRでやってたんでしたっけ？
自分で使いたくてこういうリストを作ってるんですが流用できますかね？
→[【艦これ】定期任務 - Google スプレッドシート](https://docs.google.com/spreadsheets/d/1F6gDmwzrKU6-QGqvA3Le1Jes7al7TtO8BR5RSrharvY/edit#gid=0) (※[艦これウィジェットグループメンバー](https://groups.google.com/g/kcwidget/)はコメント可能)

**Comment by otiai10** [comment]
任務の管理は、OCR使ってないはずです（HTTPリクエストのなかに任務IDがあるので）。
スプレッドシート、超有用っす！！！！！！！！！
