### ISSUE TITLE
疲労タイマーの登録単位について出撃艦隊/時刻を選択可能にする

### ISSUE THREAD

**Issue by wifeofvillon** [otiai10/kanColleWidget#1074]
# 問題の概要

v2にあった、疲労タイマーの登録単位を出撃艦隊/出撃時刻で選択できるオプションがあると嬉しい

v2のスクリーンショット↓

![v2  スクリーンショット 2020-06-30 21 16 20](https://user-images.githubusercontent.com/24819529/86126147-c8299900-bb18-11ea-8c13-cd1df0d763d1.png)

# 提案の基準となったバージョン

- v3-alpha.66

# ひとこと

疲労タイマーめちゃくちゃ助かります。イベント後半になると1-1で1隻ずつキラ付けしたりするので時刻単位を選べると嬉しいです

**Comment by wifeofvillon** [comment]
すいません、現状は出撃時刻単位になってますね……！
![スクリーンショット 2020-07-01 0 19 06](https://user-images.githubusercontent.com/24819529/86144341-81479d80-bb30-11ea-9d76-24a2aaf5524a.png)

**Comment by otiai10** [comment]
これ必ず出撃艦隊単位ってことにしたらよさそう
