### ISSUE TITLE
デイリー任務で日付が出現条件になるものを考慮する

### ISSUE THREAD

**Issue by wifeofvillon** [otiai10/kanColleWidget#1080]
# 問題の概要

一部のデイリー任務には日付が出現条件になっているものがあり、現在それが考慮されていない

- 敵空母を3隻撃沈せよ！: 日付の一の位が0,3,7の日のみ出現
- 敵輸送船団を叩け！: 日付の一の位が2,8の日のみ出現

[【艦これ】定期任務 - Google スプレッドシート](https://docs.google.com/spreadsheets/d/1F6gDmwzrKU6-QGqvA3Le1Jes7al7TtO8BR5RSrharvY/edit#gid=0)

# 問題の再現方法

1. 7/3に出撃デイリー任務を全て受けた状態で"出撃" > "出撃"を開く
2. 「未着手任務があります: 敵輸送船団を叩け」の通知が上がる
3. (3日に当該任務は出現しない)

<img width="382" alt="スクリーンショット 2020-07-03 7 24 44" src="https://user-images.githubusercontent.com/24819529/86414431-db965900-bcfe-11ea-9be8-36feba9133eb.png">

上記の方法により、100％の確率で、再現する。

# 問題が起きているバージョン

- 問題が観測されるバージョン: 3.0.0-alpha.68(local)
- 問題が観測されなかったバージョン: 

# 環境

- OS: Mac
- Chrome: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36

**Comment by otiai10** [comment]
@wifeofvillon さん、Assigneeって変えれますか？
重複作業防止のために、Contributorになってもらって、すくなくともassign myselfできるようになってもらおうかなという気持ちもじゃっかんありつつ

**Comment by wifeofvillon** [comment]
@otiai10 遠征追加の方 #1067 に自分をassignしようと思ったんですがassigneesのところに歯車が表示されなくてできてません。個人リポジトリの場合はcollaboratorにならないとできないんですかね

このissueに関しては何もやってないです

**Comment by otiai10** [comment]
あ、そうです。collaborator。ハイ。

**Comment by otiai10** [comment]
orgつくったほうがいいかな...
