### ISSUE TITLE
疲労回復タイマーの残時間表示

### ISSUE THREAD

**Issue by xia-sava** [otiai10/kanColleWidget#1089]
# 問題の概要

疲労回復タイマーに「残○○分」の表示がほしい

![SS_20200709_194003](https://user-images.githubusercontent.com/679532/87030451-94d3c200-c21c-11ea-8391-ed763fa101a2.jpg)

なくてもいいような内容なんですが実際使ってるとあった方がびみょーーに便利で……ｗ

# 問題が起きているバージョン

- 3.0.0-alpha.70

# 環境

- OS: Windows 10
- Chrome: 83

**Comment by otiai10** [comment]
一応hoverすると見えますけど、まあ一覧性ほしいっすよね
