### ISSUE TITLE
常に最前面に表示するオプションが欲しい（clockmodeだけでも）

### ISSUE THREAD

**Issue by pchw** [otiai10/kanColleWidget#118]
http://developer.chrome.com/extensions/windows.html
の`always on top`らへん？

**Comment by otiai10** [comment]
chrome://flags/#enable-panels

**Comment by otiai10** [comment]
https://github.com/otiai10/kanColleWidget/commit/1ef74a0e5865dabb05f8feb7d58e728a1a9dbf36

chrome.windows.createのtype:'panel'でどうにか対応したが、以下の問題を<s>サボって</s>調査中

- Windows様のAero領域を考慮してないっす  └(՞ةڼ◔)」
- なんかpanelだとスクショ撮れねえな

**Comment by otiai10** [comment]
# 2018年01月24日 追記

以前までは `panel` で対応していたが、ChromeExtension的にdeprecatedになった。

https://developer.chrome.com/extensions/windows#type-CreateType

**Comment by otiai10** [comment]
<blockquote class="twitter-tweet" data-conversation="none" data-lang="en"><p lang="ja" dir="ltr">補助ツールとして「最前面でポーズ」もご紹介。<br><br>機能は……名前通りです。demadoのウィンドウを常に最前面表示するように設定できます。最大化した背後のウィンドウに触れても隠れる事がないので、気になる動画をチェックしながら周回なんてこともできますよ～<br><br>Vector(<a href="https://t.co/jQNyZGrSMF">https://t.co/jQNyZGrSMF</a> …) <a href="https://t.co/CCVRKe5itV">pic.twitter.com/CCVRKe5itV</a></p>&mdash; 八葉 りん (@yatsuba_rinn) <a href="https://twitter.com/yatsuba_rinn/status/989145502775033856?ref_src=twsrc%5Etfw">April 25, 2018</a></blockquote>
