### ISSUE TITLE
大破進撃防止窓が小っさくなってしまう

### ISSUE THREAD

**Issue by otiai10** [otiai10/kanColleWidget#426]
> 最近艦これウィジットを使用させていただいているのですがサイズが小さくなっており非常に見にくくなっています
> コレの対処法などがあれば教えていただきたいのですが・・・
> よろしくお願いします

<span></span>

> Chromeの最新版への更新(3日前くらいにあったらしい)をしてから状態表示の大きさがかなり小さくなってしまったようです
> バージョンの更新が原因なのか自分で無意識に何かやらかしてるのか…
> 都度サイズ変更しても次の出撃でまた戻ってしまいます。
> 何か対処方法はないでしょうか…？
> 
> かなり小さく表示されるバージョン 38.0.2096.0 dev-m (64-bit)
> 
> 今までの大きさのバージョン 35.0.1916.153 m(ChromePortable)
> 
> いずれもwin7ですﾊｲ

<blockquote class="twitter-tweet" lang="ja"><p>艦これウィジェットで大破進軍防止のスクショ撮影でこれまでの半分くらいのサイズしか撮影されなくなったのは運営側で何かしら表示処理とかの変更が入った感じだろうか・・・？ウインドウ起動時も左側に白い空白部分が出てずれてるしChrome本隊もFlash周りが怪しいし・・・うーむ</p>&mdash; ちゃそ＠佐世保提督 (@shinchaso) <a href="https://twitter.com/shinchaso/statuses/490516735422779393">2014, 7月 19</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" lang="ja"><p>艦これウィジェットの大破進撃防止窓がかなり小さいサイズで出現してしまう。手動で見やすいサイズに直してもも、次には再び小さいサイズで出てしまう。Chrome再起動、OS再起動でも改善ならず。Chromeを最新版にしたらなったっぽい？</p>&mdash; 東雲P (@shinonome_25) <a href="https://twitter.com/shinonome_25/statuses/489725187571474432">2014, 7月 17</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

えー記憶もしないの？

**Comment by 0x0003** [comment]
古いところにスミマセン。
ひと月ほど前からか当方の環境でも「開くたびにだんだん高さが小さくなる」現象が生じています。
Mac OS X 10.11.4　これのバージョンv1.7.6
Chromeバージョン 50.0.2661.94　ズーム100%
