### ISSUE TITLE
クロックモードのクエストタブにおけるデイリー任務総数が日によって正しくない問題

### ISSUE THREAD

**Issue by Acrylban** [otiai10/kanColleWidget#489]
src/js/definitions/models/quests/Quests.jsを拝見して、2015/01/11のデイリー総数が19になってしまうのが不思議でなりません。12日、完遂していない状態ですが、総数18となっています（19であるべき）。さらに追って確認する予定です。

個人的要望としましては、追加された装備改修強化任務も実装して頂けるとありがたいと存じます。

**Comment by fanatics** [comment]
……もしかして、前日の総数をそのまま引っ張ってきている？

**Comment by fanatics** [comment]
おはようございます。不具合報告と要望の切り分けありがとうございます。毎度お手数かけているようで恐縮の限りです……。

現状：
1/11　18/19　限定任務が出ない日なのに+1されている
1/12　19/18　輸送艦5任務が出る日なのに+1されていない
1/13　??/18　空母3任務が出る日なのに+1されていない

今後はここに追記していきます。

**Comment by otiai10** [comment]
助かります

**Comment by fanatics** [comment]
お疲れ様です。日限任務は両方ともリストに出現、遂行、完了可能です。

・輸送5任務については母数に反映されず
・空母3任務については0の日は問題なし（？）、3・7の日は（私の記録・記憶も）怪しい
・日限任務なしで母数が19になる日は、前日に日限任務が出ている

今のところこんな感じでしょうか。

**Comment by otiai10** [comment]
ありがとうございます！今作ってるものひと段落したらタックルしようと思っております

**Comment by otiai10** [comment]
このへん怪しいな
https://github.com/otiai10/kanColleWidget/blob/develop/src/js/definitions/models/quests/Quests.js#L27-L55

**Comment by fanatics** [comment]
こんばんは。前※にて「0の日は問題なし（？）」と書きましたが、本日（20日）、空母3任務出現前、遂行後（早朝5-6時台）ともに母数が18であることを確認、しかし現在（19時）では母数が19になっています。色々デイリーを進めてしまっている（残り南西→1-5）ので何とも言えませんが、必ず18→19になると仮定すると、羅列したメモを見返す限り、16/18（残り南西→1-5）になる前後で表示が改まっているような気がします。

**Comment by yajamon** [comment]
時間によって表示が変わるのって、以下が関係していそうですね
https://github.com/otiai10/kanColleWidget/blob/develop/src/js/Util.js#L543-L550

**Comment by fanatics** [comment]
xia-savaさんのPR#505に気になる文言
「工廠系任務ふたつ（改修工廠と2隻解体）がひとつの任務（建造3回）に依存しているため，素直に作ると改修工廠に入る時に解体任務が未受諾というメッセージになってしまうので，ちょっときったないコードになっちゃってます」
があったんですが、これって補給5任務（2任務が1任務に依存）が出現しても母数に反映されないこととなんか関係ありませんか？

**Comment by fanatics** [comment]
・母数が当日中に修正される（空母）
・母数が反映されない（輸送）
・何もない日なのに母数が+1される
これらが全部違うところに原因があったりして……？　(T_T)

**Comment by otiai10** [comment]
（僕あんまりこの機能使ってないんですよねw だから再現してないw）

**Comment by fanatics** [comment]
ｗ　ところで、今気づいた（また19時台ですよ＾＾；）んですけど、今日（22日）の輸送5、母数に反映されてます。で、デイリーの進行状況は……17/19（南西→潜水）……です。1/12にデイリー完遂しても19/18だったのと、状況が変わっていますね。もう何が何やら。

**Comment by fanatics** [comment]
うー、初期確認してませんが、空母任務出たときには母数が19になってました（23日）。うー。

**Comment by RarXmaEta** [comment]
どうもお久しぶりです。ついでに名前まで変わっていたりして誰だか判らないかも知れませんが。本日も分母が20（本来なら19）になっていましたので、試しに「clock mode」ウィンドウを開き直したところ、分母が正常に表示されました。もしかしたらずっと出しっ放しにしている（更新を跨ぐ）ことが原因なのかも知れません。

**Comment by otiai10** [comment]
v2で作り直します

**Comment by Acrylban** [comment]
<(_ _)>
