### ISSUE TITLE
デイリー任務いろいろ追加されたんで追加して

### ISSUE THREAD

**Issue by otiai10** [otiai10/kanColleWidget#490]
> 個人的要望としましては、追加された装備改修強化任務も実装して頂けるとありがたいと存じます。

#489 のあとかなー

**Comment by otiai10** [comment]
@fanatics 現状（ゲーム内最新）の一覧ってここに貼れますか？

**Comment by fanatics** [comment]
おはようございます。
http://wikiwiki.jp/kancolle/?%C7%A4%CC%B3#Routine-D
これが最新の一覧で、追加された任務は「工廠」の「装備の改修強化」です。
よろしくお願い致します<(_ _)>
