### ISSUE TITLE
2015年2月6日のアップデートにて追加された遠征について

### ISSUE THREAD

**Issue by mizunashi** [otiai10/kanColleWidget#496]
2015年2月6日のアップデートにて次の遠征が追加された様です。
西方海域の遠征32番：「遠洋練習航海」（24時間）
こちらの演習に出したところ表示されませんでしたのでご報告致します。

よろしくお願いいたします。
![2015-02-10 0 38 12](https://cloud.githubusercontent.com/assets/1645189/6109401/ed5e4538-b0bd-11e4-8081-e337bb19a709.png)

**Comment by otiai10** [comment]
ありがとうございます。助かります
