### ISSUE TITLE
Save dataが機能しない

### ISSUE THREAD

**Issue by eru01** [otiai10/kanColleWidget#502]
昨夜のアップデート以降、「タイマー、任務実績、メモを同期」の設定で、save dataボタンを押しても反応しなくなりました。
全て同期にすれば動作するので、サウンド以外同期の項目を増やした際にエンバグしたものと思います。
よろしくお願いします。

Widget 1.5.6.4
Chrome 40.0.2214.111

**Comment by otiai10** [comment]
ありがとうございます！

**Comment by otiai10** [comment]
> 初めまして。いつもウィジェットを便利に使わせていただいております。
今回のv1.5.6.4にアップデートしてから
「リッチな設定」ページでの「save now」によるデータの記録ができなくなってしまいました（今まではセーブのたび設定ページが閉じられていたのに閉じなくなりました）。clockmodeで時間を記録してセーブボタンを押し、少し後にロードボタンを押しても記録がされていません。ウィジェット窓を閉じることによる記録はどうやら可能なようです。
今のところ再現率は100%です。当方こういったプログラム関係ではずぶの素人なのでなにか根本的な誤解があるのかもしれませんが、よろしくお願いします。

**Comment by otiai10** [comment]
@eru01 v1.5.6.5をリリースしました。治ってるかと思います。ご確認いただければ幸いです

**Comment by eru01** [comment]
@otiai10 対応ありがとうございます。ボタン動作までしかみれていませんが、直ってるっぽいのを確認できました。
