### ISSUE TITLE
第二艦隊のスクリーンショット位置について

### ISSUE THREAD

**Issue by ni3shi9p** [otiai10/kanColleWidget#534]
はじめまして。

先日アプデされた第二艦隊のSSですが、当方環境でやや左にズレているようです。

![2015-05-08 12 29 53](https://cloud.githubusercontent.com/assets/12195515/7530135/2edd0224-f57e-11e4-92a1-944268643c57.png)

OS
Mac OS X 10.10.3
Chrome
42.0.2311.135 (64-bit)

取り急ぎご報告まで

**Comment by otiai10** [comment]
ありがとうございます。

#532 

https://github.com/otiai10/kanColleWidget/blob/develop/typescript/src/application/pages/exposed.ts#L13-L14

実は僕が雑に作ってたところっす...すみません
