### ISSUE TITLE
「戦績表示」画面に移動する場合「装備の改修強化任務が未着手」の通知が出してくれます

### ISSUE THREAD

**Issue by ReimuYome** [otiai10/kanColleWidget#537]
これは変と思いますが・・・「工場」画面に移動する場合通知を出してくるものではないでしょうか？

そういう問題が起こす時点は、「軍需条約対応」任務が完成した後、「装備の改修強化」任務が未完成・未受領の時です。

でも、「軍需条約対応」と「装備の改修強化」両方も未完成・未受領の時は「戦績表示」画面に移動してもこういう通知が出してくれません。

私は普通に「軍需条約対応」も、「装備の改修強化」もしませんので、こういう問題を発見することも偶然ですが・・・

**Comment by otiai10** [comment]
related #600
