### ISSUE TITLE
Injustice user

### ISSUE THREAD

**Issue by houzyou090** [otiai10/kanColleWidget#546]
I misuse octocat and remodel it
URL http://live.fc2.com/89731106

**Comment by otiai10** [comment]
test @houzyou090

**Comment by otiai10** [comment]
@houzyou090 
I can't watch this video 'cause this is fc2 chat.
Is there any other way to check the problem? and
Please give me more description of the problem you want to point out.

**Comment by otiai10** [comment]
I will close this issue if no more comment here.
@houzyou090
