### ISSUE TITLE
時間取得窓をどうにかしていただきたい

### ISSUE THREAD

**Issue by ke9000** [otiai10/kanColleWidget#549]
かなりわがままです。わかっています。
先に申し上げておきます。こんなわがまま言って申し訳ございません。

えっとできたら実装してほしいのが
時間取得窓の表示場所を

ウィジットの下or右等にずらす
or
ユーザーで表示場所の指定をできるようにしてほしい

というものです
現在の左上だと少々邪魔くさくて・・・
無理でしたら聞かなかったことにしていただいて構いません
ご検討のほどよろしくお願いします

**Comment by otiai10** [comment]
@ke9000 
issueありがとうございます。ちなみになぜですか？

**Comment by ke9000** [comment]
@otiai10 
（本当にわがままな内容ですが・・・）
（ニコニコさん等の）生放送で放送画面に突如窓が出てくるのがうっとうしいということがありました。
こちらで指定できる感じでもないので、できたらいいなと思った次第であります。

最悪取得をなしor公式を使うことにしてしまえばいいのですが...
こんな理由で申し訳ないです。

**Comment by otiai10** [comment]
まあ、取得中窓を表示しないくらいなら（ユーザによる指定よりは）楽なので、非表示を選択可能にする方向でやりますね。

ちなみに、ニコニコの実況って、画面中の座標の指定じゃなくて、特定URLのウィンドウそのものを指定できないんですか？僕くわしくないんでわからないんですけど

**Comment by ke9000** [comment]
@otiai10 それが・・・画像を見ていただくとわかると思いますがNiconico Live Encoderでやると、
窓まるごととってしまい窓の枠の部分（タイトルバーの含む部分）まで入ってしまうのです。
これはおそらく公式を使っている生主もおそらくは座標指定で取得しているものを思われます。
※画像:赤枠が窓指定での取得時の挙動
![2](https://cloud.githubusercontent.com/assets/12986282/9299850/08e448da-44fb-11e5-8972-5a95587e79b4.png)

**Comment by otiai10** [comment]
![なるほど](http://img.tiqav.com/38n.jpg)

**Comment by ke9000** [comment]
@otiai10 とてつもなく早い対応ありがとうございました！今後も楽しく使わせていただきます！
