### ISSUE TITLE
キャプチャ機能セズ

### ISSUE THREAD

**Issue by katsusand** [otiai10/kanColleWidget#556]
環境
Win7 HP
Chrome V44(stable) x64
ウィジェットの機能は使用せず通常のウインドウを使用(+右サイドにデベロッパーツール表示)
stylishで余計なものを排除

症状
通常スクショの座標が下方向にズレてかつ、枠のサイズが本来のウインドウよりもでかい
![kancolle_20150824_083958](https://cloud.githubusercontent.com/assets/6007916/9430778/cf289146-4a3b-11e5-98a6-e6e8ad01ce12.jpg)

編成スクショでは「この装備画面をキャプる」を押しても何も起こらない

**Comment by otiai10** [comment]
> ウィジェットの機能は使用せず通常のウインドウを使用

これのせいですね。ウィジェットの窓使えば機能すると思います（v1.6.2）。
窓使わないなら『艦これウィジェット』使わなくていいんじゃないでしょうか？

**Comment by katsusand** [comment]
ちょっと試してみます。
今まで遠征自動タイマー用途で使っていたもんで…

**Comment by otiai10** [comment]
普通の窓でやる+遠征自動タイマーが欲しい場合は、たぶんChrome鎮守府とか航海日誌とかのほうが機能が充実していると思うので、オススメです。（僕は使ったことないですが）

**Comment by katsusand** [comment]
whiteモードで動作確認しました。ご迷惑をおかけいたしました。
不具合かどうかは不明ですが、同一ウインドウで編成スクショコンソールを別タブに置いている状態で編成スクショを撮るとコンソールのウインドウをスクショしてしまいました。
whiteモードでしか発生しないとは思いますがとりあえず報告いたします。

**Comment by otiai10** [comment]
ありがとうございます！よかったっす！
![img](http://img.tiqav.com/3yl.jpg)
