### ISSUE TITLE
謎の2ドットの四角が出る

### ISSUE THREAD

**Issue by katsusand** [otiai10/kanColleWidget#561]
![0_bg_holo](https://cloud.githubusercontent.com/assets/6007916/9754687/b56a9c68-5706-11e5-899e-33a7cea4e81f.png)
ボーキサイトの横あたり。
F12で調べると要素はdiv#ntg-recommend.area-pickupgame.show
です。
自分はadblock系で
dmm.com##DIV[class="area-pickupgame show"]
を入れることで対処しました。

**Comment by otiai10** [comment]
艦これウィジェット以外で、dmm.com にて有効なChrome拡張やソフトはインストールされてますか？

**Comment by katsusand** [comment]
ublock(easylistとABP-Japanese filter)とstylish(MSゴシックをメイリオに置き換える自作スクリプトのみ)です。
ublockのフィルタは通常開いた際の右側に出る宣伝の除去に使っていました。

**Comment by otiai10** [comment]
お使いのモードは、Whiteですか？APPですか？

**Comment by katsusand** [comment]
whiteです！

**Comment by otiai10** [comment]
<img width="977" alt="2015-09-09 16 56 43" src="https://cloud.githubusercontent.com/assets/931554/9756303/180ea438-5714-11e5-84f3-4b90e2e0b6fb.png">

領域としてはここっぽいです。

「これ」のボタン押したら閉じてくれるんじゃないですかね？

**Comment by katsusand** [comment]
ｱｱｱｯそれブロックしてた
adblockでのブロック漏れのようでした。
closeとします。
