### ISSUE TITLE
ＦＣ２ライブ配信者（かえで）

### ISSUE THREAD

**Issue by houzyou090** [otiai10/kanColleWidget#563]
https://www.youtube.com/watch?v=oub2nSvezHM
KAEDE（かえで）ＦＣ２で使用した無許可の上
規約無視の改造

**Comment by otiai10** [comment]
Thanks for comment. But I cannot understand your pointing.
Please use English to make issue, please.

And YOU once made issue https://github.com/otiai10/kanColleWidget/issues/546 but YOU didn't answer my reply.

Along this, I will close this issue if you don't reply this message by 3 days.

Thank you

**Comment by otiai10** [comment]
YOU didn't reply to my response.
close this issue, thank you.
