### ISSUE TITLE
Google Chrome 46.0.2490.71にアップデート後画面キャプチャ関連の動作がおかしい

### ISSUE THREAD

**Issue by abyssluke** [otiai10/kanColleWidget#568]
Google Chrome 46.0.2490.71(Linux(Ubuntu 14.04.3 LTS) 32bit)にアップデートして以降ウィジェット(v1.6.7.5)の画面キャプチャ関連の動作がおかしいです。Appモードで利用していますがWHITEモードでも同じ現象が発生するようです。

・「進撃/撤退選択時に艦娘の状態を表示する」機能で正常に表示されないことがある
![kcwidget_fail_grub_status_moz95](https://cloud.githubusercontent.com/assets/97727/10474289/f01e887c-726f-11e5-9568-27667ab835a7.jpg)
画像の通り。だが稀に正常に表示されることもある。

・「入渠・建造時完了通知」のOCR認識による自動登録機能が動作しない
取得中窓が出たまま何も起きない。

・スクリーンショットに失敗する。
真っ白だったり黒い点だったり。その後にCtrl+Shift+0やスクショボタンを押しても編集画面が出なくなる(ブラウザを再起動するまで？)。

現在確認できている問題は以上の通りです。よろしくお願いいたします。

**Comment by otiai10** [comment]
MacOSX 10.10.5
46.0.2490.71 (Official Build) （64 ビット）

で再現しました。Chromeの問題っぽいですが、できるかぎり調べてみます。

**Comment by otiai10** [comment]
# 現象の概要

1. 大破進撃防止窓の画像srcがempty `src="data:,"`
2. タイマー登録時backgroundでerror `Error in response to tabs.captureVisibleTab: IndexSizeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.`
3. スクショ撮れない__ことがある__ `Error in response to tabs.captureVisibleTab: InvalidStateError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.`

((2))
<img width="815" alt="2015-10-14 14 53 35" src="https://cloud.githubusercontent.com/assets/931554/10475890/66b2885e-7283-11e5-9ddc-1397f6fc7e4d.png">

((3))
<img width="816" alt="2015-10-14 14 54 36" src="https://cloud.githubusercontent.com/assets/931554/10475903/89df1338-7283-11e5-80df-75867f69ae8d.png">

**Comment by otiai10** [comment]
# 対応方針

1. 現在開発中のGIFキャプチャを暫定的に使う（夜戦突入時もみれる！すごい！）
2. タイマー登録時キャプチャエラーはサーバエラーと同じUIに集約する
3. エラーちゃんとハンドリングして、GIFキャプチャに誘導する

**Comment by otiai10** [comment]
jpgなら撮れる。デフォルトでpng指定してるところを直そう。

1. [大破進撃防止](https://github.com/otiai10/kanColleWidget/blob/develop/typescript/src/infrastructure/capture/capture.ts#L12-L16)
2. [タイマー](https://github.com/otiai10/kanColleWidget/blob/develop/src/js/definitions/process/DetectTime.js#L55)
3. [編成キャプチャ](https://github.com/otiai10/kanColleWidget/blob/develop/src/js/pages/hensei-capture.js#L105)

**Comment by yajamon** [comment]
スクリーンショットアイコンからの経路を開発者ツールで見てみたのですが、dataURIが空っぽになった結果、'broken' state に成ってる、という見方で良いのでしょうか。
![capture](https://cloud.githubusercontent.com/assets/6084855/10533916/afc7fc76-740a-11e5-914a-120c19e35172.PNG)

**Comment by otiai10** [comment]
そうすね。uriが空なのは別問題として、
uriが空だった場合のUIをちゃんとしなきゃいけない感じっすね

**Comment by yajamon** [comment]
なるほどです。

**Comment by yajamon** [comment]
空っぽが気になってもう少し見させて頂いたのですが chrome.tabs.captureVisibleTabの実行時点では画像データあるんですね。
![capture](https://cloud.githubusercontent.com/assets/6084855/10534088/943fe3f8-740d-11e5-8f42-2fe7e1a86df8.PNG)

これが Util.removeBlackBlank(dataUrl) を経由したときに空に成ってしまっているようです。

![capture1](https://cloud.githubusercontent.com/assets/6084855/10534091/c085be1a-740d-11e5-8a1b-60d4b5542d4f.PNG)

**Comment by otiai10** [comment]
なんですと！

**Comment by yajamon** [comment]
どうも生成した img.width, img.height が 0 っぽいです？
img.src に放り込んだ際の挙動が chrome46 から非同期的になったような印象があります。
（元々非同期で、読み込み処理の速度が爆速だったために発生しなかったかもですが）

![capture2](https://cloud.githubusercontent.com/assets/6084855/10534181/8de4d552-740f-11e5-8c61-7fe3954de8f4.PNG)

**Comment by otiai10** [comment]
なるほど、だから「取れることもある」だったんすね

**Comment by yajamon** [comment]
おそらくそうだと思います。
対策はcallbackで処理を繋いでいくことになりそうですね…

**Comment by otiai10** [comment]
https://github.com/otiai10/kanColleWidget/pull/567

**Comment by abyssluke** [comment]
スクショ機能などは動作確認しましたが、編成キャプチャは失敗するっぽいです…
GET unsafe:data:, net::ERR_UNKNOWN_URL_SCHEME

**Comment by otiai10** [comment]
resolved by 1.6.8.2
