### ISSUE TITLE
画質

### ISSUE THREAD

**Issue by macaroon1127** [otiai10/kanColleWidget#601]
先週の20日くらいから艦これウィジェットの画質がいきなり悪くなり艦娘が少し荒く表示されるようになりました
解決方法を教えて下さい

**Comment by otiai10** [comment]
- https://productforums.google.com/forum/#!topic/chrome-ja/n-H9pN6heyo
- https://productforums.google.com/forum/#!category-topic/chrome-ja/ZSfAwTqK5ec
- http://akankore.doorblog.jp/archives/46700079.html
- http://kanmusu.blomaga.jp/articles/55235.html
- http://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q13155329523

よくわからないけどこの辺ですかね。WHIETモードですか？

**Comment by macaroon1127** [comment]
APPでやっていました

**Comment by otiai10** [comment]
Chrome50で治ったらしいっすよ
