### ISSUE TITLE
AdBlockが干渉して通信エラーになっているかも知れません

### ISSUE THREAD

**Issue by waraki** [otiai10/kanColleWidget#639]
はじめまして、warakiと申します。
艦これウィジェットでいつも快適にゲームを楽しんでいます。
ありがとうございます。

ところで、12月9日のメンテ明け以降下記のような事象が発生しています。
・発生条件（ゲーム内）
　出撃後の母港帰投時
　任務達成演出完了時
・発生条件（動作環境）
　OS、ブラウザの種類を問わず、AdBlockが有効になっている
・事象
　通信エラー画面が表示される
・想定される原因など
　AdBlockが干渉している様で、通常のブラウザは艦これのページをブロック対象から除外することで防げます。
　艦これウィジェットの場合、WHITEモードでは下記の設定をホワイトリストとして追加すれば
　問題を回避できますが、通常モードでは下記の設定はおろかDMMのドメインをまるごと除外する
　設定をしても通信エラーが発生します。
　通常モード時とWHITEモード時でリクエストURIが異なるのでしょうか。
　因果関係は私にはよく分かりませんが、艦これウィジェットの開発者さんや利用者にとっては
　災難な話です。

　ホワイトリストの例
　@@|http://www.dmm.com/netgame/social/-/gadgets/=/app_id=854854/?$document
　
現在旅の途中かと思いますが、お時間がある時に対策をご検討いただけると幸いです。

**Comment by otiai10** [comment]
ご報告ありがとうございます。たいへん助かります。

これ、AdBlockとか入れてなかったらそもそも問題再現しないということですかね？
正直ナススベナシな気がしてます。
CC @hourglassx18

ひょっとすると為す術あるのかもしれないけど、他のChrome拡張に干渉する、しかも「AdをBlockする」という目的のChrome拡張に干渉して「AdをBlockしない」という状態をつくるのは、Chrome拡張としてあるべき姿じゃないと思うので、そういうハックはしたくないですね。

**Comment by hourglassx18** [comment]
そうですね、Adblockやμblock等の広告ブロック機能を導入し、なおかつ当該『ABP japanese filter』を購読している環境においてのみ発生すると思います。
ADB系はブラックリスト形式でのフィルタを行っており、当該フィルタは日本語環境用のフィルタリストとしてまず初めに名前が上がるほどの有名どころです

これが通常利用でしたら当該リストの開発gitにissueを上げるのですが…appモードのアクセスが一般的方法でない以上はそれも出来ないですね…

自分もADBをブロックする手法は色々な意味で辞めたほうがいいと思います
