### ISSUE TITLE
複数PC間のタイマ同期がほしい

### ISSUE THREAD

**Issue by xia-sava** [otiai10/kanColleWidget#649]
v1 にあったやつ

**Comment by xia-sava** [comment]
Queue と Config を横断的に storage.sync.set() / get() するみたいなやつをどっかに作る，ですかね……？
chomex の Model に持たせて任せるとかはやりすぎか……

**Comment by otiai10** [comment]
- [今はやらない] chomex.Modelに持たせるのが将来的に正しいかとは思いますが、chomexでchromeオブジェクトを参照したくないのでちょっと工夫したいなという気持ちです。いずれにしても、これは作業として分離できるので、このissueでは考えなくていいかなと思います。
- [今はやらない] v1でset/getをどういう風に呼んでいたかはもはや覚えてないんですが、暗黙的にsetを呼ぶようなことは、作業として分離できるので、これもこのissueでは考えなくていいと思ってます。
- [今はやらない] 「これは同期するこれは同期しない」という設定が必要かと思いますが、これも作業として分離できるので以下略
- **[やること]** 最小要件は以下の感じになるかなと
    1. Models/index.jsに「（将来的にはConfigを受けて）storage.sync.set/getを叩く関数をつくる」
    2. 「セーブ」「ロード」を明示的に行うボタンをどっかに配置する
