### ISSUE TITLE
V1同様画面サイズの選択を出来るようにして欲しい

### ISSUE THREAD

**Issue by PCEDuo** [otiai10/kanColleWidget#653]
任意にサイズ変更できるのは知っているけれどもやはり欲しい。

**Comment by otiai10** [comment]
リストに追加もできるけど、プリセットな画面サイズが「DEFAULT WHITE」と「小型」だけでは不足だ、という主張でよかったですか？

**Comment by otiai10** [comment]
https://github.com/otiai10/kanColleWidget/commit/13a4ef195ffecf754ebe118321ea33cfc6e8fdad

**Comment by PCEDuo** [comment]
ですです、v1での 大サイズと中サイズ があるととてもありがたいです

2016/12/16 午前0:11 "OCHIAI, Hiromu" <notifications@github.com>:
