### ISSUE TITLE
スクショ保存を JPEG にした時のファイルサイズがわりと大きい

### ISSUE THREAD

**Issue by xia-sava** [otiai10/kanColleWidget#658]
v1 だと JPEG なら 300～700KB 程度だったんですが v2 だと 1MB 超えるくらいになります．

**Comment by otiai10** [comment]
https://github.com/otiai10/kanColleWidget/blob/develop/src/js/Util.js#L287

**Comment by xia-sava** [comment]
v1 では capture-destination-size（常に中型サイズでキャプチャ）を false にしてたんで resizeImage() 通ってなかったんですが画像ファイルサイズもっと小さくなっていました．

v2 の https://github.com/otiai10/kanColleWidget/blob/v2/master/src/js/Components/Services/CaptureService/index.js#L16 で quality=100 でキャプチャしてるんですが，これデフォルト値は 92 だそうなので，これかー！って思ったらここだけ 92 にしたり無指定にしてもあまりサイズ減ならず．

ファイル保存時の https://github.com/otiai10/kanColleWidget/blob/v2/master/src/js/Components/Views/Capture/index.js#L184 ここで toDataURL(undefined, 0.92) にしてやると v1 と同程度のサイズになりました．

rate は jpeg と webp の時のみ有効とあるので後者の対処を闇雲に仕込んでしまっても実害はないんですが，なんで前者の対処でアカンのか Canvas まわりをイマイチ把握しきれてないのでまだ追えてなくて，今のところここまでです．

**Comment by otiai10** [comment]
v1のとき、「スクショとるとぼやけるんだけど」みたいに言われたことが多々あって、そういうのもあったので、今回はなるべく触らんとこと思ってました。

もしかしたら、downloadボタンを押した時に、ファイル名を入力させるダイアログ内で、「サイズ変更なし（ ${canvas.width} x ${canvas.height}」「800 x 480」「1600 x 960」というSelectFieldをこっそり追加してもいいかもしんないですね。

あ、いやそうすっと「即ダウンロード」だった場合に無意味か。

**Comment by xia-sava** [comment]
OS のスケーリングが 200% なので v1 の中型も v2 もどちらも内部 800x480 が生成される画像は 1600x960(px) になってるんですが，v1 では画質未指定でタイトル画面が 330KB 前後，v2 だと 1.6MB くらいです．つまり画像ピクセル数の違いではないっぽい．
上述の「保存時にレート 0.92 を指定」だと v1 と同様に 330KB 前後です，まぁ 1.00 だと JPEG でも可逆と同レベルになるので PNG と同じくらいになりますね．

そういえば編集画面に表示される画像ファイルサイズも出力結果と一致してないんですよね，この辺に何かヒントあるかなぁ……メンテ開けたらもうちっと見てみます．

最終的に「保存時に無条件で 0.92 指定させてください」とかになる予感がヒシヒシとしますｗ

**Comment by otiai10** [comment]
> 編集画面に表示される画像ファイルサイズも出力結果と一致してない

これは単に僕の適当な実装のせいだと思います。

**Comment by xia-sava** [comment]
あぁーわかりました https://github.com/otiai10/kanColleWidget/blob/v2/master/src/js/Components/Views/Capture/Canvas.js#L30 ここの 1.0 指定があるから最初のキャプチャ時の quality を落としても保存時にファイルサイズが膨れあがる模様でした．

CaptureService は 100 で撮って，スクショの保存時だけ画質指定を特にしない（JPEG の q=0.92 は普通の目で判別できる劣化ではないので）ようにしたら良い感じになりそうです．

ファイルサイズ表示の方も修正できるかどうかやってみますー

**Comment by otiai10** [comment]
ありがとうございます。勉強させていただきます！ 🙇

**Comment by xia-sava** [comment]
色々と確認しました．
大きく分けて，即ダウンロードと編集画面経由で挙動がだいぶ異なります．

まず JPEG の編集画面経由についてですが，編集画面からの保存時に q=1.0 指定を強制していたため画質に対してファイルサイズが大きくなっていた件（アプリコードの問題），これはデフォルト値を undefined にするよう修正しました．
これにより v1 と同レベルの画質・ファイルサイズとなりました．

次に JPEG の即ダウンロードですが，これは caputureVisibleTab() の返す URI をそのまま downloads で保存しており，CaptureService で q=100 としているため上記の編集画面経由よりファイルサイズが大きくなります．
CaptureService が引数で q を受けられるようにして，CaptureController のみが q=92 を渡すようにすると，おそらく編集画面経由と同レベルのファイルサイズになると思われます（まだ試してない）．

PNG の方ですが，これは JPEG とは全然違う問題が発生していて，即ダウンロードと編集画面経由ではやはり後者の方がファイルサイズが大きくなりますが，理由が異なります．
編集画面経由の場合は captureVisibleTab() の出力がいったん Image に変換されてから Canvas に draw されるんですが，この時に，アルファ値（透過情報）が必ず追加されて，RGBx8bit=24bit データが RGBAx8bit=32bit データに変換され，保存時もこのまま保存されます．
つまり，編集画面を経由するだけで，劣化も強化もなしにデータが 4/3 倍になります．
これを防ぐ，というか RGBA を RGB にする方法はまだ見つけていません．軽くググったら「無理．canvas 使うな」とか無慈悲な StackOverflow が出てきましたｗ

というわけでひとまずは png の方は手付かずです（だって自分使ってないしー

**Comment by xia-sava** [comment]
それからファイルサイズ表示の方ですが，上記と似たような理由で img を canvas に渡すとそれだけでファイルサイズが変動するんですが，コードが初期表示を img の方のサイズを表示していて齟齬が発生していたので，ここはもう諦めて毎回きちんと canvas から getImageURI() してリアルなサイズを求めるよう修正しました．
ちょっと重くなっちゃいますがまぁ許してください……

**Comment by xia-sava** [comment]
作業してて見つけたんですが，png の時にファイルサイズのトコをクリックしてサイズ縮小すると jpeg 扱いしてから q を下げてると思うんですが，最終的に保存の時にそれを png で保存して，低 q な jpeg のモスキートノイズで逆にエントロピー上げて png ファイルサイズが増大してる気がします．

サイズ縮小ボタンを一度でも押したら，Config の設定がどうであれその画像に関しては jpeg であるとして扱うよう一貫する必要がありそうです．

（……が，自分で png 使ってないのでひとまず報告まで

**Comment by otiai10** [comment]
なるほど。勉強になります。

**Comment by otiai10** [comment]
closeでいいっすよね（マージされたし、当方あんま困ってないので）

**Comment by xia-sava** [comment]
こちらも現状のコードで困らないので，いいと思います！
