### ISSUE TITLE
v2にて[APP]でウィンドウを開くと黒い帯が入る。

### ISSUE THREAD

**Issue by anmi01** [otiai10/kanColleWidget#667]
[APP]に設定したプリセットで開いたウィンドウにすべての上部に黒い帯が入ります。
v1でも入っていたのですがv1ではLAUNCH APPを押し直すことで解消できていました。

再現環境：Windows 10 64bit、Google Chrome 55 (64bit)

![2016-12-20 4](https://cloud.githubusercontent.com/assets/24665087/21338883/8a283844-c6bd-11e6-8295-91c6bdc17806.png)

**Comment by otiai10** [comment]
これわかんないなー

**Comment by anmi01** [comment]
[LAUNCH APP]ボタンを実装し直していただけませんか？
いままではそれで対処できていたので。

**Comment by otiai10** [comment]
所感を述べますと、プログラマとして、そういうのは面白くないので、ちゃんと原因を知って、ちゃんと直したいと思っております。このプロジェクトは広告も入れてないし何も利益発生していないどころか心ないユーザにいろいろ言われるデメリットすらあるので、せめてプログラマとして実装がたのしくないことはやりません。v2移行は、「ユーザ様」のためにやっているのではなく、開発者が使い易いツールの追求と、好んで使ってくれる「ファン」（≠ ユーザ）のために開発するという原点に立ち返っています。

なお、この問題に関しては、設定からheightを変更することで、回避できませんか？

**Comment by otiai10** [comment]
@anmi01 さんって、あんみさんですよね？ もしお時間あればSkypeできませんか？ 問題が起きている画面の開発者コンソールが見たいです。

**Comment by otiai10** [comment]
メモ: デバイスの画面の大きさを超えている可能性がある。
