### ISSUE TITLE
（ポップアップだけでなく、）【クロックモードにも、時間表示を「のこり時間表示」にする】設定が欲しいです。

### ISSUE THREAD

**Issue by hiroshi1101** [otiai10/kanColleWidget#671]

**Comment by otiai10** [comment]
@hiroshi1101 この修正自体は簡単なので、やっておきます。

ついでにお聞きしたいんですが、表示形式は、クロックモードにも反映させたいですか？表示形式というのはつまり「タイムライン形式」「種類別艦隊順」と表現されている項目のことです。

**Comment by hiroshi1101** [comment]
はい！表示形式は、クロックモードにも反映させたいです。

**Comment by otiai10** [comment]
そうすっと、クロックモードの縦の長さが問題になってくると思いますが、いかがです？

**Comment by hiroshi1101** [comment]
v1同様に、「種類別タイムライン」のような表示が見やすいです。

**Comment by otiai10** [comment]
あー理解です。やってみます。
