### ISSUE TITLE
夜戦突入選択画面で、【自艦隊】と【敵艦隊】の損傷度合を見たいのですがどうでしょうか？

### ISSUE THREAD

**Issue by hiroshi1101** [otiai10/kanColleWidget#680]

**Comment by otiai10** [comment]
ご要望ありがとうございます。かつて考慮したうえで諦めてる過去がありますが、v2が正式にリリースしたら取り組みたいと思っています。

**Comment by otiai10** [comment]
@hiroshi1101 もし可能でしたら、新しく「機能要望・バグ報告」のフォームをつくりましたので、そちらからissue立て直していただいてもいいでしょうか。ここはいったんクローズさせていただきます。
