### ISSUE TITLE
v2のキャプチャ　編集画面にならない

### ISSUE THREAD

**Issue by rikuya12** [otiai10/kanColleWidget#693]

**Comment by rikuya12** [comment]
キャプチャボタンを押すと下記のＵＲＬになり真っ白
chrome-extension://egkgleinehaapbpijnlpbllfeejjpceb/dest/html/capture.html?img=data%3Aimage/png%3Bbase64%2CiVBORw0KGgoAAAANSUhEUgAAAyAAAAHgCAIAAADSZZ6iAAAgAElEQVR4nOS9edBt2XUX9ltr7X3uvd/wXr9%2BPU9qSS2pZQ3tGcuDZApjG2HAQBJCMRXl（ここから先も同じようなものが続く）　動画も同様です

**Comment by otiai10** [comment]
@rikuya12 こちらでのご報告たいへん助かります。ありがとうございます 🙇 

1) 艦これウィジェットのバージョンはいくつですか？ ↓ 2.0.35と書いてある部分です。
![image](https://cloud.githubusercontent.com/assets/931554/22152206/fcfdd938-df21-11e6-9f73-3f6ba4f2acd1.png)

2) 真っ白の状態で `右クリック` → `要素の検証` → `Console` で表示されているもののスクリーンショットをください。こういうやつです

![image](https://cloud.githubusercontent.com/assets/931554/22152299/72ac5966-df22-11e6-941c-937c33158e26.png)

**Comment by rikuya12** [comment]
バージョンは最新　2.0.35です
![0](https://cloud.githubusercontent.com/assets/25247783/22152446/569631c2-df66-11e6-8d96-0e2656b7f9c9.jpg)

**Comment by otiai10** [comment]
あー

**Comment by otiai10** [comment]
@rikuya12 使っているPCのOSのバージョンはいくつですか？

**Comment by otiai10** [comment]
@otiai10
memo: https://github.com/otiai10/kanColleWidget/blob/v2/master/src/js/Components/Views/Capture/index.js#L66

`SearchParams` が無いなこれ

**Comment by rikuya12** [comment]
![1](https://cloud.githubusercontent.com/assets/25247783/22152698/7567c24a-df67-11e6-98b5-c72929c7b683.jpg)

**Comment by otiai10** [comment]
@rikuya12 五月雨質問ですみません、Chromeのバージョンはいくつですか？ `chrome://version/` で分かるやつです

**Comment by rikuya12** [comment]
![1](https://cloud.githubusercontent.com/assets/25247783/22152811/ddc92f68-df67-11e6-8e12-fa1cbd7ff399.jpg)

**Comment by otiai10** [comment]
ビンゴ！ Chrome51以上にアップデートすれば解決するかと思います。

**Comment by otiai10** [comment]
@rikuya12 アップデートした後の挙動を観測したらいずれにしてもここにコメントいただいていいですか。治ってればclose、治らなければ引き続き質問させてください。

**Comment by rikuya12** [comment]
vistaではクロームのサポートが終わっているそうです（最新のバージョンが利用できない）
いろいろお手数かけました　ありがとうございます
