### ISSUE TITLE
「右上ポップアップの背景カスタマイズ」が反映されない

### ISSUE THREAD

**Issue by tomo-jis4352** [otiai10/kanColleWidget#696]
# 画面

「右上ポップアップ」および「艦これウィジェットの設定」

# 観測される問題

設定前と同様の白い背景のまま

# 期待される挙動

指定した画像が表示される

# 再現方法

「右上ポップアップの背景カスタマイズ」のボタンをおして、画像を指定するところまではいけます。
その後開くボタンを押しても、背景に画像は表示されません。

Windows10では、同じ画像を使用して右上ポップアップと設定画面のどちらも表示されました。

-------

環境

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36

バージョン

> 2.0.36

**Comment by otiai10** [comment]
@tomo-jis4352 
ありがとうございます。設定画面において、"画像指定するものの何も起きない"ときにConsoleに表示されているものをスクショでいただけますか。ついでに、ポップアップそのもののスクショもいただけると助かります。

**Comment by tomo-jis4352** [comment]
こちらの環境の問題だったようです。
Chromeを再インストール（設定を初期化）したところ、背景が表示されるようになりました。
お騒がせしました。

> Consoleに表示されているものをスクショでいただけますか。

スクショを撮ろうとしたところ、そもそもConsoleが表示できませんでした。
そこで"~/Library/Application Support/Google/Chrome"を削除してChromeの設定を初期化し
改めて「右上ポップアップの背景カスタマイズ」の設定を行ったところ、
無事背景が表示されました。
