### ISSUE TITLE
敵連合艦隊において大破進撃防止窓の設定が反映されていない

### ISSUE THREAD

**Issue by URSK11** [otiai10/kanColleWidget#697]
# 画面

大破進撃防止窓

# 観測される問題

6-5（おそらく敵連合艦隊なら他でも？こちらが連合艦隊の場合も同様に発生する？）において、
設定画面の大破進撃防止窓の項目が「設定しない」にも関わらず、
ゲーム画面左上に大破進撃防止窓が出て来る
https://gyazo.com/4aeca2b44dd7445bef4baefb7aa39b5a
（設定しない以外に設定した場合の挙動は未確認）

# 期待される挙動

連合艦隊時でも設定画面の大破進撃防止窓の項目通りに大破進撃防止窓を出す（or出さない）

# 再現方法

１.大破進撃防止窓の設定を「設定しない」に設定
２.6-5ボスマスで戦闘を行い、戦闘報告画面を見る
３.ゲーム画面左上にカーソルを合わせると大破進撃防止窓が出て来る

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

バージョン

> 2.0.36

**Comment by otiai10** [comment]
<blockquote class="twitter-tweet" data-lang="en"><p lang="ja" dir="ltr"><a href="https://twitter.com/KanColleWidget">@KanColleWidget</a> 6-5で大破確認窓の挙動が変という報告は上がってますか？自軍は通常艦隊なのに連合艦隊用の確認窓(第二艦隊キャプチャ)が出たり非表示になるタイミングがおかしかったりします(戦闘開始しても表示が消えない)<br>ボス前空襲マスあたりからおかしくなります。</p>&mdash; Sep (@jaqwatdas) <a href="https://twitter.com/jaqwatdas/status/818703572388835329">January 10, 2017</a></blockquote>

**Comment by otiai10** [comment]
「自軍が通常艦隊なのに連合艦隊用の窓が出る」件は別issueとして処理します。
