### ISSUE TITLE
画面上スクショボタンってどうでしょう？

### ISSUE THREAD

**Issue by xia-sava** [otiai10/kanColleWidget#702]
現在ある画面上ミュートボタンみたく，画面上スクショボタンを配置する．
場所はまぁミュートボタンの横とか下とか……？

# 解決される問題

クロックモードが手前になくてもキーボード使わなくても気軽にスクショ出来たらいいかなーと思いました．

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

バージョン

> 2.0.37

**Comment by otiai10** [comment]
ありがとうございます。わりと考えてました。クリックしてマウスオーバーで表示されている領域を消してからスクショ撮るmessageを送る、という点だけ懸念ですかね。

**Comment by otiai10** [comment]
https://github.com/otiai10/kanColleWidget/blob/v2/master/src/js/entrypoints/pages/osapi.dmm.js#L19

**Comment by otiai10** [comment]
https://github.com/otiai10/kanColleWidget/blob/v2/master/src/js/Components/Routine/InAppActionButtons.js#L34
これを事前につくっといてメンバにしとけばよさそう

**Comment by xia-sava** [comment]
わぁ早！ ありがとうございますー！
