### ISSUE TITLE
大破防止窓をクリックした時、ゲーム画面を前面に出す

### ISSUE THREAD

**Issue by GeorgesLonghill** [otiai10/kanColleWidget#703]
v１の頃出来た、大破画面をクリックした時に、ゲーム画面を前面に出す機能をつけて欲しいです。

# 解決される問題

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36

バージョン

> 2.0.37

**Comment by otiai10** [comment]
@GeorgesLonghill 解決される問題はなんですか
