### ISSUE TITLE
一発起動できるようになりませんか？

### ISSUE THREAD

**Issue by sasayou1** [otiai10/kanColleWidget#706]
現在はウィジェット起動時、前回選択したサイズが表示されそれをクリックするとデフォ小型＋好みの設定から起動したいサイズ選択することで起動しますが、v1で慣れてしまっているため2回クリックしないと起動できないのがもどかしいです。自分はAPPしか使わないので出来るならv1みたいなボタン形式を任意で選択できるようにしてほしいです…

# 解決される問題

クリック回数

-------

環境

> Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

バージョン

> 2.0.38

**Comment by otiai10** [comment]
@sasayou1 ありがとうございます。
もしキーボードをお使いなら、右上が表示された状態でエンターキーを押せばクリック回数は減ります。
あるいは、クロックモードを使っていたら、そちらからも起動できます。

いずれにしても

> v1みたいなボタン形式を任意で選択

これは検討してみます

**Comment by sasayou1** [comment]
@otiai10 ご返答ありがとうございます、試してみます！

**Comment by otiai10** [comment]
@sasayou1 もし上記の使い方が問題を解決する場合は、このissueをcloseします。
そうでない場合は、

> v1みたいなボタン形式を任意で選択

これを実装しますので、いずれにしても、試したあとコメントいただけると助かります。 ☺️

**Comment by sasayou1** [comment]
@otiai10 キーボードショートカットと併用することで確かに先の煩わしさは解消されますね！

現状はそこそこに満足できているのでボタン形式はあれば欲しいなー程度です！

**Comment by otiai10** [comment]
思ったんですが、前回選択サイズが必ず1番上にくるのだから、ダブルクリックしたらそれっぽい挙動になるんじゃないですか。どうすか？w

**Comment by GeorgesLonghill** [comment]
v1の頃のほうが起動に関してはスムーズであったので、サイズ選択を経ずにワンクリックで起動できたほうが良いとは思います。
比べるとどうしても煩わしい感じが残ってしまっていますので……できれば、自分からもお願いします。

**Comment by otiai10** [comment]
@GeorgesLonghill ダブルクリックではどうですか？
