### ISSUE TITLE
通知のポップアップ設定について

### ISSUE THREAD

**Issue by gchaka** [otiai10/kanColleWidget#709]
v1では通知に対して「登録時」「終了時」のポップアップの有無を設定出来ましたが、v2でも同様の設定を実装して頂けないでしょうか。自分は遠征終了時のみ音声で通知を行っていましたので、同じ事が出来ると助かります。Chromeからの誘導有難う御座いました。

# 解決される問題

v1との機能差分

-------

環境

> Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

バージョン

> 2.0.38

**Comment by otiai10** [comment]
@gchaka ありがとうございます。

まず大きな質問なんですが、これは、すべての通知種類に関して共通の設定、ということでよいですか？そうでなければ、各種（遠征・修復・etc...）ごとに設定したいですか？

次に細かい質問なんですが、取り得る設定はどのようなものがあるでしょうか？自分がすげー簡単に考えて

| 登録時 | 終了時 |
|:--:|:--:|
| 消す | 消す |
| 消す | 消えない |
| 消えない | 消す |
| 消えない | 消えない |

**※ すべての「終了時」において音声設定してあれば音声は再生する**

ということかなと思っています。

**Comment by gchaka** [comment]
迅速な御回答有難う御座います。また、中途半端な要望内容で申し訳御座いません。私個人としましては、v1同様、全ての通知に対して共通で「開始時」「終了時」のポップアップ有無の設定を考えておりました。ですので上記頂いております、「取り得る設定」通りのパターンが全ての通知の共通設定としてあるとの考えでした。音声に関しましても上記otiai10様のお考え通り、「設定してあれば音声再生を行う」という事で良いと考えております。

**Comment by otiai10** [comment]
ありがとうございます。もう僕自身v1を長らく使っていないので、v1の仕様教えてもらえるのは助かります。やってみます。

**Comment by gchaka** [comment]
今しがた、登録時のポップアップが正常に出なくなる事を確認致しました。迅速な御対応有難う御座いました。
