### ISSUE TITLE
遠征出し忘れ通知について

### ISSUE THREAD

**Issue by yuichinishimura** [otiai10/kanColleWidget#715]
第二～第四艦隊がある一定の時間以上、遠征に出ていない場合に通知を入れる機能がほしいです。
タイマーパネルやウィジェットアイコンを注意深く見ていれば遠征出し忘れは防げると思いますが、ゲームウィジェットのみ出してプレイすることが多いため、通知という形での実装をお願いします。

# 解決される問題

遠征出し忘れ防止

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

バージョン

> 2.0.38

**Comment by otiai10** [comment]
> ゲームウィジェットのみ出してプレイすることが多いため、通知という形での実装をお願いします

これに関してのソリューションにはなっていないですが、同様の機能を「遠征強化令」という名前で出しました。とりあえずそちらの反応を見てから、実装するしないを決めさせていただければと思います。

**Comment by yuichinishimura** [comment]
遠征強化令について確認致しました。
素晴らしいアイデアだとは思いますが、先述した通りダッシュボードは開かずにプレイすることが多いです。
お手数おかけしますが、ゲームウィジェットのみ利用している状態であっても、
遠征強化令と同様の通知をユーザが検知できるよう実装をお願い致します。

**Comment by otiai10** [comment]
僕は遠征強化令でわりと満足していますが、ダッシュボード開かない場合のソリューションは検討してみます。それは必ずしも通知ではないと思っています。

**Comment by otiai10** [comment]
@yuichinishimura 結果からいうと、通知のほうがよかったですね！今ではめちゃくちゃ気に入ってます。ありがとうございます 🙇 👍

**Comment by yuichinishimura** [comment]
いえ、こちらこそお手数おかけして申し訳ありません（プルリクなり投げられれば良かったのですが…）
今後も便利に利用させて頂きます🙇
