### ISSUE TITLE
夜戦突入選択画面で、【自艦隊】と【敵艦隊】の損傷度合を見たい

### ISSUE THREAD

**Issue by hiroshi1101** [otiai10/kanColleWidget#720]
現状の【大破進撃防止窓】のようなものを、
夜戦突入選択画面で、
【自艦隊】と【敵艦隊】の両方とも表示して欲しいです。

# 解決される問題

勝利条件や任務条件を満たすために夜戦をしたい、
そうでない場合は夜戦をしたくない、
という場合が多々ありますが、
戦闘画面を見逃した場合でも、それを判断することが出来るようになります。

-------

環境

> Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

バージョン

> 2.0.40

**Comment by otiai10** [comment]
related: https://github.com/otiai10/kanColleWidget/issues/316

**Comment by otiai10** [comment]
無理なのでcloseします
