### ISSUE TITLE
通知音の音量設定について

### ISSUE THREAD

**Issue by himari1543** [otiai10/kanColleWidget#722]
現在、通知設定欄から通知音の音量設定は出来るようになっていますが、これは全部まとめて設定するようになっています。
私が使っていて思うのは、使っている音声ファイルはそれぞれ音量が異なるので、ウィジェットの方で設定したところで、結局それぞれの音量に違いがでてしまい、遠征通知音は大きいけれど、入渠通知音は小さい、という状態になっていしまうということです。
タイマー音それぞれ個別に音量の設定が出来るようにお願いいたします。

# 解決される問題

個別の通知音量設定

-------

環境

> Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

バージョン

> 2.0.40

**Comment by yajamon** [comment]
自分で編集してしまうのもひとつの選択肢として

MP3Gain - 窓の杜ライブラリ
http://forest.watch.impress.co.jp/library/software/mp3gain/

SoundEngine Free【音楽編集・音声録音フリーソフト】
http://soundengine.jp/software/soundengine/

**Comment by otiai10** [comment]
@himari1543 ありがとうございます。
「解決される問題」は、解決策や、解決後の状態ではなく、この機能によって取り除かれる **問題** を書いてください。

**Comment by otiai10** [comment]
v1ってどうなってましたっけ？

**Comment by yajamon** [comment]
@otiai10 
v1での UIは以下な感じで

![cap1](https://cloud.githubusercontent.com/assets/6084855/22550992/116aca38-e996-11e6-984c-349de3e1a2d4.PNG)
![cap3](https://cloud.githubusercontent.com/assets/6084855/22551024/468c69ec-e996-11e6-932f-e8a92fa8b7c3.PNG)

音声再生のコードは以下あたりです？

https://github.com/otiai10/kanColleWidget/blob/v1.5.10.4/src/js/Notifier.js#L76-L100

**Comment by otiai10** [comment]
@yajamon ありがとうございます。

@himari1543 
v1では個別に音量設定していないようなので、v2も同様の方針でいきたいと思います。

**Comment by himari1543** [comment]
@yajamon 
フリーソフトの紹介ありがとうございます。Sound Engineは私も時々使用しているのですが、音量を統一するために編集するのがどうも慣れなくて、ウィジェットの方で個別設定できないかとお願いしてしまいました。

@otiai10 
まず「解決される問題」についての表記間違いすみませんでした。他のissueも見ながら書いたのですが、理解が足らず、申し訳ないです。
また、v1と同様の方針とのこと、了解いたしました。迅速な対応、ありがとうございました。
