### ISSUE TITLE
クロックモード 各タイマーの上書き/手動解除

### ISSUE THREAD

**Issue by calbattery** [otiai10/kanColleWidget#723]
クロックモードの各タイマーについて、
設定済みのタイマーを手動登録で時間を設定し直す
手動登録の手順で0:00を設定すると解除できる仕様 (v1ではできてた気がする)

# 解決される問題

高速修復材を使用した場合にタイマーが登録されることがある問題
登録されたタイマーを解除/上書きできない問題

-------

環境

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36

バージョン

> 2.0.40

**Comment by otiai10** [comment]
@calbattery ありがとうございます。
「解決される問題」は、解決策や、解決後の状態ではなく、この機能によって取り除かれる問題を書いてください。

**Comment by calbattery** [comment]
変な勘違いをしておりました。申し訳ありません。
以下のように訂正いたします。
訂正前)
高速修復材を使用した際にも登録されてしまう(ことがある)タイマーを上書き/解除できる
↓
訂正後) 
高速修復材を使用した場合にタイマーが登録されることがある問題
登録されたタイマーを解除/上書きできない問題

**Comment by otiai10** [comment]
ありがとうございます。問題は3つあるってことですよね。

> 高速修復材を使用した場合にタイマーが登録されることがある問題

これに関しては、実装すべきなのでします（そういや久しくバケツ使ってなかったんで気付かなかったっすw）。

> 登録されたタイマーを解除

これも、必要なのでやりたいと思います。ただ、0:00を入力してクリアってのはかっこわるいのでどうにかします。

> 上書きできない問題

これはもうありますよね？ご確認いただけると幸いです。

**Comment by calbattery** [comment]
返信ありがとうございます。
>上書きできない問題

この問題に関してなのですが
(1) 手動でタイマーを登録
(2) (1)と同じ場所をクリックして再度登録
といった流れで上書きをやろうとすると(2)の際"登録"を押しても何も起きませんでした
(登録しますか？の画面が出たまま。"しません"は問題なく押せる)

(もうある=既出という意味でしたら該当のissueを見つけることができませんでした。申し訳ありません。。)

**Comment by otiai10** [comment]
いや、なるほど、これはバグですね。上書きできない。ありがとうございます。

**Comment by otiai10** [comment]
@otiai10

- 高速修復/建造剤を使ったときタイマーセットしないこと
- マニュアル登録モーダルで、上書きができていないこと
- マニュアル登録モーダルで、セット済みの値をデフォで表示すること
- マニュアル登録モーダルで、「解除」ボタンを設置すること

このへん
https://github.com/otiai10/kanColleWidget/blob/master/src/js/Components/Views/Dashboard/Contents/Dialogs/ManualTimerDialog.js#L82-L85

**Comment by otiai10** [comment]
TODO
- [ ] 高速修復/建造剤を使ったときタイマーセットしないこと
- [ ] マニュアル登録モーダルで、上書きができていないこと
- [ ] マニュアル登録モーダルで、セット済みの値をデフォで表示すること
- [ ] マニュアル登録モーダルで、「解除」ボタンを設置すること

**Comment by calbattery** [comment]
対応ありがとうございました。
タイマー登録/解除 問題なく行えてます。
(反応遅くなりました。すみません
