### ISSUE TITLE
右下通知が、開始系：自然消失、終了系：消えない

### ISSUE THREAD

**Issue by admiralycoris** [otiai10/kanColleWidget#725]
# 画面

右下ぼのちゃんの通知が、種類によって自然に消えるものと、待っても消えないものがあります

# 観測される問題

自然に消えたもの：遠征開始、建造開始、おやすみします
残ったもの：遠征帰投、建造完了、疲労回復、修復終了

# 期待される挙動

すべての通知が自然に消えると助かります。可能であれば、消せる/残せるを選択できるとなおありがたいです。

# 再現方法

当方で変更した設定は
・通知に音声を付けた
・twitter連携した
・新しい窓を作った（ADDで出てくるサイズそのまま、APPモード）
これらの現象は新しく作ったAPPモードの窓でみられました。

-------

環境

> Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

バージョン

> 2.0.40

**Comment by otiai10** [comment]
@admiralycoris ありがとうございます。

現状その挙動は仕様です。機能要望として、実装します。

**Comment by admiralycoris** [comment]
ご返信ありがとうございます。
仕様であった旨承知いたしました。早合点してバグとして投稿してしまい、申し訳ありませんでした。
可能であれば、お手すきの折に実装していただけますとありがたいです。
