### ISSUE TITLE
[APP]設定な窓を開いた際にwww.dmm.comのズーム設定の影響を受ける

### ISSUE THREAD

**Issue by cabbagejirou** [otiai10/kanColleWidget#726]
# 画面

新規に開いたゲーム窓

# 観測される問題

艦これウィジェットとは無関係なタイミングで予めwww.dmm.comのズーム設定を変更した状態で、[APP]設定の窓を開くと、窓がズームの影響を受けてしまい設定された通りのサイズで開かれてくれない

# 期待される挙動

v1の時にはズーム設定が何％に設定されていようともLAUNCH APPから起動した窓は「中型」なら中型、「極小」なら極小…と期待通りのサイズで窓が開かれていた。v2でも同等の挙動を期待したいのだが…

# 再現方法

www.dmm.com に行き、CTRL+マウスホイール等でページのズームを変更しておく。その後艦これウィジェットv2から[APP]モードな設定で窓を開くだけ。これにより例えば遊べない位小さな「大型」設定の窓が開かれたり、画面いっぱいに広がった「小型」の窓が開かれたりしてしまう

-------

環境

> Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

バージョン

> 2.0.40

**Comment by otiai10** [comment]
これは根が深そうだ...

**Comment by otiai10** [comment]
@otiai10 たぶんタイトルバー考慮の `resizeBy` のところで取得できる `window.innerHeight` とかがzoomにひっぱられてるんじゃないかしら

**Comment by otiai10** [comment]
@cabbagejirou これって、一瞬タイミング置いて、画面の外枠が大きく期待と違う大きさに変化する、って理解でいいですか？
