### ISSUE TITLE
デイリーのカウンターについて

### ISSUE THREAD

**Issue by Youn1998** [otiai10/kanColleWidget#727]
# 画面

clock modeのポップアップ

# 観測される問題

演習、開発、建造の回数が記録されない

# 期待される挙動

こちらの操作に合わせて記録される

# 再現方法

演習、開発、建造を行った時に以前のバージョンでは記録できていたのができなくなっています。
艦これはWHITEで開いています。

-------

環境

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

バージョン

> 2.0.40

**Comment by otiai10** [comment]
これはわりと意図的です。この機能追加は全く難しくないので、誰かやってくれないかなという気持ちがあります。

**Comment by otiai10** [comment]
pull-requestお待ちしております

**Comment by Acrylban** [comment]
一部分だけ追加した（と思う）pull-requestを送らせていただきましたが、ものすごいお目汚しのような気がしなくも。
[https://github.com/otiai10/kanColleWidget/pull/734](url)

**Comment by otiai10** [comment]
- [ ]  SORTIE,
- [ ] PRACTICE,
- [ ] MISSION,
- [x] RECOVERY,
- [x] SUPPLY,
- [ ] CREATEITEM,
- [x] CREATESHIP,
- [ ] REMODEL,
- [x] CUSTOMIZE,
- [ ] DESTROYSHIP,

**Comment by otiai10** [comment]
@Acrylban 遠征って、支援はカウントすべきではないんですか？

**Comment by Acrylban** [comment]
お疲れ様です。
遠征任務などの進行（カウント）条件に支援が含まれていないようなので、着手時に除外すべきかと考えていました。
しかしこれって個人の都合（ここの記録をウィークリーの進捗確認に使いたいなど）なので、言われてみれば確かに除外はどうなのかな、と……。

**Comment by otiai10** [comment]
ありがとうございます。
コードとしてはほんの数行の条件を入れるだけだとは思うんですが、明らかにエレガントではない感じになりますね。それとおっしゃった通りユースケースを考えると、実装コストに対する利益があまりよくないと思いますので、現時点ではスルーでいいかな、と思います。
どっかでissueが立ったら対応、って感じかなと。
