### ISSUE TITLE
通知が自動で消える機能

### ISSUE THREAD

**Issue by Youn1998** [otiai10/kanColleWidget#728]
通知ポップアップをいちいち手動で消すのがめんどくさいです

# 解決される問題

・上記のめんどくささが解消
・艦これがもっと楽に楽しくプレイできる

-------

環境

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

バージョン

> 2.0.40

**Comment by otiai10** [comment]
#725 とduplicatedなのでcloseします
