### ISSUE TITLE
クロックモードの実行数カウンタ（週）がリセットされない

### ISSUE THREAD

**Issue by Acrylban** [otiai10/kanColleWidget#733]
# 画面

クロックモードの任務関連タブ

# 観測される問題

（恐らく機能実装以降）週内カウントが週でリセットされず累積されている

# 期待される挙動

艦これ時間月曜5時にリセットされる

# 再現方法

月曜に表示されているカウントが正当なものか確認する……？

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

バージョン

> 2.0.42

**Comment by Acrylban** [comment]
すみません、今確認しましたら未実装機能のようですね。

**Comment by otiai10** [comment]
たしかに #727 とは似ていますが、あえて別のものとして扱ったほうが都合がよいので、このissueは残しておきます。
