### ISSUE TITLE
希望する追加機能です。

### ISSUE THREAD

**Issue by anipapa01** [otiai10/kanColleWidget#742]
# 画面

遠征画面・入渠画面・建造画面

# 観測される問題

時刻がとれないことがあります。

# 期待される挙動

アプリ側で「今キャプチャする」ボタンのようなものがあり、
仮に画面の取得に失敗しても、例えば入渠画面を表示中にそのボタンを押すと
再キャプチャ出きるような機能があるとうれしいです。

# 再現方法

-------

環境

> Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36

バージョン

> 2.0.42

**Comment by otiai10** [comment]
1. それは「バグ報告」用のフォームなので、「機能要望」を選択してください
2. 概要は、お気持ちではなく、概要を書いてください
3. こちらと重複してないですかね #700
