### ISSUE TITLE
スクショ取得時のファイル名称不正

### ISSUE THREAD

**Issue by genotome** [otiai10/kanColleWidget#754]
# 画面

時計別窓

# 観測される問題

ファイル名称が「ダウンロード」となる

# 期待される挙動

設定画面にて設定したファイル名称（「yyyymmddhhmmss」等）

# 再現方法

chrome上の曙アイコン→吹き出し下部の時計アイコン→時計別窓左上のカメラボタン→名前を付けて保存画面のファイル名称が「ダウンロード」

-------

環境

> Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

バージョン

> 2.0.42

**Comment by otiai10** [comment]
とりあえず当方の環境では再現しなかったのですが、さらに詳細な再現方法をおしえてください。

![download](https://cloud.githubusercontent.com/assets/931554/22884789/f5555660-f1f6-11e6-95c1-b4294319aba2.gif)

![download2](https://cloud.githubusercontent.com/assets/931554/22884837/2b7a2ab8-f1f7-11e6-9d11-4bf3399903fb.gif)

**Comment by otiai10** [comment]
@genotome コメントが無い場合はcloseします

**Comment by genotome** [comment]
ちょと待って下さいね…

**Comment by genotome** [comment]
![02171](https://cloud.githubusercontent.com/assets/25743093/23062943/563ee62e-f54b-11e6-8ea7-4b9899799593.png)
![02172](https://cloud.githubusercontent.com/assets/25743093/23062949/61b61b76-f54b-11e6-90f1-b59cb88556a1.png)
動画の撮り方分からんのでこれ以上の再現方法の説明はできません

**Comment by otiai10** [comment]
`kancolle_yyyyMMdd_HHmmss` `.png`

**Comment by otiai10** [comment]
再現しないので一旦closeします
