### ISSUE TITLE
WIKI表示

### ISSUE THREAD

**Issue by syou-0124** [otiai10/kanColleWidget#756]
早見表に、建造と開発レシピのページを追加してほしい。

# 解決される問題

建造や開発をするたびに、検索をしなくて良くなる。

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

バージョン

> 2.0.42

**Comment by otiai10** [comment]
https://github.com/otiai10/kanColleWidget/blob/develop/CONTRIBUTING.md

**Comment by otiai10** [comment]
CONTRIBUTIONG.md とりあえず読んでいただきたいのと、
https://github.com/otiai10/kanColleWidget/blob/develop/src/js/Components/Views/Wiki/index.js
この機能とっても簡単なのでたぶん僕がやらなくても誰かpull-requestしてくれると思います。
