### ISSUE TITLE
WHITEモードの大破進撃防止窓は常に同窓表示？

### ISSUE THREAD

**Issue by Shadow01124** [otiai10/kanColleWidget#757]
# 画面

戦闘後のリザルト画面

# 観測される問題

別窓表示の設定をしていても、WHITEモードではゲーム画面内に表示された。

# 期待される挙動

大破進撃防止窓の別窓表示の設定をしている場合は、ゲーム画面外に出てほしい。

# 再現方法

別窓表示の設定にしてからWHITEモードで起動し、出撃する

-------

環境

> Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

バージョン

> 2.0.42

**Comment by otiai10** [comment]
#751 と重複です

**Comment by Shadow01124** [comment]
すでに同じ問題が上がっていましたね…。失礼しました。

**Comment by otiai10** [comment]
いずれにしてもご報告ありがたいです
