### ISSUE TITLE
明石の泊地修理について

### ISSUE THREAD

**Issue by swallou** [otiai10/kanColleWidget#769]
明石が第一艦隊の旗艦になって母港に戻ってからの時間をカウントしてほしいです。

# 解決される問題

明石の泊地修理は２０分毎に行われるので、この機能が実装されれば開始時間を覚えていなくても、例えば開始時間から36分経っていた場合後四分で修理されると分かったり、また開始時間から２２分経っていた場合後18分後に修理されるならバケツを使ってしまおうと判断できるようになったりするので便利だと思いました。

-------

環境

> Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

バージョン

> 2.0.43

**Comment by otiai10** [comment]
https://github.com/otiai10/kanColleWidget/blob/develop/CONTRIBUTING.md

@swallou ありがとうございます。
解決される問題には *問題* を書いてください

**Comment by swallou** [comment]
しっかり読み込んでから書き込めばよかったですね、大変申し訳ありませんでした。

解決される問題
明石の修理時間の経過を把握できない問題。

**Comment by otiai10** [comment]
@swallou 日常的に使いますか？イベント中だけ？

**Comment by otiai10** [comment]
2014年の発言ですが

<blockquote class="twitter-tweet" data-lang="en"><p lang="ja" dir="ltr"><a href="https://twitter.com/otiai10">@otiai10</a> バケツが貴重品なら需要あるんでしょうけどね・・・現状、PCの前で明石回復を正座して待つ人がどれほどいるか・・・ってことでしょうね。</p>&mdash; bassingmagic＠大湊提督 (@bassingmagic) <a href="https://twitter.com/bassingmagic/status/463907291767382016">May 7, 2014</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="en"><p lang="ja" dir="ltr"><a href="https://twitter.com/otiai10">@otiai10</a> 「明石を旗艦にして編成画面から母港画面に戻ったタイミングから，以降 20分おきに，残りの艦の耐久がちょっとずつ回復する」です．「旗艦にしたタイミング」でなく「編成後に母港に戻ったタイミング」が基点なんですなー．</p>&mdash; ISIGE, Akira (xia) (@xia_sava) <a href="https://twitter.com/xia_sava/status/463892223432486913">May 7, 2014</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by otiai10** [comment]
@swallou 

> 解決される問題
> 明石の修理時間の経過を把握できない問題。

把握できないとどんな問題が発生するんですか？

**Comment by otiai10** [comment]
@xia-sava 巻き込んですみません。
そもそも明石の修復って、どの艦娘についても20分で1回復なんでしたっけ？

**Comment by swallou** [comment]
周回をする際に使うので、イベント中に使いますね。

把握できないとどんな問題が発生するか？については
明石の修理を行っている際にスムーズに行動が取りづらいという問題です。

**Comment by xia-sava** [comment]
> そもそも明石の修復って、どの艦娘についても20分で1回復なんでしたっけ？

1 以上の場合もあります，「明石旗艦の艦隊を編成変更したタイミング」を起点として，そこから20分以上経ってから「母港画面に戻ったタイミング」で修理量が各艦ごとに判定されますが，この時「耐久 1 回復するのに20分より多くかかる艦」であっても最低 1 は回復します．

例えば明石旗艦としてそれぞれ「30分・20分・11分・10分」が「1 回復するのに必要な時間」である艦を組んでからぴったり20分後に母港に戻った場合，耐久回復量はそれぞれ「1・1・1・2」となります．22分後だったなら「1・1・2・2」となりますね．

**Comment by otiai10** [comment]
なるほど、ということは「回復量の可視化」とはなりえなくても、20分はいずれにしても単位だから、カウントすることには意味がある、ってことですね。

実装上の問題は、「明石を旗艦にした」というのが果たして取れるのかっていうことですね...

**Comment by otiai10** [comment]
控えから編成加入させたとき・既存でドラッグアンドドロップしたとき、同じ

```
api_req_hensei/change

api_ship_id: 2918, // <- たぶんこれエンティティIDなので、鎮守府によって一定じゃない
api_ship_idx: 0, // <- たぶんこれ旗艦
```

**Comment by otiai10** [comment]
# 現状での結論

1. 「明石を」旗艦にしたというリクエストが検知できない
    - ship_idでリクエストが飛んでいるので、各提督の鎮守府ごとにship_idと「明石」を紐付ける必要がある
    - どっかでかならず `ship_id == 「明石」` が判明するタイミングさえあればどうにかなるかも
2. ユースケースがほぼイベント中である（しらんけど）
3. 僕は需要をあんまり感じてない

という理由から、wontfixの方針です。1が解決されれば、その限りではないかもですが。

cc @swallou

**Comment by otiai10** [comment]
単に、「クリックいっぱつで起動する20分（おき）タイマー」があればいい気もしてきた

**Comment by xia-sava** [comment]
強いて言えば「第1艦隊が編制変更すると自動的に20分タイマー起動」なんてのあればいいのかなーとか昔も考えて機能追加しようかなとか思ったりもしたんですが，使用頻度からして建造タイマーに手動セットで事足りてしまうことに気付いてしまい，その運用にしてますｗ

**Comment by swallou** [comment]
了解しました。貴重なお時間を割いてしまい申し訳ありません。
検討していただきありがとうございました！
