### ISSUE TITLE
スクショツイートをショートカットキーでできるようになりませんか？

### ISSUE THREAD

**Issue by admiralycoris** [otiai10/kanColleWidget#773]
現在、Tweetをクリックしないとスクショをツイートできないのですが、v1のようにショートカットキー(Ctrl+Enterなど)でツイートできるようにならないでしょうか。

# 解決される問題

ツイート内容をキーボードで入力し、そのままキーボード操作で(マウスを動かすことなく)ツイートができるようになると大変便利です。
お忙しいとは存じますが、機能追加につきご検討いただけますと幸いです。

-------

環境

> Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

バージョン

> 2.0.44

**Comment by otiai10** [comment]
今後、問題は、問題を書いてください。この場合、「画像のスクショ→ツイートの完了までにマウスを触る必要があるという問題」みたいな感じになると思います。
