### ISSUE TITLE
疲労タイマーをローテーション出撃に対応させたい

### ISSUE THREAD

**Issue by peescae** [otiai10/kanColleWidget#784]
従来の疲労タイマーでは艦隊ごとに疲労を管理し、出撃時に対象の艦隊の疲労時間をリセットしていますが、（艦隊プリセット機能を用いた）ローテーション出撃を行う場合、どの編成にどれだけ疲労が溜まっているかがわからなくなってしまいます。これを解決する機能実装を要望いたします。
　具体的には、現行動作の「出撃時に疲労時間を上書き」を廃止（設定でオン／オフ）し「出撃時に新しい疲労ゲージを、今ある疲労ゲージの下に追加する」「不要になった疲労ゲージはクリックで消せる」といった実装を提案いたします。
　もっと良い実装方法があるような気もしますが、ご一考よろしくお願いいたします。

# 解決される問題

（艦隊プリセット機能を用いた）ローテーション出撃を行った際に、どの編成にどれだけ疲労が残っているかが把握できない問題

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

バージョン

> 2.0.45

**Comment by otiai10** [comment]
![image](https://cloud.githubusercontent.com/assets/931554/23580086/03693998-00fb-11e7-918e-689ae7b3aec8.png)

**Comment by peescae** [comment]
ありがとうございます！
まさにこういうのが欲しかったんです。とても助かります。
