### ISSUE TITLE
大破進撃防止アラート

### ISSUE THREAD

**Issue by crinum** [otiai10/kanColleWidget#786]
大破進撃防止窓とゲーム画面を閉じるときのアラートをくみあわせたもので，リザルト画面のキャプチャ時に大破艦がいた場合アラートを出すというもの．精度は高くなくてもよく，あくまでお守り程度の機能

# 解決される問題

主にながらプレイング時，画面を注視しないことによる大破進撃があるという問題

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

バージョン

> 2.0.46

**Comment by otiai10** [comment]
@crinum 素朴な質問なんですけど、どうやって「大破艦がいる」と検知するつもりですか？

**Comment by crinum** [comment]
@otiai10 「大破」のマークの表示される座標は常に同じなように見えたのでマークで…と思いましたが厳しいですかね...？素人考えで恐縮ですがなにぶん開発等に関しては無知なもので...(なら要望を出すな←)

**Comment by otiai10** [comment]
なんかこれ同じような要望がかつてあった気がするんですけど、どっかいっちゃったっぽいっすね。技術的にけっこうだるいっすねこれ。あと「アラート」っていうのは一体何をイメージしていますか？たとえば、艦隊状況を画面内に出す設定にしていたら、それ以上のeye catchingな見せ方はできない気がしているんですが。

**Comment by crinum** [comment]
@otiai10 技術的に大変ですか...私はあくまで使わさせてもらっている側なので厳しいようでしたら無理と一蹴してもらって構いません(;´･ω･)
「アラート」はゲーム画面を閉じるときの「このページを離れ(ry」のような操作しなければ消せないものを，厳しいようなら遠征帰投時に出てくるアレを考えていました
