### ISSUE TITLE
前回終了時の位置以外の場所に起動してしまうことがある

### ISSUE THREAD

**Issue by mafurya** [otiai10/kanColleWidget#793]
# 画面

少なくとも[APP] で切り出したゲームウィンドウ

# 観測される問題

左上や、Chromeウィンドウの左下に起動してしまうことがある

# 期待される挙動

前回終了時の位置で起動する

# 再現方法

右上ボタンからAPPモードで起動する設定にした項目をコンボボックスから選ぶ、すでに選択されているAPPモードで起動する設定を一発起動ボタンから起動する

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

バージョン

> 2.0.47

**Comment by mafurya** [comment]
補足です
毎回終了し、次回も起動してほしい位置がここで
![k01](https://cloud.githubusercontent.com/assets/25608139/24038444/be66fd36-0b44-11e7-847a-a9a7ee3f140e.jpg)

なぜか起動してしまうことのあるChromeウィンドウの左下というのはここです
![k02](https://cloud.githubusercontent.com/assets/25608139/24038495/02ea6f6a-0b45-11e7-9d19-6e96d37b2ed3.jpg)

ちゃんとデスクトップの左下に起動してくれることもあるのですが
左上、デスクトップ左下、Chromeの左下どこに起動されるかは毎回ランダムといっていいような状態です

**Comment by otiai10** [comment]
@mafurya ありがとうございます。とりあえず当方の環境では全く再現しません。「ランダム」ではなく、もうちょっと具体的に、この場合はデスクトップ左下、この場合はクロームの左下、といったように状況を特定していただけると助かります。

**Comment by mafurya** [comment]
@otiai10

１．一発起動ボタンでAPPモードの艦これを起動（以降LAUNCHIすると書きます）し、タイトル画面のままにしておく
２．デスクトップ左下に起動した場合はそのままGAMESTARTボタンを押す。デスクトップ左下以外の場所で起動した場合は、デスクトップ左下まで艦これウィンドウを移動させてからGAMESTARTボタンを押す
３．母港が表示されたら艦これウィンドウを閉じ、再びLAUNCHIする

　という手順を繰り返し取った場合、「デスクトップ左下」に起動する確率がかなり高く、「デスクトップ左上」に起動することがたまにあり、「Chromeの左下」に起動することはありませんでした。

　また、

１．上記を利用しデスクトップ左下に起動したのを確認してGAMESTARTボタンを押す
２．母港が表示されたら艦これウィンドウを閉じ、再びLAUNCHIする
３．デスクトップ左下に起動したのを確認して、タイトル画面のままにしておく
４．Chrome本体のほうでDMM GAMESのトップページを開く
５．艦これウィンドウを閉じ、再びLAUNCHIする

　という手順を繰り返し取った場合、「Chromeの左下」に起動する確率が高く、「デスクトップ左下」に起動することがたまにあり、「デスクトップ左上」に起動することはありませんでした。


　色々試してみましたが同じ手順を繰り返しても結果が変わることがあり、確実な再現方法を見つけるのは難しいかもしれません…。タイトル画面で閉じるというという操作も普段は絶対にやらないのですが、やってもやらなくても「Chromeの左下に起動」することがあるので再現しやすくするための手順として記載しました。

**Comment by otiai10** [comment]
@mafurya なるほど、ありがとうございます。

おそらく原因が2つあります。

1. 起動位置記憶は[15秒ごとに行われている](https://github.com/otiai10/kanColleWidget/blob/develop/src/js/entrypoints/pages/osapi.dmm.js#L31)こと
2. 艦これウィジェットを介さないページの表示（"Chrome本体のほうで"と表現されているもの）[の場合でも](https://github.com/otiai10/kanColleWidget/blob/develop/manifest.json#L100)、起動位置記憶をしてしまっていること

2番はある意味バグなんですが、この2点を考慮して、問題が再現するか検討していただいていいですか？

**Comment by mafurya** [comment]
@otiai10 

・ 1番について

Chromeを開き、一発起動ボタンで艦これをLAUNCHし、艦これウィンドウの位置を保存確認のためにデスクトップの適当な位置にずらし、15秒以上（1分とか5分とか）余裕を持って閉じ、再びLAUNCHする。ということを数十回やってみたのですが、たしかにほぼ毎回「前回終了時の位置」で起動しました。
が、艦これを開き移動し閉じる以外の操作をしていないにもかかわらず一度だけ「Chromeの左下」で起動することがありました。

・ 2番について

これは「艦これウィジェットを介さないページの表示を」した場合、次の起動位置記憶周期がくる前に艦これウィンドウを閉じてしまうと、次の起動位置が「艦これウィンドウを介さないページの表示をしたウィンドウの位置」になってしまう。的な解釈でよかったでしょうか…。（違ったらすみません）

これは数回しか試していないのですがまず「デスクトップ左下」に起動したのを確認したあと、起動位置記憶周期の合間を縫うようにChrome本体でどこかのウェブサイトへアクセスし、すぐさま艦これウィンドウを閉じてまたすぐLAUNCHする。という手順でやったところ8割ぐらいは「Chromeの左下」に起動し、それ以外は「前回終了時の位置（デスクトップの左下）」でした。

**Comment by otiai10** [comment]
ありがとうございます。
2番は、詳しくは「艦これウィジェットを介さない艦これの表示」です。

**Comment by mafurya** [comment]
@otiai10 
Chromeのブックマークバーから艦これのページを開き、15秒以上時間をおいてからページを開いているタブを閉じ、艦これウィジェットからLAUNCHする。というのを5回ほどやりましたがすべて「前回終了時の位置（デスクトップの左下）」に起動しました。

**Comment by otiai10** [comment]
当方の環境で再現されないので、closeさせてください。
