### ISSUE TITLE
戦果自動計算

### ISSUE THREAD

**Issue by NewTsu** [otiai10/kanColleWidget#798]
出撃の統計を自動で取得し、戦果を計算してくれる機能

# 解決される問題

時間短縮及び誤算防止という問題

-------

環境

> Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

バージョン

> 2.0.47

**Comment by otiai10** [comment]
@NewTsu 

- 「出撃の統計」とは何ですか？
- 戦果はどのように決定されるのですか？

艦これそこまでガチ勢ではないので、ご教授いただけるとありがたいです

**Comment by NewTsu** [comment]
@otiai10 
まず「出撃の統計」についてですが、
例えば、１－１に出撃したとすると『１－１に出撃した』というAPIが送信されるようです。
そこでそのAPIを取得することにより、あとから「どこの海域にどれだけ出撃したか、
どのマスで何勝利（B勝利やS勝利など）を取れたか」などがわかります。
それをもとにして表などを作成してもらえるととても助かります。

次に「戦果」についてですが、
戦果というものは、その海域に出て取得した『提督経験値』を　7/10000(0.0007)した値が戦果です。
提督経験値はそれぞれの海域毎に別の値が設定されており、何勝利か でもその提督経験値は変わります。（艦娘がもらっている経験値とは別に、提督経験値というものがあります）
そこで『出撃の統計』で取ったデータから計算して戦果を求めることができる、と考えました。
非公式wikiに海域毎に獲得できる提督経験値の一覧及び計算式も載っているのでそちらに目を通してもらえれば幸いです。

艦これ非公式wiki
・提督経験値一覧
http://wikiwiki.jp/kancolle/?%B7%D0%B8%B3%C3%CD#h2_content_1_9

・戦果の計算式やその他の概要など
http://wikiwiki.jp/kancolle/?%B3%AC%B5%E9

**Comment by otiai10** [comment]
> あとから「どこの海域にどれだけ出撃したか、どのマスで何勝利（B勝利やS勝利など）を取れたか」などがわかります。

わかりません。艦これウィジェットの実装方針の範囲内では、この情報を取得するのはルール違反です。
こちらの資料 https://www.slideshare.net/otiai10/ss-26908975 に目を通してもらえれば幸いです。

**Comment by otiai10** [comment]
航海日誌など併用すれば、戦果集計してくれるんじゃないんですかね。
