### ISSUE TITLE
1-6 Fマス(航空戦マス)の戦闘開始時に大破進撃防止窓が閉じない

### ISSUE THREAD

**Issue by abyssluke** [otiai10/kanColleWidget#803]
# 画面

1-6 Fマス(航空戦マス) 戦闘開始時

# 観測される問題

航空戦マスであるFマス戦闘開始時に大破進撃防止窓が閉じない。
その結果、戦闘結果画面で艦隊状態が2つ(前の通常戦闘マスであるEマスの分とFマスの分)表示される(通常戦闘であるBマス開始時はすべて閉じる)。下記スクショ参照。
同じ航空戦マスであるLマス、Dマスでも同様のことが起こると思われる

![2017-04-01-194047](https://cloud.githubusercontent.com/assets/97727/24582648/03767ef2-176f-11e7-9751-da353a9a8772.png)

# 期待される挙動

航空戦マス(F/L/D)開始時に大破進撃防止窓が閉じる

# 再現方法

1-6でA→E→G→Fの順に通る

-------

環境

> Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

バージョン

> 2.0.48

**Comment by otiai10** [comment]
調査します

**Comment by otiai10** [comment]
```
kcsapi/api_req_sortie/airbattle
```
