### ISSUE TITLE
起動時の表示座標がずれている

### ISSUE THREAD

**Issue by Darkdream765** [otiai10/kanColleWidget#807]
![kancolle_20170407_164529](https://cloud.githubusercontent.com/assets/27000092/24790659/1f203cb4-1bb2-11e7-97e4-b84cb0252a49.png)
艦これウィジェットを起動したときにウィジェット窓の座標が上にずれており、下が見切れています。DMM側の変更に起因するものと思われますが、不便なので修正していただきたいです。

**Comment by otiai10** [comment]
1. まず艦これウィジェットのバグ報告フォームから来てください。環境などいっさいないので何もデバッグできません。
2. 僕の環境（macOS Sierra, Google Chrome	57.0.2987.133 (Official Build) (64-bit)）では再現できません。艦これウィジェット以外のChrome拡張や、ユーザスタイルシートなどが競合している可能性はありませんか？
3. v2ならDEFAULT WHITEであっても設定画面から**自分で**座標を調整できます。
