### ISSUE TITLE
資源推移表の設定をoffにしていても、OCR取得がoffになっていないと思われます。

### ISSUE THREAD

**Issue by hiroshi1101** [otiai10/kanColleWidget#810]
# 画面

資源推移表

# 観測される問題

資源推移表の設定をoffにしていた間の日付（時刻）で、上書きされています。

# 期待される挙動

資源推移表の設定をoffにしたら、その間のOCR取得（上書き）を無効にしてほしいです。

# 再現方法

資源推移表の日付（時刻）等を確認し、資源推移表の設定をoffにします。
編成画面への変移を実施し、資源推移表の設定をonにします。
すると、資源推移表の設定をoffにしていた間の日付（時刻）で上書きされています。

-------

環境

> Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

バージョン

> 2.0.49

**Comment by otiai10** [comment]
たしかに設定見てないですね。
https://github.com/otiai10/kanColleWidget/blob/develop/src/js/Components/Controllers/RequestControllers/Deck.js#L16
時間ができたら直します

**Comment by hiroshi1101** [comment]
すみません！
私が望む姿を思いついたので、
機能要望で上げます。
こちらはcloseして頂いても構いません。
