### ISSUE TITLE
資源推移表の、【自動取得】を廃止してほしい。

### ISSUE THREAD

**Issue by hiroshi1101** [otiai10/kanColleWidget#811]
編成画面への遷移時の、資源推移表の【自動取得】を廃止して、
資源推移表の取得ボタンによる【手動取得】のみにしてほしい。
★追記しました★　また、【上書きしない】ようにしてほしい。

# 解決される問題

①OCRの精度が低いため正確に取得出来ている可能性が低いという問題
②　★削除しました★
③正確に取得出来ていたのに自動で不正確な上書きをされてしまうという問題

※
「毎日・出来るだけ最新の数値だけ、自動で更新したい」という要望がある場合は、
【自動取得】のon/offが出来るようにしてほしいと思いますが、
「備蓄の開始・終了（起床～就寝、イベント終了～次回）やマップ攻略の開始・終了（数時間or数日間）などのタイミングで手動取得」という使い方をしたいです。

-------

環境

> Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

バージョン

> 2.0.49

**Comment by hiroshi1101** [comment]
解決される問題の②は不要でした。すみません。

**Comment by otiai10** [comment]
related #810

**Comment by hiroshi1101** [comment]
申し訳ありません。
詳細に、【上書きしない】を追加でお願い致します。

**Comment by hiroshi1101** [comment]
（最初の投稿に、★追記と削除★を行いました）

**Comment by otiai10** [comment]
②なんでしたっけ？

**Comment by hiroshi1101** [comment]
②は、
「OCR取得が正確な値かどうか、資源推移表を開いて確認しなければならない」という問題でしたが、
解決方法が、「資源推移表を開いて手動取得によって確認する」なので解決しませんでした。

**Comment by otiai10** [comment]
これ上書きしないとグラフの感覚が時系列等間隔にならないな。まあ誰かが指摘したら直そう。
