### ISSUE TITLE
修復タイマーと建造タイマーの挙動がおかしいように見えます。

### ISSUE THREAD

**Issue by hiroshi1101** [otiai10/kanColleWidget#833]
# 画面

アラーム登録画面および通知

# 観測される問題

①修復タイマーと建造タイマーが自動登録されません。
②修復タイマーと建造タイマーの通知設定をＯＦＦにしていても（手動登録したアラームが）通知されます。

# 期待される挙動

①修復タイマーと建造タイマーの自動登録。
②修復タイマーと建造タイマーの通知設定の正常動作。

# 再現方法

①修復と建造を行う。
②修復タイマーと建造タイマーの通知設定をＯＦＦにして、手動でアラームを登録して時間経過を待つ。

-------

環境

> Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36

バージョン

> 2.0.53

**Comment by hiroshi1101** [comment]
②については、「通知ポップアップを出す」をＯＦＦにすると通知されなくなります。

**Comment by otiai10** [comment]
２つのissueにしてください。

**Comment by hiroshi1101** [comment]
修復タイマーと建造タイマーをＯＮにしたら、自動登録されました。
すみません。勘違いしていたのかも知れません・・
以前のバージョンの設定を忘れてしまったので、自分でＯＮにしていたかわからないのですが、
以前のバージョンでは、
「遠征タイマー・修正タイマー・建造タイマーは、設定に関わらず自動登録されていたような気がするのですが、違いましたでしょうか？」

**Comment by otiai10** [comment]
1. [各httpリクエストについてトリガーするコントローラ内でisNotificationEnabledをチェック](https://github.com/otiai10/kanColleWidget/blob/develop/src/js/Components/Controllers/RequestControllers/Recovery.js#L45)
2. [isNotificationEnabledは、全体設定と個別設定両方を見ている](https://github.com/otiai10/kanColleWidget/blob/develop/src/js/Components/Models/Config.js#L4-L9)
3. [デフォルト（設定を変更していない初期状態）では全体設定は有効、入渠の個別設定も有効になっている](https://github.com/otiai10/kanColleWidget/blob/develop/src/js/Components/Models/Config.js#L32-L50)

あんあおで、設定にかかわらず自動登録されるような気がします。偶然、画像解析失敗したんじゃないですかね？

**Comment by otiai10** [comment]
@hiroshi1101 さんって、プログラムちょっとできたりしないんですか？

**Comment by otiai10** [comment]
参加してほしいんですが

**Comment by hiroshi1101** [comment]
・自動登録はちょっと様子を見てみます。こちらは閉じていただいて構いません。
・ごめんなさい。プログラムはまったく出来ません。わがままばかりで申し訳ありません。
