### ISSUE TITLE
資源推移表の自動入力ができない

### ISSUE THREAD

**Issue by syou-0124** [otiai10/kanColleWidget#839]
# 画面

資源推移表

# 観測される問題

画像は取れるが入力されない

# 期待される挙動

自動で入力されるようになる

# 再現方法

自動で入力されるようにする。

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

バージョン

> 2.0.54

**Comment by otiai10** [comment]
画面のサイズとアスペクト比を教えてください。

**Comment by otiai10** [comment]
> 画像は取れるが入力されない

ちょっと意味がわかりません

**Comment by syou-0124** [comment]
手動入力で横に表示される画像は忠作表示されるけど、自動で入力してくれないということです。

**Comment by otiai10** [comment]
@syou-0124 問題の画面のスクショをください。

**Comment by syou-0124** [comment]
それは、手動入力で表示される画像のことですか?

**Comment by otiai10** [comment]
あなたが問題だと思われる部分です。今どうあって、本来どうあるべきか、僕は現状では全く理解していません。

**Comment by syou-0124** [comment]
![default](https://cloud.githubusercontent.com/assets/25746730/25942054/9e75c81a-3676-11e7-8dd0-a99d27a1dd25.PNG)

**Comment by otiai10** [comment]
1. だからそれの何が問題なんですか？僕には期待された通りに動いているように見えます。
2. 設定の「資源推移表を使う」の項目の他の設定は試しましたか？
3. 設定の「資源推移表を使う」の項目の説明は読みましたか？

**Comment by syou-0124** [comment]
資源推移表は自分が説明を読んで、画像解析をして自動でグラフに入力されるようになっていると思っているのですが。
自動取得や手動取得での話です。手動入力はこの写真を撮るために変えただけです。

**Comment by otiai10** [comment]
> 自動取得や手動取得での話です。手動入力はこの写真を撮るために変えただけです。

変えたら問題の画面のスクショではないのではないですか？どういう設定のもと何をすると何が起きてほしいか教えてください。

**Comment by syou-0124** [comment]
すみません。趣旨を間違えていたようです。
自動取得や手動取得に設定したときに、資源推移表に何も変化がありません。
PCはフルHDで、ゲーム画面は800×480です。
編成画面に遷移して、ほかの条件もすべてクリアしてのですが。

**Comment by otiai10** [comment]
> 自動取得や手動取得に設定したときに、資源推移表に何も変化がありません。
> PCはフルHDで、ゲーム画面は800×480です。
> 編成画面に遷移して、ほかの条件もすべてクリアしてのですが。

把握しました

**Comment by otiai10** [comment]
1. 「手動 **入力** 」という設定は、手動で入力されるための設定なので、手動で入れてください。
2. 「手動 **取得** 」という設定は、画像認識で値の取得を試みます。
3. 「自動 **取得** 」という設定は、編成画面への遷移をトリガーとして、画像認識で値の取得を試みます。

本件の問題点は以下だと思われます

1. 手動 **入力** ダイアログが現れたときに、手動 **入力** 用であることを明示していない点
2. 説明に書いてある条件をすべて満たしていると思われるのに **取得** が失敗する点
3. **取得** を試みたときに失敗の理由がわからない点
    - そのため、なにを改善すればよいか不明である点
    - 可能であれば、フェイルオーバーとして手動 **入力** ダイアログが現れてくれればなお良い

いかがでしょうか。 @syou-0124

**Comment by syou-0124** [comment]
はい、大丈夫です。
ありがとうございました。

**Comment by otiai10** [comment]
#881 に集約しました。ここはいったんcloseします 🙇
