### ISSUE TITLE
スクショサイズの固定機能

### ISSUE THREAD

**Issue by Massy-mz** [otiai10/kanColleWidget#842]
v1の「スクショった結果は常に中型の大きさにしてくれ」機能の追加

# 解決される問題

スクショ画像が取得時のウィンドウの大きさに依存する問題

-------

環境

> Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36

バージョン

> 2.0.55

**Comment by otiai10** [comment]
スクショ画像が取得時のウィンドウの大きさに依存してしまうと、具体的に何が問題なんですか？それを書いてください。

**Comment by Massy-mz** [comment]
テンプレにあったので「問題」という書き方をしましたが、
不具合のようなものではありません。

敢えて言うならスクショ後に毎回リサイズ保存する手間が省ける、
といったところでしょうか。

現在はメインウィンドウをタイマーをv2で使用し、
スクショ撮る時にv1のclock modeを起動して
そちらで撮ってます(推奨する使い方では無いと思いますが)

**Comment by otiai10** [comment]
なぜリサイズして同じサイズにする必要があるんですか？

**Comment by Massy-mz** [comment]
HPやSNSで使用する際に＆単純に保存する際にサイズを統一したい、といったところでしょうか。

重ねてになりますが
「v1であったこの機能をv2でも引き継いでくれたらありがたい」
といった感じですので。

**Comment by otiai10** [comment]
@Massy-mz 
やろうとしてるんですが、再現方法がわかりません。どういう設定でどうダウンロードしたらサイズがゲーム画面に依存してバラバラになりますか？

**Comment by Massy-mz** [comment]
関係ありそうな設定項目としては、
・スクショしたらそのままダウンロードする：ON
・窓設定：大型(初期値：1200*720,[APP])

[取得再現手順]
①ヴィジェット起動
②ヴィジェットの大きさを手動で調整
③スクショ実行(自動ダウンロード)


画面解像度は[1280*800]ですが、
②の大きさを画面の約1/4程度に小さくしてスクショを撮った場合の画像サイズは[650*400]、
同様にほぼフル画面の大きさにして撮った場合の画像サイズは[1170*700]と、
スクショ取得時のヴィジェットの大きさが小さければ画像サイズも小さくなり、
大きければ同様に大きくなる、という状況です。

そもそもの話として「最初からウィンドウサイズを固定したまま変えない」とすれば
いいのかもしれませんが、タブレット端末の為、縦・横両方で使用していますので
その際にウインドウサイズを手動で変えています。
