### ISSUE TITLE
ツイート時に文字数制限を超えた場合でも入力内容を保持させる

### ISSUE THREAD

**Issue by HonkyandJack** [otiai10/kanColleWidget#845]
文字数を超えたツイートを誤って入力した場合に、直前に入力した文章を保持させることで再編集を容易にさせる。資材推移のようなデフォルト入力文字数が多い場合140文字をオーバーすることがある

# 解決される問題

140文字を超えた場合に直前の入力内容が破棄される問題

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

バージョン

> 2.0.55

**Comment by otiai10** [comment]
ついでに
![image](https://cloud.githubusercontent.com/assets/931554/26382999/13ba3cca-406b-11e7-9168-0ed8f8341000.png)
