### ISSUE TITLE
特定条件下で誤った資源記録の値が検出される

### ISSUE THREAD

**Issue by syou-0124** [otiai10/kanColleWidget#847]
# 画面

資源推移表

# 観測される問題

資源がゲーム内で10000以上になったときに資源推移表では1になっている

# 期待される挙動

10000以上まで読み取れるようにしてほしい

# 再現方法

ゲーム内で資源を10000以上にする

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

バージョン

> 2.0.55

**Comment by syou-0124** [comment]
![default](https://cloud.githubusercontent.com/assets/25746730/26495068/e629464a-425c-11e7-8e05-a05ab0475e4c.PNG)

**Comment by syou-0124** [comment]
![default](https://cloud.githubusercontent.com/assets/25746730/26495089/001079d4-425d-11e7-98f1-652c9e739b2c.PNG)
スクショです。

**Comment by otiai10** [comment]
アスペクト比そのままでなるべく大きくしたときはどうなりますか

**Comment by syou-0124** [comment]
そのように設定していますが、この現象が起きています。

**Comment by otiai10** [comment]
@syou-0124 とりあえず画像解析使ってるっていう事実はご存知ですか？

**Comment by syou-0124** [comment]
はい。知っています。

**Comment by otiai10** [comment]
#881 に集約しました。ここはいったんcloseします 🙇
