### ISSUE TITLE
コメント編集が出来ない時がある

### ISSUE THREAD

**Issue by humohumosanae** [otiai10/kanColleWidget#849]
# 画面

編成画面・戦績表示画面

# 観測される問題

コメント編集後、更新ボタンを押しても反映されず、編集前の文章に戻ってしまう。

# 期待される挙動

更新ボタンを押し、画面下にロード中表示が出たあとコメントが更新される。

# 再現方法

不明。文字の半角全角は関係なし。正常に更新できることもあるが出来ないことのほうが多い。ublockのアドオンは停止させても編集できないこともあったし、逆につけていても編集できたときもあった。ウィンドウモードはサイズにぴったり合わせるモード。

-------

環境

> Chrome/ 58.0.3029.110 (64-bit)

バージョン

> 2.0.56

**Comment by otiai10** [comment]
ありがとうございます。既知の問題です。

- 艦隊名・コメントの編集は、DMMのログイン状態が必要です
- したがって、ゲーム画面（艦これドメインの部分）を切り出す [APPモード] では、艦隊名・コメントの編集は基本的にはできません
    - ログインし直してすぐ、というタイミングならできるかもしれませんが、基本的にはできないと思ってください
- [WHITEモード] を使えば可能です

**Comment by humohumosanae** [comment]
返信ありがとうございます。
