### ISSUE TITLE
資源情報取得の不具合

### ISSUE THREAD

**Issue by akira1222mtn** [otiai10/kanColleWidget#857]
# 画面

資源推移表

# 観測される問題

手動または自動で資源の情報の取得が行われた際に、燃料(本来は１１万ほどある)が「１」と読み取られてしまう。

# 期待される挙動

資源の値を常に正確に取得してほしい。

# 再現方法

中型・大型に関わらず、資源情報を取得しようとすると、発生する。

-------

環境

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

バージョン

> 2.0.56

**Comment by otiai10** [comment]
[ここ](https://github.com/otiai10/kanColleWidget/blob/develop/src/js/Components/Services/Rectangle/index.js#L45-L49)のチューニングですね。あと画像の二値化とかしてもいいかも。二値化だけなら、つくりかけの[こいつ](https://github.com/otiai10/crescentjs)が使えるかも。僕はしばらく普通に仕事が忙しいので、誰かがやるかもしれないです。

**Comment by akira1222mtn** [comment]
ご返答ありがとうございます。仕事が一段落したら、ぜひお願いいたします。

**Comment by otiai10** [comment]
#881 に集約しました。ここはいったんcloseします 🙇
