### ISSUE TITLE
建造・修復タイマー及び資源推移の取得漏れ

### ISSUE THREAD

**Issue by KidoAmaha** [otiai10/kanColleWidget#859]
# 画面

タイマー画面・資源推移表

# 観測される問題

遠征と任務と出撃時間は取得されタイマーや達成未達成が表示されるが建造・修復・資源推移が取得されないのか表示されない

# 期待される挙動

建造・修復タイマー及び資源推移が取得表示される

# 再現方法

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

バージョン

> 2.0.60

**Comment by otiai10** [comment]
- 再現方法がないです
- 画像がないので何のことかわかりません
- 設定はどうなってますか。設定のスクショをください。
