### ISSUE TITLE
【要望】資源推移記録の手動入力モードの入力ボタンの自動化と後でまとめて入力

### ISSUE THREAD

**Issue by ta-yamaoka** [otiai10/kanColleWidget#861]
### 前提条件、現在の機能の認識
現在ある手動入力機能は、任意のタイミングで入力ボタンを押すと、資源部分のスクショが撮影されて
それを見ながら入力する機能であると把握しています。

### 期待される新機能、要望
- 入力ボタンを押さなくても自動で資源のスクショを撮影（入力ボタンの自動化）
- 取りためたスクショからまとめて入力する機能（まとめて入力機能）

# 解決される問題

- 資源推移記録を手動入力する場合に手動で入力ボタンを押す必要がある問題
- 手動入力の場合に、入力を忘れてしまう問題

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

バージョン

> 2.0.60

**Comment by ta-yamaoka** [comment]
後でまとめて入力する機能の作りこみも大変そうだなと思い
現状の自動取得の機能に対して
- スクショを捨てないで貯めて置く
- 資源レコードをクリックしたときに表示されるダイアログにスクショが表示されている

といった感じが良いかなと考えました
下記は実装イメージです

![image](https://user-images.githubusercontent.com/11879583/27740533-49741ec2-5ded-11e7-8ff6-49455d9f8ce0.png)

**Comment by otiai10** [comment]
「画像を溜めとく」っていう行為がけっこう厳しい気がするんですよね...

**Comment by otiai10** [comment]
#881 に集約しました。ここはいったんcloseします 🙇
