### ISSUE TITLE
2-5-Dで前回の大破進撃窓が消えない

### ISSUE THREAD

**Issue by Roadagain** [otiai10/kanColleWidget#862]
# 画面

2-5(沖ノ島沖)Dマスリザルト画面 大破進撃窓

# 観測される問題

前回(Aマス)の損害状況が表示され続け、大破進撃窓が連合第2艦隊と同様の位置で表示される

# 期待される挙動

Dマスでの損害状況のみ表示される

# 再現方法

2-5に出撃しDマスで戦闘を行う

-------

環境

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

バージョン

> 2.0.60

**Comment by otiai10** [comment]
- https://github.com/otiai10/kanColleWidget/blob/develop/src/js/Components/Routes/WebRequestRoutes.js#L46-L49
- https://github.com/otiai10/kanColleWidget/blob/v1/master/src/js/definitions/Dispatcher.js#L42

たぶんこれだと思います

**Comment by Roadagain** [comment]
原因箇所の特定ありがとうございます。
ただ、後者は1行下の `api_req_battle_midnight/sp_midnight` のようです。
https://github.com/otiai10/kanColleWidget/blob/v1/master/src/js/definitions/Dispatcher.js#L43
こちらにハンドラを追加したところバグが解消されました。
CIでのテストも通ったので、PR出してもよろしいですか？

**Comment by otiai10** [comment]
@Roadagain ぜひお願いします。
もし可能なら、v1のDispatcherでforSortieBattleを呼ぶべきルーティングを全部移植していただけるとありがたいです。
