### ISSUE TITLE
資源推移記録のグラフの数値が異なっている

### ISSUE THREAD

**Issue by kazuki005** [otiai10/kanColleWidget#866]
# 画面

資源推移記録

# 観測される問題

取得した際、グラフの数値が実際の数値と異なっている

# 期待される挙動

取得を行うと正しい数値がグラフに反映される

# 再現方法

要求されている条件（画面が中型以上、縦横比が800x480）で取得を行っています

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

バージョン

> 2.0.61

**Comment by otiai10** [comment]
すでに報告されているissueと重複はありませんか？また、画像解析であることを理解していますか？

必ず返信してください

**Comment by kazuki005** [comment]
返信ありがとうございます
画像解析である事は理解しています
それお踏まえて上手く画像解析出来る方法がありましたらお教えして下さるとありがたいです

**Comment by kazuki005** [comment]
あと問題の重複してるのではという件ですが確かに似てるいる問題がありました
お教えしていただきありがとうございます

**Comment by otiai10** [comment]
@kazuki005 似ていると思われるissueにコメント頂けると助かります。類似のissueを乱立させると管理に困るのとモチベーション下がりますので。

**Comment by otiai10** [comment]
#881 に集約しました。ここはいったんcloseします 🙇
