### ISSUE TITLE
窓設定

### ISSUE THREAD

**Issue by AdmiralMasyu** [otiai10/kanColleWidget#867]
# 画面

艦これウィジェットの設定

# 観測される問題

窓設定で名前の変更ができません

# 期待される挙動

改善お願いします

# 再現方法

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

バージョン

> 2.0.56

**Comment by otiai10** [comment]
問題の画面のスクショください
