### ISSUE TITLE
音声出力が出来なくなる

### ISSUE THREAD

**Issue by sqnyceo** [otiai10/kanColleWidget#870]
# 画面

音声

# 観測される問題

かなり前からですが、USB-DACを使用すると、そのDACの電源をOFFにして　帰宅して電源ON　としても、
音声が出力されない状態になります。　その時、mute,unmute等実施しても改善しません。
同様の状況のはずのchrome等他の音声を出力するアプリケーションではこのような事は発生していません。

# 期待される挙動

ウィジェットからの出力先が無くなった際に、音声出力が停止してしまっている様に見受けられます。
音声出力先が見つかり次第、再開　と出来てほしいです。

# 再現方法

おそらくですが、USB-DACを使用していれば、電源を落とした際に復帰しなくなると思います。
もしくはそれが無い場合、PC上のサウンドデバイスを一旦無効化し、再度有効化しても同じことが起こるのではないかと思います。

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36 USB DAC UDA-1

バージョン

> 2.0.56

**Comment by sqnyceo** [comment]
ユーザーインパクトはそれほど高く無いと思われますので、
優先度低で大丈夫です。
これが修正されると、私個人の利便性が上がるだけですので・・・

**Comment by otiai10** [comment]
艦これウィジェット起因ですか？Chrome起因ですか？艦これウィジェットはChrome拡張ですので、ネイティブに近い部分はどうにもできないことが多いです

**Comment by sqnyceo** [comment]
Chromeから出力される他の音声は正常ですので、
Chrome起因ではないと思うのですが・・・
ウィジェットが使用している、Chrome提供の仕組みの仕様となると
私のレベルでは切り分けが難しいです。すみません。
使用に支障が出るということでもありませんので、一応、そういう事もある　程度のお話でした。

残しておくのも邪魔かとおもいますので、Close致します。
