### ISSUE TITLE
ゲーム画面を閉じるときのアラートについて

### ISSUE THREAD

**Issue by M-Unknown** [otiai10/kanColleWidget#871]
# 画面

ゲーム画面全般

# 観測される問題

オプションのゲーム画面設定にあるゲーム画面を閉じるときアラートを出す設定を有効にしても機能しません。

# 期待される挙動

設定通りの挙動にしてほしい

# 再現方法

オプションのゲーム画面設定にあるゲーム画面を閉じるときアラートを出す設定を有効にする
その際に画面右上にミュートボタンを出す設定は無効にして下さい

-------

環境

> Chrome/59.0.3071.115

バージョン

> 2.0.61

**Comment by otiai10** [comment]
APPですかWHITEですか

**Comment by M-Unknown** [comment]
APPです
