### ISSUE TITLE
通知ポップアップが消えない

### ISSUE THREAD

**Issue by jaqwatdas** [otiai10/kanColleWidget#872]
# 画面

疲労・修復完了等の通知ポップアップ

# 観測される問題

疲労回復通知や修復完了通知が通知表示のどこをクリックしても消えずに表示され続けます。
消すにはChromeを終了させるか艦これウィジェットを停止するか、条件は不明ですが、稀に新たな通知が発生したタイミングで消えることがあります。

# 期待される挙動

クリックすれば通知が消える。

# 再現方法

完全な再現方法がないのですが、おおよその発生条件として以下の状況で高頻度で発生します。
・通知がマシンがスリープ中、またはディスプレイスリープ中に発生する
・通知ポップアップを見えるまんまにするの設定がON(関係は不明)
・セカンダリモニタ(Retina)でプレイしている(関係は不明)

-------

環境

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

バージョン

> 2.0.61

**Comment by otiai10** [comment]
@jaqwatdas 

僕の環境だと、

1. onClickで消えるようにしてるのに、消えないことがある
    - その場合は、nativeの[close]（添付画像参照）を押せば消える
2. どうしたって消えない、という現象は起きない

![image](https://user-images.githubusercontent.com/931554/27759926-ab5575a8-5e76-11e7-92ad-0f094c4dca74.png)

いずれにしてもChromeがけっこうアップデート入れてきたんで、ほっといたら治るかなとも思ってます

**Comment by jaqwatdas** [comment]
スクリーンショットを拝見する感じChrome v59のOSネイティブの通知表示とお見受けします。
Chrome v58までの旧通知ポップアップで発生していました。
先ほど気づいてChromeをアップデートして、通知表示が変更されました。
これで解決しそうに思います。
お騒がせいたしました。ご対応ありがとうございました。

**Comment by otiai10** [comment]
確認ありがとうございます。とりあえず閉めます。
