### ISSUE TITLE
通知ポップアップの時間変更

### ISSUE THREAD

**Issue by JoyandJoy** [otiai10/kanColleWidget#875]
通知ポップアップの時間を1分以外にも変更できるようになりませんか？
例えば2分前や3分前通知といったようにです

# 解決される問題

以下が改善されると予測される問題
・旧版を使っていた人が新版に変わり使いにくくなったとアドオンの使用を終了する問題
・演習開始前や出撃中に表示されると即時対応できないので遠征や入渠が終了後すぐに遠征や入居が行うことができない問題
・プレイスタイルは一つではない。様々なプレイスタイルがあっていい。現状では一つしかない。プレイスタイルの幅を狭めている問題

-------

環境

> Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2900.1 Iron Safari/537.36

バージョン

> 2.0.62

**Comment by otiai10** [comment]
> 旧版を使っていた人が新版に変わり使いにくくなったとアドオンの使用を終了する問題

- 使いにくくなったと思うなら仕様を終了すればいいと思います。このソフトウェアはビジネスではないので、僕はそこを問題としません

> 演習開始前や出撃中に表示されると即時対応できないので遠征や入渠が終了後すぐに遠征や入居が行うことができない問題

- それは1分だろが3分だろうが設定で変えるようにしようが同じなのではないでしょうか？

> プレイスタイルは一つではない。様々なプレイスタイルがあっていい。現状では一つしかない。プレイスタイルの幅を狭めている問題

- これはプレイスタイルではないですし、問題に共感できません。様々な〜とおっしゃるなら他のツールも様々ありますので、他のツールを使えばよいか、キッチンタイマーなどを使えばいいのではないでしょうか？
    - それでもこのソフトウェアでその「プレイスタイル」をしたいのであれば、ここを編集して使ってください https://github.com/otiai10/kanColleWidget/blob/develop/src/js/Components/Models/Queue/Queue.js#L162

繰り返しになりますが、このソフトウェアはビジネスでもないですし、今となってはただの僕の趣味です。共感できない問題のソリューションを僕が実装する理由がありません。オープンソースですので、forkするなりpull-reqするなりするのがよいかと思います。
