### ISSUE TITLE
スクショに何の部隊かわかる文字がほしい

### ISSUE THREAD

**Issue by JoyandJoy** [otiai10/kanColleWidget#876]
スクリーンショットの編成はずいぶん便利になりました
しかしながら、この画像をみてなんの編成がわからないときがあります
ファイル名だけではなく、画像でも第一部隊なのか第二部隊なのか、道中支援なのか決戦支援なのか
画像を見ただけでも判断できるようになりませんか？
なお、文字無しもあるとうれしいです

# 解決される問題

以下が解決されると予測される問題
・SNS上にアップしたときに説明しなければならない問題
・第三者が見る場合や記憶が薄れた場合にファイル名を見ないとわからない問題
・毎回ファイル名に第一艦隊や道中支援などいちいち説明しなくても入力しなければならない問題

-------

環境

> Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2900.1 Iron Safari/537.36

バージョン

> 2.0.62

**Comment by otiai10** [comment]
![image](https://user-images.githubusercontent.com/931554/27983095-ac71bc98-63ef-11e7-81c1-4e983776a813.png)

これのこと言ってますか？

**Comment by otiai10** [comment]
コメントいただけると幸いです
