### ISSUE TITLE
スクショ作成時にキャプチャ画像を修正したい

### ISSUE THREAD

**Issue by JoyandJoy** [otiai10/kanColleWidget#877]
編成画面で画像を間違えたとき現状では最初からやり直しになります
画像を間違えた場合それを修正できる機能がほしいです

# 解決される問題

キャプチャ画面を間違えたときに最初からやり直さねばならない問題

-------

環境

> Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2900.1 Iron Safari/537.36

バージョン

> 2.0.62

**Comment by otiai10** [comment]
![image](https://user-images.githubusercontent.com/931554/27983084-4cd5757c-63ef-11e7-8c62-29c6e6b3d522.png)

これのこと言ってますか？

**Comment by otiai10** [comment]
コメントいただけると幸いです
