### ISSUE TITLE
窓設定の変更が反映されない

### ISSUE THREAD

**Issue by JoyandJoy** [otiai10/kanColleWidget#878]
# 画面

艦これウィジット全画面

# 観測される問題

{APP}ゲームコンテンツを切り出してウィンドウぴったりの大きさにする
と
[WHITE]ゲームコンテンツの左上がウィンドウの左上になるようずらす
が変更されない

# 期待される挙動

{APP}ゲームコンテンツを切り出してウィンドウぴったりの大きさにする
と
[WHITE]ゲームコンテンツの左上がウィンドウの左上になるようずらす
が自由に変更できる

# 再現方法

１．艦これウィジットの設定画面を表示させる
２．窓設定にて＋ADDを押下する
３．作成画面にて{APP}ゲームコンテンツを切り出してウィンドウぴったりの大きさにするを選択する
４．OKを押下する
５．ブラウザを再起動する
６．艦これウィジットの設定画面を表示させる
７．窓設定にて「３」で作成した画面の設定を選択する
８．設定画面にて[WHITE]ゲームコンテンツの左上がウィンドウの左上になるようずらすを選択する
９．UPDATEを押下する
10．ブラウザを再起動する
11．艦これウィジットで「３」で作成した画面を選択する
12．ゲームを開始する

-------

環境

> Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2900.1 Iron Safari/537.36

バージョン

> 2.0.62

**Comment by otiai10** [comment]
ありがとうございます。確認します

**Comment by otiai10** [comment]
@JoyandJoy 細かい再現方法ありがとうございます。助かりました。

たしかに、確認できました。僕としては、APP↔WHITEの変更は、入力項目が大きく異るという理由で、窓設定作成後にはあまりやってほしくないと思っています。したがって、このバグの回避として「追加済み窓設定のモード（APP/WHITE）の変更はできないようなUIにする」という提案をしたいのですが、いかがでしょうか？
