### ISSUE TITLE
twitterタグ自動付与

### ISSUE THREAD

**Issue by yuuyuu0** [otiai10/kanColleWidget#886]
twitter投稿時に本文にタグを自動で付ける機能を復活させてほしいです

# 解決される問題

twitter投稿時にタグが無い問題

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

バージョン

> 2.0.63

**Comment by otiai10** [comment]
@yuuyuu0 どういう感じでしたっけ？ 自分で任意のタグを設定すると常にそれが付与される感じでしたっけ？v2開発中からずっとv1触ってないので、かなり忘れてます 😭

**Comment by yuuyuu0** [comment]
そうですね、設定画面で設定したワードを、投稿時に本文にタグとして自動で付与してくれるやつです

**Comment by otiai10** [comment]
2.0.64でつくりました。ご確認ください

**Comment by yuuyuu0** [comment]
ありがとうございます！
ただ入力カーソルの位置が末尾になってしまうので、もし技術的に可能であれば初期位置が行頭になるとこの機能を使う人達にとってより便利だと思うのですが、可能でしょうか？

**Comment by otiai10** [comment]
```
修復材: 1462 / 開発材: 3000
燃料: 103k / 鋼材: 300k
弾薬: 92k / ボーキサイト: 73k
#資源記録
```

となるのがデフォルトなので、どこにカーソル合わせるか問題もあります。むしろどこにカーソル合わせるか問題がだるいので、ちょっとイケてるUIつくります...

**Comment by otiai10** [comment]
![image](https://user-images.githubusercontent.com/931554/28540649-6228cbc6-70b6-11e7-9a1d-a48a30388ec4.png)
