### ISSUE TITLE
エラーや出撃中に終了して再開すると画面がブラウザ上のものと同じになる

### ISSUE THREAD

**Issue by JoyandJoy** [otiai10/kanColleWidget#887]
# 画面

ゲーム開始画面

# 観測される問題

ゲーム開始時に画面サイズはデフォルトや大、小などのユーザーが設定したものになるが、
エラーが発生した場合や出撃中に終了して再度起動すると、開始画面がブラウザ上のものと同じになる

# 期待される挙動

いかなる状態で終了しても、ウィジットの画面にあったサイズに自動的に調整されるのが望ましい

# 再現方法

この不具合はフリーズしたときに発生したものである
そのため、フリーズさせるのが好ましいが、その再現はほぼ不可能であると推測する
しかし、別のやり方で再現することができたためそれを記す

１．ゲームを開始する
２．西方海域のカレー沖を選択する
３．下ルートを通り、Hでの戦闘終了後に羅針盤が南西(I)をさしたことを確認する
４．移動中に右上の×ボタンを押してウィジットを終了する
５．ウィジットを再開する

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3100.0 Iron Safari/537.36

バージョン

> 2.0.63

**Comment by otiai10** [comment]
ありがとうございます。スクショいただいてもいいですか。あと、 @JoyandJoy さんにassignされてるissueへのコメント頂けますか？

**Comment by hana99999** [comment]
はじめまして、いつも使わせていただいております。

この問題ですが、うちの環境でもある条件下で確実に出ました。
それは「ウィジットの再開前に、大破進撃防止窓を消していない」と、必ず発生していました。
(画面設定では別窓表示に設定しております)

問題解決のヒントになれば幸いと思い、投稿させていただきました。

**Comment by otiai10** [comment]
@hana99999 ありがとうございます。説明付きスクショあれば頂きたいです。

なお、出てきた画面（意図に反して「ブラウザ上」（艦これウィジェットもChromeブラウザなんですけどね）の大きさと同じ大きさとして出てきた画面）は、APPモードになってますか？WHITEモードになってますか？

**Comment by otiai10** [comment]
また、 **ゲーム開始時** というのは、いったい何を起因とした **開始** ですか？

@hana99999 @JoyandJoy

**Comment by hana99999** [comment]
例えば、潜水艦5隻でオリョクルの場合(2戦以上続くマップ)
通常起動の場合は
![2017-08-03-005611](https://user-images.githubusercontent.com/30655022/28884033-5c3b7ae2-77eb-11e7-9cea-6311383b61c5.png)
なんですが、出撃して一戦戦った後、大破進撃防止窓が出ますよね
![default](https://user-images.githubusercontent.com/30655022/28884097-8c178468-77eb-11e7-8bd9-57ac6b04e395.png)
その後、ゲームの進撃or撤退の判定～次の戦いの陣形選択までに、猫るorユーザー側でウィジット終了して(羅針盤の向きや、ウッカリ大破進撃やらかしていたete)、ウィジットを再度起動した場合
大破進撃防止窓を消していないと、窓の大きさ等は変わらず
![2017-08-03-012130](https://user-images.githubusercontent.com/30655022/28884436-c4b8a684-77ec-11e7-91b9-8ef025d68881.png)
このような表示になってしまいます。

ちなみに窓関係の設定はこんな感じで
![default](https://user-images.githubusercontent.com/30655022/28884463-ea83b1ec-77ec-11e7-80d0-ac66c3e5d5e3.png)

**Comment by otiai10** [comment]
@hana99999 ありがとうございます。たいへん助かります。

1. DEFAULT WHITEで起動
2. クロックモードを出しておく
3. 何かしらの進撃をする
4. 別窓にて大破進撃防止窓を出す
5. 3を確認ののち、艦これウィジェットの窓を閉じる
6. クロックモードの左上から艦これウィジェットの窓を出そうとする
    a. **期待:** DEFAULT WHITEのサイズで窓が開き、コンテンツ座標変更もされる
    b. **現象:** DEFAULT WHITEのサイズで窓が開くが、コンテンツ座標変更がされない

という認識で合ってますか？

あと、

1. 窓自体の座標は、前回の位置を反映していますか？
2. クロックモードではなく右上アイコンから艦これウィジェットの窓を出そうとしたときも現象bは観測されますか？

**Comment by hana99999** [comment]
>という認識で合ってますか？
合っています。
補足で、ウィジェットの窓を閉じた後、大破進撃防止窓を閉じてから
艦これウィジェットの窓を出そうとすると、現象aになります。

＞窓自体の座標は、前回の位置を反映していますか？
前回起動時の位置が反映されています(前回起動後に位置を変えても起動時の位置です)
＞クロックモードではなく右上アイコンから艦これウィジェットの窓を出そうとしたときも現象bは観測されますか？
先ほど確認しましたが観測されました。

**Comment by otiai10** [comment]
@hana99999 ありがとうございます。時間ができ次第、調査します。

**Comment by otiai10** [comment]
<blockquote class="twitter-tweet" data-lang="en"><p lang="ja" dir="ltr">chrome-extension://プロトコルの同一拡張のページが開いているとき（e.g. 設定画面など）content_scriptからruntime.sendMessage(null, ...) すると、backgroundにもそのページにもメッセージ送信してるわ</p>&mdash; エロリツイート先生 (@otiai10) <a href="https://twitter.com/otiai10/status/894093624102629376">August 6, 2017</a></blockquote>

**Comment by otiai10** [comment]
@hana99999 さんの言う現象に関しては、原因が分かりました。 @JoyandJoy さんの「エラーがあったとき」というケースは、もしかして「大破進撃防止窓が残っているとき」の真部分集合ではないでしょうか？

**Comment by hana99999** [comment]
調査お疲れ様です。
>もしかして「大破進撃防止窓が残っているとき」の真部分集合ではないでしょうか？
私もそれではないかと思います。
