### ISSUE TITLE
ショートカットキーでスクリーンショットを撮りたい。

### ISSUE THREAD

**Issue by throne02** [otiai10/kanColleWidget#889]
以前有った、キーボードのショートカットキーでスクリーンショットが撮れる機能を復活して欲しいです。

# 解決される問題

キーボードでスクリーンショットが撮れないという問題

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

バージョン

> 2.0.56

**Comment by otiai10** [comment]
v1のときと同様に、chrome://extenstionsに行って最下部にありませんか

**Comment by otiai10** [comment]
確認できたらcloseしてください

**Comment by throne02** [comment]
確認できました、お手数おかけしてすみません…。
