### ISSUE TITLE
タイマーを”のこり時間表示”にすると、マウスオーバーしても時刻が表示されない

### ISSUE THREAD

**Issue by Hien2622** [otiai10/kanColleWidget#892]
# 画面

タイマー

# 観測される問題

”時刻表示”だとオーバーレイするとのこり時間が表示されるが”のこり時間表示”にすると時刻が表示されない

# 期待される挙動

”のこり時間表示”でもマウスオーバーで時刻表示して欲しい

# 再現方法

タイマー設定で”のこり時間表示”にする
登録したタイマーにマウスオーバー

-------

環境

> Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

バージョン

> 2.0.64

**Comment by otiai10** [comment]
@otiai10
https://github.com/otiai10/kanColleWidget/blob/develop/src/js/Components/Views/Dashboard/Contents/Clock/SchedulesRow.js#L43

**Comment by otiai10** [comment]
```diff
- this.rest ? "時刻" : "のこり" + " " + schedule.toClockString(!this.rest)
+ (this.rest ? "時刻" : "のこり") + " " + schedule.toClockString(!this.rest)
```

**Comment by otiai10** [comment]
![image](https://user-images.githubusercontent.com/931554/29102176-42664fd2-7cf2-11e7-8eab-85db85c933ee.png)
