### ISSUE TITLE
通知ポップアップが、ON/OFF関わらず表示されない

### ISSUE THREAD

**Issue by ReykaWang** [otiai10/kanColleWidget#894]
# 画面

ポップアップ

# 観測される問題

通知ポップアップを出す と設定したのに通知が出てこない

# 期待される挙動

設定通りの動作をしてもらいたい

# 再現方法

設定画面から通知に関する設定を全てONにする
例えば、遠征開始　等を行うと、出港のポップアップが出てこない

-------

環境

> Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2636.0 Safari/537.36

バージョン

> 2.0.56

**Comment by otiai10** [comment]
ここどうなってますか？

chrome://settings/content/notifications

**Comment by ReykaWang** [comment]
ご覧の通りです

**Comment by ReykaWang** [comment]
![notifications](https://user-images.githubusercontent.com/30864606/29175502-ce4e2090-7e1b-11e7-968d-e7689910acfb.jpg)

ご覧の通りです

**Comment by ReykaWang** [comment]
映像を撮ってきました
ご参考に
https://youtu.be/EobUZ9S6kDc

**Comment by otiai10** [comment]
@ReykaWang 動画、たいへん助かります。ありがとうございます。
音は鳴るし、遠征以外の通知は表示される、ってことっすね...

**Comment by otiai10** [comment]
放置して申し訳ないですが、v3.0プロジェクト発足にともない、いったんcloseします。
