### ISSUE TITLE
連合艦隊時の大破進撃防止窓で第二艦隊が表示されない

### ISSUE THREAD

**Issue by kazuya1116** [otiai10/kanColleWidget#897]
# 画面

連合艦隊時の大破進撃防止窓

# 観測される問題

戦闘終了後、2艦隊用のサイズで空の大破進撃防止窓がポップアップし、リザルト画面をクリックして次画面に遷移させる際、1クリック目にポップアップの左側に第一艦隊が表示されるが、2クリック目以降、第二艦隊が表示されず第一艦隊のみの表示で終了する。

# 期待される挙動

画面左上の表示設定の時は2艦隊とも表示されたので、v1と同じならポップアップ画面左に第一艦隊、右に第二艦隊が表示される。

# 再現方法

イベントの連合艦隊で出撃する海域で戦闘し、終了後普通にクリックしてゲームを進める。（ウィジェットの設定は大破進撃防止窓を別窓表示に）

-------

環境

> Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36

バージョン

> 2.0.64

**Comment by otiai10** [comment]
@kazuya1116 
ありがとうございます。いくつか確認があります。

1. クリックを検知してスクショを撮っているので、落ち着いて最小クリック回数で進めても、この問題は観測されますか？
2. 問題が起きたときのスクショをいただいてもいいですか？
3. 1が原因ではない場合、海域特有の問題が疑われるので、どの海域かなどの海域詳細情報をいただけますか？

**Comment by chyfis** [comment]
別窓のサイズを少し調整すると表示されるようになりました。参考になるかどうか分かりませんが…

**Comment by otiai10** [comment]
@chyfis ありがとうございます。今度同じ症状を見たときでいいので、スクショ撮っておいてください 🙇

**Comment by kazuya1116** [comment]
1.については、ゆっくりと画面右下の表示を見ながら最小回数でクリックしても発生します。
2.　1枚目は第一艦隊表示時、2枚目は第二艦隊表示時です。スクショ撮れていませんが、第一艦隊表示前にポップアップは立ち上がってます（背景のみ）
![default](https://user-images.githubusercontent.com/31003883/29296135-4a3078c8-8193-11e7-8111-404eb1692b0d.PNG)
![2](https://user-images.githubusercontent.com/31003883/29296558-02792860-8196-11e7-926b-b6516b6e6f9f.PNG)
3.現在開催のイベント海域E-3（連合艦隊）で起こっています。関係無いですが、通常海域（6－5）は自軍は通常艦隊ですが、深海棲艦側が連合艦隊なので大破進撃防止窓が連合艦隊用の2艦隊表示用になっています。（こちらは1艦隊だけ見えれば良いのでこのままでも問題ないです）

**Comment by otiai10** [comment]
@kazuya1116 

> 別窓のサイズを少し調整すると表示されるようになりました。参考になるかどうか分かりませんが…

これについてはどうですか？

**Comment by kazuya1116** [comment]
これから出撃するときに確認します。しばらくお待ち下さい。

**Comment by kazuya1116** [comment]
確認しました。
サイズ調整ですが、ポップアップウィンドウのデフォルトでの縦横比率の問題かなと思います。
1.戦闘終了後、第一艦隊の表示
![5](https://user-images.githubusercontent.com/31003883/29301209-889a32b2-81b5-11e7-9794-39da21227f0a.PNG)
2.第二艦隊の表示（前回と同様、表示無し）
![6](https://user-images.githubusercontent.com/31003883/29301224-a90daefc-81b5-11e7-8284-22f63ef1d1fb.PNG)
3.ウィンドウサイズを広げたり狭めたりすると第二艦隊も表示される
![7](https://user-images.githubusercontent.com/31003883/29301245-d1115020-81b5-11e7-8f94-03284bd7eade.PNG)
この後も色々試しましたが、縦方向は関係無く、横方向にデフォルトより少し広げると第二艦隊も表示されることが判りました。
ただ、表示されるようにサイズを変更しても、次の戦闘終了後はサイズは変わってもまた元の縦横比率に戻るので第二艦隊が”見えなく”なりました。（これも横に広げれば表示されます）

**Comment by kazuya1116** [comment]
雑ですが動画も撮ってみました。
![20170815_125746](https://user-images.githubusercontent.com/31003883/29301845-10e9172e-81ba-11e7-866d-634b79b4f7f3.gif)

**Comment by otiai10** [comment]
あーなるほど、原因はわかったので、たぶんすぐ直せると思います。詳細な情報と、スクショと動画まじで助かります！ありがとうございます！

**Comment by otiai10** [comment]
@otiai10
https://github.com/otiai10/kanColleWidget/blob/develop/src/js/Components/Routine/DamageSnapshot.js#L29-L30

ここに、 `display = flex` を追加
