### ISSUE TITLE
起動中、起動画面表示中に再起動し、右上のスクショボタンが消えてしまう

### ISSUE THREAD

**Issue by kazuya1116** [otiai10/kanColleWidget#898]
# 画面

起動画面表示時、遅い場合は母港画面など通常プレイ時に突然再起動が掛かる

# 観測される問題

ウィジェット起動時、早い場合は起動画面で再度起動ボイスと共に再起動する

# 期待される挙動

1度の起動で再起動が掛からず、ミュートボタンとスクショボタンが有効のままになる

# 再現方法

ウィジェットモードで起動（サイズは不問）する。
※おま環でしたらすみません

-------

環境

> Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36

バージョン

> 2.0.64

**Comment by kazuya1116** [comment]
ウィジェットモードでの起動
![20170815_090859](https://user-images.githubusercontent.com/31003883/29297419-ceffc6e6-819b-11e7-9ee5-9d69dc2ee570.gif)

**Comment by kazuya1116** [comment]
ホワイトモードでの起動も同じですが、すぐには再起動は掛かりません。動画を上げようとしたのですが、容量オーバーで無理でした。左下の表示が関係するのかもと怪しんでいます。自分でChromeの設定等見直しましたが改善しませんでした。

**Comment by kazuya1116** [comment]
「リクエストを処理しています・・・」の表示が左下にずっと出ていると、再起動されないようです。
ただ、予告無しにいきなり再起動するので困りものです。

**Comment by otiai10** [comment]
なんか別のChrome拡張の気配を感じます。そんなことないですか？

**Comment by kazuya1116** [comment]
艦これに関係の無いChrome拡張が悪さしている、と言うことでしょうか？

**Comment by otiai10** [comment]
艦これに関係有無にかかわらず、ページが読み込まれた時にリロードするような挙動に見えます。たとえば、v1がまだインストールされたままとか。

**Comment by kazuya1116** [comment]
v1はもう削除しています。ちなみにv1の時はこのような挙動はありませんでした。艦これ関係は、艦これタイマー連携ツールとChrome鎮守府の2つです。後はChrome リモート デスクトップと別ゲーム用にdemadoが入ってます。

**Comment by otiai10** [comment]
v3.0プロジェクト発足に伴い、いったんcloseさせてください
