### ISSUE TITLE
タブレットPCでのタッチモードで連合艦隊時の大破進撃防止窓に表示されない

### ISSUE THREAD

**Issue by Massy-mz** [otiai10/kanColleWidget#899]
# 画面

連合艦隊時の大破進撃防止窓

# 観測される問題

連合艦隊時のリザルト画面から、タブレットPC(Win8,10)でのタッチでは
大破進撃防止窓に表示されない為、タッチにも対応してほしい

・大破進撃防止窓：別窓表示
タッチ：2艦隊とも表示されず(空の2艦隊分の窓が表示)
マウス：第1艦隊のみ表示
(※)別窓のサイズを少し調整すると第2艦隊も表示される(#897と同じ挙動)

・大破進撃防止窓：左上表示
タッチ：2艦隊とも表示されず
マウス：2艦隊とも表示(正常)

#897で『クリックを検知してスクショを撮っている』とありましたので、
「タッチ」を検知していないように思われます。

# 期待される挙動

タッチモードでの連合艦隊時の大破進撃防止窓への表示

# 再現方法

現在だと、イベント海域E-3への連合艦隊での出撃・戦闘

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36

バージョン

> 2.0.64

**Comment by otiai10** [comment]
これバグですかね？機能要望かと思うんですが。

**Comment by Massy-mz** [comment]
すみません、タッチモードでも標準対応と思い違いしてました。
機能要望扱いでお願いします。

**Comment by otiai10** [comment]
@Massy-mz 使ってないタブレットPCとかお持ちではないでしょうか？僕持ってないので、検証しようがないというか...

**Comment by Massy-mz** [comment]
今のタブPC(Win10)の前に艦これ用として使っていたタブPC(Win8)あります。
もし検証とか必要であれば、可能な範囲でお手伝いします。

**Comment by otiai10** [comment]
@Massy-mz ありがとうございます。最近普通に仕事が忙しいので、一段落したら改めて取り組みたいと思っています。その時はご協力お願いするかと思います。

落合展
otiai10@gmail.com

**Comment by otiai10** [comment]
v3.0プロジェクト発足にともない、いったんcloseします
