### ISSUE TITLE
艦隊状況（大破進撃防止窓）で連合艦隊の第二艦隊が表示されない

### ISSUE THREAD

**Issue by mofy0129** [otiai10/kanColleWidget#900]
# 画面

艦隊状況の別窓

# 観測される問題

艦隊状況の別窓に連合艦隊時の第二艦隊が表示されない

# 期待される挙動

恐らく戦果報告２クリック目に第二艦隊が表示されると思うのですが、第二艦隊が表示される部分に変化なし

# 再現方法

このバージョンにあげてからずっと続いている問題のため、出ないことが標準です＞（２０１７春イベ以降にアップしたので、連合艦隊がこの夏イベが初で気づきました）

-------

環境

> Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36

バージョン

> 2.0.64

**Comment by mofy0129** [comment]
前の送信しているのがはんえいされていたため

**Comment by otiai10** [comment]
Related #897
