### ISSUE TITLE
ゲーム画面と異なる縦横比のウィンドウでスクリーンショットを撮ると画像がおかしくなる

### ISSUE THREAD

**Issue by hisamek** [otiai10/kanColleWidget#901]
ウィンドウを最大化するとゲーム画面の上下または左右に黒い部分ができ、スクリーンショットを撮るとその部分も画像に残る。ウィンドウサイズを縦長にして800x480にリサイズのオプションを使いスクリーンショットを撮ると現象の再現は顕著。せめて、中型リサイズのオプションを付けた場合くらいは、ウィンドウ内のゲーム画面のみをゲーム画面の縦横比と同様に切り出して黒色部分を除いてからリサイズして欲しい。

# 解決される問題

800x480のゲーム画面と異なる縦横比のウィンドウでスクリーンショットを撮ると画像がおかしくなるという問題

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36

バージョン

> 2.0.64

**Comment by otiai10** [comment]
Trimしていないのでしかたがないけれど、v3.0で対応する
