### ISSUE TITLE
連合艦隊時の大破進撃防止窓に第一・第二の両艦隊が表示されない（#897とは違い第一艦隊も表示されない）

### ISSUE THREAD

**Issue by usagiINB** [otiai10/kanColleWidget#902]
# 画面

大破進撃防止窓

# 観測される問題

戦闘終了後にポップアップされる大破進撃防止窓に落ち着いてゆっくりクリックしても第一・第二両方の艦隊が表示されない。#897のトピックにてkazuya1116氏が撮った動画のように窓の横幅サイズを変更しても変化無し。この症状を確認したのは今日（8月18日）の夕方過ぎだが、昼までは#897と同様の症状だった。

# 期待される挙動

v1と同様の仕様であれば、戦闘終了後にポップアップされる窓の左側に第一艦隊が表示され、クリック回数による検知で第二艦隊が窓の右空きスペースに追加表示されるものと推察。

# 再現方法

連合艦隊で出撃し、戦闘終了後の大破進撃防止窓が表示されるタイミングで必ず発生

-------

環境

> Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36

バージョン

> 2.0.64

**Comment by usagiINB** [comment]
たった今確認したところ、何故かこの症状は現れず再度#897の症状が出るようになりました。

経緯・状況等を改めて詳しくご報告致します。
連合艦隊となるE-3とE-4において全ての出撃で#897の症状を確認。
18日の朝からE-6輸送ゲージの攻略を開始。昼頃まで#897の症状を確認。
同日夕方過ぎに同海域攻略中に当トピック（#902）の症状を確認。
その際、キャッシュ削除とPC・ブラウザの再起動を試みていますが変化無し。
日を跨いで昨日（19日）E-6の輸送ゲージを破壊。#902の症状はそれまで全ての出撃で確認。
明けて今日（20日）の朝、同海域の戦力ゲージの攻略を開始したところ、#902の症状は見られず
また#897の症状に戻っているのを確認。今に至る

最初は輸送ゲージでこうなるのかと思いましたがE-3ではずっと#897の症状でしたし、
E-6の輸送ゲージも初めは#897の症状でしたので関係無いもよう？
Windowsアップデートが途中ありましたがE-5攻略中でしたし、そのほか環境の変化等の心当たり無し。

**Comment by otiai10** [comment]
closeしてもいいですか？

**Comment by usagiINB** [comment]
はい。
あれから#902の症状は発生しておりません。
原因は解らずじまいですが俗に言うおま環だったのかもしれません。

お騒がせして申し訳ありませんでした。
