### ISSUE TITLE
建造タイマーのプッシュ通知について

### ISSUE THREAD

**Issue by vandojapan** [otiai10/kanColleWidget#910]
# 画面

ゲーム画面：工廠　

# 観測される問題

建造時間の取得漏れの可能性。「**建造開始**」ボタン押下時に建造時間が「**NaN時間undedined分**」、予定時刻が「**Invalid Date**」になり、建造してすぐに建造完了のプッシュ通知される

問題のスクリーンショット
![image](https://user-images.githubusercontent.com/30983282/31248665-8db7be5a-aa4f-11e7-820e-c0715868b4a5.png)

# 期待される挙動

建造完了予定時刻を「**建造開始**」押下時に正常に表示、建造完了予定時刻にプッシュ通知

# 再現方法

建造タイマーをONにした状態で
 工廠の建造で「**建造開始**」ボタンを押下する

再現時
![bug](https://user-images.githubusercontent.com/30983282/31249117-1b8d9e74-aa51-11e7-8b15-52b3dae5868a.gif)
-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

バージョン

> 2.1.0

**Comment by otiai10** [comment]
@vandojapan これって、「今まで期待通りにうごいていたが、最近このような現象を起こすようになった」というやつですか？

**Comment by vandojapan** [comment]
そうですね。前までは正常に動いてたのですが、最近になってこのような挙動に変わりましたね

**Comment by otiai10** [comment]
@vandojapan これまだ起きますか？

**Comment by vandojapan** [comment]
今も起きますね
動画も撮ってきたので目を通していただくと幸いです
https://youtu.be/B4F0S5fdbnY

**Comment by vandojapan** [comment]
バージョンは
2.1.1 
Chromeバージョンは61.0.3163.100

**Comment by otiai10** [comment]
v3.0で直します 🙇
