### ISSUE TITLE
資源推移表の自動取得が出来ず手動で取得するとエラーが発生

### ISSUE THREAD

**Issue by nyoki5548** [otiai10/kanColleWidget#911]
# 画面

資源推移表

# 観測される問題

10/2までは自動取得出来ていましたが
現在は資源推移表の自動取得が出来ず手動で取得を押すと
[v2開発版] beta.艦これウィジェット
 {"status":404,"message":"Not Found"}
とうエラーが表示され取得出来ない

# 期待される挙動

資源推移表の自動取得

# 再現方法

-------

環境

> Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

バージョン

> 2.0.56

**Comment by otiai10** [comment]
開発版はだいぶ前に死にました。
こちらを使ってください。
https://chrome.google.com/webstore/detail/%E8%89%A6%E3%81%93%E3%82%8C%E3%82%A6%E3%82%A3%E3%82%B8%E3%82%A7%E3%83%83%E3%83%88/iachoklpnnjfgmldgelflgifhdaebnol?hl=ja

なお、記録はこのへんです。
https://github.com/otiai10/kanColleWidget/releases/tag/2.0.57
