### ISSUE TITLE
ゲーム画面に遷移しない

### ISSUE THREAD

**Issue by Gedachtnis** [otiai10/kanColleWidget#916]
# 画面

（小型以外）のゲーム窓すべて

# 観測される問題

艦これスニッファーのアイコンをクリックしても窓の大きさが変わるだけでゲーム画面に遷移しない

# 期待される挙動

普段通りの快適なプレイ（いつもお世話になっています）

# 再現方法

Chrome: 62.0.3202.89（Official Build） （32 ビット）

-------

環境

> Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36

バージョン

> 2.1.1

**Comment by otiai10** [comment]
『艦これスニッファー』のリポジトリはここではありません。
https://osdn.net/projects/kancollesniffer/scm/git/KancolleSniffer/
