### ISSUE TITLE
ゲーム画面に遷移しない

### ISSUE THREAD

**Issue by Gedachtnis** [otiai10/kanColleWidget#917]
# 画面

（小型以外）のゲーム窓すべて

# 観測される問題

艦これウィジェットのアイコンをクリックしても窓の大きさが変わるだけでゲーム画面に遷移しない

# 期待される挙動

普段通りの快適なプレイ（いつもお世話になっています）

# 再現方法

通常通り　アイコンをクリック→ドアマーク(?)をクリック　
100％の確率で再現されます
デスクトップPCでの挙動です．winタブの方では正常に起動するので所謂「おま環」だと思われますが
何をどうしたものかという状態なのでお助け頂けないかと．

# 環境

Chrome: 62.0.3202.89（Official Build） （32 ビット）

バージョン

2.1.1

- OS: Windows10
- Chrome: 62.0.3202.89
- 艦これウィジェット: 2.1.1

# ひとこと

先ほどは誤投稿大変失礼いたしました

このリンクをみました 👉 http://amzn.asia/aWYh5Z0

**Comment by otiai10** [comment]
白い画面で `要素の検証` → `Console` → に表示されてる赤い文字のスクリーンショットをください。

あと、小型は期待通りの挙動をしているんですか？

**Comment by no1fushi** [comment]
似たような挙動が確認されたので報告します.  
# 画面  
DEFAULT WHITE以外のすべて  
  
# 観測される問題  
大型、小型で起動すると真っ白な画面になる、またはDMMゲームのページが開かれる.  
  
# 期待される挙動  
直接艦これが開き、普段通りのプレイができる.  
  
# 再現方法  
窓の設定を大型または小型にしドアマークをクリックする.  
広告ブロック拡張を入れていますがDMM,艦これのページでは無効にしています.  
また、艦これウィジット以外の拡張を入れていないChromeでも試してみましたが同じです.  
  
# 環境  
OS:Windows7  
ブラウザ:Google Chrome 62.0.3202.94 (Official Build) (64bit)  
艦これウィジット:2.1.1  
  
# 要素の検証  
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://www.dmm.com') does not match the recipient window's origin ('http://osapi.dmm.com').
postMessage @ ifr:219

**Comment by otiai10** [comment]
@no1fushi ご報告ありがとうございます。
とりあえず再現を試みましたが、当方の環境では再現されません。

![image](https://user-images.githubusercontent.com/931554/32999230-0d498baa-cde4-11e7-8c69-78726e328bc3.png)

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

- @Gedachtnis さんの「窓の大きさが変わるだけでゲーム画面に遷移しない」という記述
- @no1fushi さんの「またはDMMゲームのページが開かれる」という記述

について、具体的にどういう状態なのかイメージできないので、スクリーンショットを頂けますか。動画だとベターです。

なお『艦これウィジェット』のアップデートはリリースしていないことや、当方の環境で再現されないことなどから、Chrome起因、あるいはお使いの環境のなんらかの起因が考えられます。 **もしいつの間にか直った場合は** 、必ずそのときの環境をコメントしていただけると幸いです。

**Comment by no1fushi** [comment]
動画を撮りました。
https://youtu.be/qoFKbck92eo

**Comment by otiai10** [comment]
メモ
https://github.com/otiai10/kanColleWidget/blob/develop/src/js/Application/Routine/ExtractFlash.js

**Comment by otiai10** [comment]
@no1fushi ありがとうございます。
通常のタブでゲーム画面が表示されたあとに、コンソールで

```
document.querySelector("iframe#game_frame").src
```

と打つとどうなりますか？

**Comment by no1fushi** [comment]
document.querySelector("iframe#game_frame").src

"http://osapi.dmm.com/gadgets/ifr?synd=dmm&container=dmm&owner=29341956&viewer=29341956&aid=854854&mid=89067277&country=jp&lang=ja&view=canvas&parent=http%3A%2F%2Fwww.dmm.com%2Fnetgame%2Fsocial%2F&url=http%3A%2F%2F203.104.209.7%2Fgadget.xml&st=QQhQ5EhN%2FRH13mMTqjJMYn2YwWZoxompIQSw9WQCFMEATLnwii05JuuZY%2FBlxmJUZv%2FvbHAguW4uCHECJth4BWBZQtarJzj5E0khh6CBPM6qz21MUggavPXyNZqj5r0OPNNVH%2BYU%2BYCl9O23vKgyhDdznbkEWB6Q4V4K70DSQIgNuBRcYi8mJBh0ON3Xsvt0boutPx4dccX6IFFuS%2BBPt%2Bpi34A%3D#rpctoken=1080995045"

**Comment by Gedachtnis** [comment]
返信が遅くなりすみません

どういう理屈なのか何が原因だったのかわかりませんが元に戻りました
どうもありがとうございました
お騒がせして申し訳ありません

ちなみに小型窓は最初は正常に動いていましたがその後他と同じ挙動に・・・
何か環境を変えた(システムに絡むものを導入したとか）訳ではなかったはずなので益々意味がわからんという状態でした

**Comment by no1fushi** [comment]
自分も戻りました。
OS:windows7
Chrome:62.0.3202.94(Official Build)(64bit)
艦これウィジット:2.1.2

他拡張の停止,削除,追加は行っていません
セキュリティソフトの変更,停止,追加もしていません

@otiai10 さん
対応ありがとうございました!
環境をどこまで書けばいいかよくわからないので足りない情報があれば教えてください。
