### ISSUE TITLE
スクショ設定で決めたDLフォルダとファイル名にならない

### ISSUE THREAD

**Issue by kazuya1116** [otiai10/kanColleWidget#918]
# 問題の概要

設定画面で設定したダウンロードフォルダとファイル名が、設定と違う保存先が開き、ファイル名も「ダウンロード.png」と固定されてしまっている。

# 問題の再現方法

1. スクショボタンを押す
2. 立ち上がった編集画面左の「保存」ボタンを押す
3. 「Save file name」のポップアップが出て設定した保存先のフォルダとファイル名が表示される
　ので「SAVE」を押す
4. 「ファイル名を付けて保存」ウィンドウが立ち上がるが、設定した保存先のフォルダでは無くまた、
　ファイル名も常に「ダウンロード.png」となっている

上記の方法により、100％の確率で、再現する。

# 問題が起きているバージョン

- 問題が観測されるバージョン: 2.1.1
- 問題が観測されなかったバージョン: 不明（但し、スクショの記録では11/5まで正常に設定通り記録できています）

# 環境

- OS: Windows　7HOME（本日Windows10にアップデートしましたが変わらず）
- Chrome: 62.0.3202.89
- 艦これウィジェット: 2.1.1

# ひとこと

このリンクをみました 👉 http://amzn.asia/aWYh5Z0

**Comment by kazuya1116** [comment]
操作時の画像です
![20171111_174700](https://user-images.githubusercontent.com/31003883/32687958-eb0e6036-c70a-11e7-8520-d5b92bcc2e05.gif)

**Comment by otiai10** [comment]
GIFありがとうございます。助かります。

---

とりあえず、2点

1. 『艦これウィジェット』の最後の更新は[2017/10/20のようです](https://github.com/otiai10/kanColleWidget/releases)、おそらく（あきらかに）Chromeのアップデートに起因するものだと思われます
    - それが彼らのバグなのか、僕が対応しなきゃいけないAPIの変更なのかは、今んとこ判断しかねます
2. 僕の以下の環境では、この問題は再現できないようです

> OS: macOS Sierra 10.12.6 (16G29)
> Chrome: 62.0.3202.89 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/931554/32688073-4fcaa3ca-c70d-11e7-9e52-96e92107611d.png)

---

TODO: Chromiumのforumを見て、Windows下でchrome.downloadsの挙動が変わった旨のドキュメントないしバグレポートが無いか漁る。

---

やってほしいこと @kazuya1116 

1. （可能なら）艦これウィジェットの削除&再インストール
2. （可能なら）Chromeのアンインストール&再インストール（その間、Chromeのバージョンの変化に注意）

**Comment by otiai10** [comment]
https://github.com/otiai10/kanColleWidget/blob/2b4c0fe153b2f1dfc53decf53b3cfcd849d6a25c/src/js/Application/Views/Capture/index.js#L212-L216

**Comment by otiai10** [comment]
この `filename` がemptyだったらこの問題が起きそうな気がする

**Comment by kazuya1116** [comment]
ご対応ありがとうございます。
早速実行してみました。

1.（可能なら）艦これウィジェットの削除&再インストール
　→削除し、再度インストールの上、同じ設定にしましたがフォルダ＆ファイル名は設定と違う　　　（削除前と同じ）

2.（可能なら）Chromeのアンインストール&再インストール（その間、Chromeのバージョンの変化に注意）
　→1.項を実行後、アンインストールの上再インストールし確認しましたが同じく設定と違う
　（削除前と同じ）バージョンは62.0.3202.89（Official Build） （64 ビット）でした

今までと同じ設定で使っていて出た症状なので、ま　た　Chrome　か　と昼間ツイートしましたが、その影響（とばっちり）をウィジェットが受けてしまったのでしょうか？

**Comment by otiai10** [comment]
艦これウィジェット側の更新が無いこと、MacOSで再現しないことを考えると、Chromeの更新起因と考えるのが妥当かと現時点では考えています。

**Comment by otiai10** [comment]
だいたいChromeのせいです。

**Comment by otiai10** [comment]
@otiai10

- https://chromereleases.googleblog.com/2017/11/
- https://chromereleases.googleblog.com/
- https://chromium.googlesource.com/chromium/src/+log/62.0.3202.82..62.0.3202.89?n=10000
- https://chromium.googlesource.com/chromium/src/+log/62.0.3202.89..62.0.3202.94?pretty=fuller&n=10000
