### ISSUE TITLE
正常に動画キャプチャ出来ない

### ISSUE THREAD

**Issue by u-ki-o** [otiai10/kanColleWidget#919]
# 画面

動画キャプチャ

# 観測される問題

動画キャプチャを開いた際ゲームウィンドウが取得できないみたいで代わりに直前に開いていたタブが録画対象になる。録画対象になったタブには青い四角のアイコンが表示され、マウスをポイントすると「このタブのコンテンツは共有されています」というメッセージが出る。

# 期待される挙動

ゲームウィンドウが録画される

# 再現方法

Chromeを起動→艦これウィジェットボタンからDefaultWhiteレイアウトで艦これゲームウィンドウを開く。→艦これウィジェットボタンを右クリックし、動画キャプチャをクリックする。→直前に開いていたタブを録画対象にして動画キャプチャ機能のタブが開く。

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

バージョン

> 2.1.1

**Comment by otiai10** [comment]
@u-ki-o ご報告ありがとうございます。

とりあえず軽くやってみたところ、僕の環境では観測されません。今後時間ができ次第調査したいので、また何か聞くかもしれません。

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

あと、上記によりつまり艦これウィジェット起因ではあり得ないので、したがって、今後「なんか知らんけど直った」的なことがあると思いますので、 **最後に問題が観測されたときの環境** と **直ったときの環境** の、できれば **差分** を必ず記録しておいてください。

**Comment by u-ki-o** [comment]
返信ありがとうございます。
この報告を行った後Macでも試してみたところ同様の現象が発生しました。

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

他のアドオンも入れてないのでChromeの環境設定か何かが影響してるような気がしますが今の時点だとこれ以上はわからないですね。
また何かわかったらこちらで報告いたします。

**Comment by otiai10** [comment]
v3.0で直します
