### ISSUE TITLE
スクショのホットキー設定について

### ISSUE THREAD

**Issue by yuuyuu0** [otiai10/kanColleWidget#920]
# 問題の概要

スクショのホットキー設定が見当たりません。
以前は設定画面で設定してキーボードからスクショを実行できたはずですが、思い違いでしょうか・・・？

# 問題の再現方法

1. 設定画面を開く
2. スクショ設定を見る
3. ホットキー設定が無い

# 問題が起きているバージョン

- 問題が観測されるバージョン: 2.1.1

# 環境

- OS: Windows 10
- Chrome: 62.0.3202.94
- 艦これウィジェット: 2.1.1

**Comment by otiai10** [comment]
@yuuyuu0 スクリーンショットいただけますか

**Comment by otiai10** [comment]
> ホットキー設定が無い

というところ

**Comment by yuuyuu0** [comment]
https://gyazo.com/84661e13a9e00fa09354109690dd56cc
こんな感じになっております

**Comment by otiai10** [comment]
ホットキー（キーボードショートカット）の登録は、Chrome拡張全体の設定画面 `chrome://extensions` のほうで行います

![image](https://user-images.githubusercontent.com/931554/33351722-7e6b821a-d4e8-11e7-8480-52000a2b927e.png)

**Comment by otiai10** [comment]
レスポンスが無いのでcloseします
