### ISSUE TITLE
ログイン時の獲得物について

### ISSUE THREAD

**Issue by doreddono-to** [otiai10/kanColleWidget#922]
# 問題の概要
これを書く前に使っていた旧型の艦これヴィジェットで母港ログイン時にもらえるもの（プレゼント箱等）がある時の画像（○○を獲得しました的なやつ）が以前表示されなかった事があったのですがこれは新型の方でも起こる現象なのでしょうか？
今回の秋イベ終了後のメンテ後母港ログイン（旧型使用）でも海峡章獲得が表示されませんでした（ただその時ログインに手間取ってしまったので同じ状態ではないかと思いますが）。

# 問題の再現方法

1. 旧型でログイン時もらえるものがある

# 問題が起きているバージョン

- 問題が観測されるバージョン: 旧型

# 環境

- OS: Windows10
- Chrome:最新
- 艦これウィジェット: 旧型

# ひとこと

**Comment by doreddono-to** [comment]
環境に追加で
航海日誌改17.12.1というのをを使っています

**Comment by otiai10** [comment]
@doreddono-to 旧型はもうサポート外なのでわからないです。新型において、なんか見た感じ、DMMアカウントに紐づく処理っぽい雰囲気があるので、不安なら `DEFAULT WHITE` を使っていただければ、そこで起きる/起きない現象は完全に `艦これウィジェット` 起因ではないので、問題の切り分けができるかとおもいます。

**Comment by otiai10** [comment]
旧型はサポート外ですし、レスポンスが無いのでcloseします。
