### ISSUE TITLE
[mastodon] スクショをMastodonでも投稿できるようにしてほしい

### ISSUE THREAD

**Issue by mimikun** [otiai10/kanColleWidget#924]
現在のスクショ投稿はTwitterしかない状況なので、これをMastodonでも投稿できるような機能が欲しいです

# 解決される問題

Mastodonにもスクショを投稿できるようになるという問題

-------

環境

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

バージョン

> 2.1.3

**Comment by otiai10** [comment]
@mimikun いろんなインスタンスがあると思うんですが、たとえばどこですか

**Comment by otiai10** [comment]
- https://gist.github.com/okapies/eab5c6fc217e914ed0cac6c944384e4d
- https://qiita.com/shindyu/items/6a1f0c567774516f07da
- https://www.npmjs.com/package/mastodon-api

**Comment by mimikun** [comment]
mstdn.jpとpawoo.netとfriends.nicoですが、できれば全てのMastodonインスタンスで投稿できるようにしてほしいです・・
(お一人様でやってるところもあると思うので)

**Comment by otiai10** [comment]
@mimikun 一回の投稿アクションで複数のmastodonインスタンスに投稿したいですか？

**Comment by mimikun** [comment]
自分としては一回の投稿アクションにつき一つのインスタンスでいいと思います
他のインスタンスにはブーストで飛ばせると思うので大丈夫かなと

**Comment by otiai10** [comment]
@mimikun であれば、設定で追加できるmastodonインスタンスは、1つで十分だ、ということになりますかｎ

**Comment by mimikun** [comment]
@otiai10 
+ 設定で幾つかMastodonインスタンスを追加できる
+ 投稿するインスタンスを投稿時 or 設定画面で選ぶ
という感じが良いかな、と思っているのですがどうでしょうか？

**Comment by otiai10** [comment]
v3.0プロジェクトでやっていこうかと思うんですが、いいですか？

**Comment by mimikun** [comment]
v3.0で実装ですか？
ならそれでいいです。

**Comment by otiai10** [comment]
いったんcloseします
