### ISSUE TITLE
[mastodon] 内部実装の要件定義

### ISSUE THREAD

**Issue by otiai10** [otiai10/kanColleWidget#926]
#924

**Comment by otiai10** [comment]
- Mastodonインスタンス設定のCRUD
  - `Mastodon`モデルの作成（backend）
  - 設定ファイルからCreate, List, Deleteする（UI）
- Mastodonインスタンス選択UI
  - 現状では、Twitter連携有効だったらTweetボタンが現れるが、これに、Mastodonモデルが保存されているかどうかを条件追加する
  - Mastodonインスタンスを選択するチェックボックスがある
      - Twitter、およびMastodonのすべてのチェックボックスが外れていれば、投稿ボタンはinactiveになる。
- Mastodonへの投稿ミドルウェア（backend）
  - Services以下に書く
  - `Mastodon`モデルを受ける

**Comment by otiai10** [comment]
↑
こんな感じになると思うんですが、まず、このなかの1つか2つを、Skypeかなんかで（ほんとはAtom Teletypeでやりたい！）ペアプロしたのち、残りからやりたい項目を選んでくれればなと思います。基本僕がやれるので、あまり責任負わなくていいです。
@mimikun

**Comment by mimikun** [comment]
@otiai10 分かりました。Atomなら自分も使っているのでTeletypeで出来そうです。
