### ISSUE TITLE
設定した内容がリセット(初期化)されてしまう

### ISSUE THREAD

**Issue by sadatora** [otiai10/kanColleWidget#928]
# 画面

ウィジェットの設定

# 観測される問題

PCを起動する度に設定した内容が初期化されている

# 期待される挙動

11月の頃は問題なかったので、なおしてほしい

# 再現方法

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36

バージョン

> 2.1.3

**Comment by otiai10** [comment]
すみません、再現方法を書いてください。

**Comment by sadatora** [comment]
PCの再起動？もしくはchromeの再起動？にて再現されています

**Comment by otiai10** [comment]
何点か確認させてください。

1. その方法で、私の環境では再現しないようなのですが、「艦これウィジェット」のバグであると判断した理由は何でしょうか。また、最後に期待通りに挙動したのはいつでしょうか。（エンバグの要因を特定するのに必要です）
2. Chromeのセキュリティ、プライバシー設定で、 `localStorage` を含めた、たぶん「閲覧履歴の保存」みたいに書かれてる部分の項目を確認してください。
3. それでなければ、ChromeないしChromiumのバグなので、 https://www.chromium.org/issue-tracking こちらにissueを投げてください。

**Comment by sadatora** [comment]
１：今まさになりました(PC起動からchrome起動で
２：閲覧履歴の保存は「同期済み」です localStorage が自分では調べきれませんでした
　　どこを調べれば良いのかわからないです…申し訳ない

**Comment by otiai10** [comment]
期待通りの挙動というのは、正常動作という意味です

**Comment by sadatora** [comment]
失礼しました
11月の時は正常でした

**Comment by sadatora** [comment]
いろいろ試しましたが、OSからのクリーンインストールで片付けました
失礼しました
