### ISSUE TITLE
敵艦隊状況確認窓

### ISSUE THREAD

**Issue by Soleilkz** [otiai10/kanColleWidget#929]
戦闘終了or夜戦開始の選択時に、大破進撃防止窓と同じような形で昼戦終了時の敵艦隊の状況を表示していただきたいです。

# 解決される問題

特定の艦種を一定数撃滅する任務において、他の作業と並行して行っている場合に打ち漏らしが出てしまう問題

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

バージョン

> 2.1.3

**Comment by otiai10** [comment]
- [夜戦突入時にも艦娘状態（& 敵艦状態）を表示する](https://github.com/otiai10/kanColleWidget/issues/316)
- [夜戦突入選択画面で、【自艦隊】と【敵艦隊】の損傷度合を見たいのですがどうでしょうか？](https://github.com/otiai10/kanColleWidget/issues/680)
- [夜戦突入選択画面で、【自艦隊】と【敵艦隊】の損傷度合を見たい](https://github.com/otiai10/kanColleWidget/issues/720)

この辺見て頂けると雰囲気分かると思うんですが、たしかにあまりにも長いこと、そして繰り返し同じ内容の要望が来るので、そろそろなんかしたいと思います。

**Comment by otiai10** [comment]
1. 戦闘終了時に敵艦隊表示 ←これはできる
2. 夜戦突入選択時に（自艦隊+）敵艦隊表示 ←これはきびしいが、どうにかすっかという気持ち
