### ISSUE TITLE
ゲームウィンドウを常に手前に表示する

### ISSUE THREAD

**Issue by root-1-2** [otiai10/kanColleWidget#930]
ゲーム画面右上の消音ボタンとスクショボタンに並べて最前表示をするボタンが欲しい

# 解決される問題

ゲーム画面を重ねて表示できないという問題

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

バージョン

> 2.1.3

**Comment by otiai10** [comment]
ご参考までに
- https://github.com/otiai10/kanColleWidget/issues/118
- https://github.com/otiai10/kanColleWidget/issues?utf8=%E2%9C%93&q=is%3Aissue+%E5%B8%B8%E3%81%AB%E5%89%8D%E9%9D%A2

**Comment by otiai10** [comment]
<blockquote class="twitter-tweet" data-conversation="none" data-lang="en"><p lang="ja" dir="ltr">補助ツールとして「最前面でポーズ」もご紹介。<br><br>機能は……名前通りです。demadoのウィンドウを常に最前面表示するように設定できます。最大化した背後のウィンドウに触れても隠れる事がないので、気になる動画をチェックしながら周回なんてこともできますよ～<br><br>Vector(<a href="https://t.co/jQNyZGrSMF">https://t.co/jQNyZGrSMF</a> …) <a href="https://t.co/CCVRKe5itV">pic.twitter.com/CCVRKe5itV</a></p>&mdash; 八葉 りん (@yatsuba_rinn) <a href="https://twitter.com/yatsuba_rinn/status/989145502775033856?ref_src=twsrc%5Etfw">April 25, 2018</a></blockquote>
