### ISSUE TITLE
改修工廠早見表の第二番艦カラム幅調整

### ISSUE THREAD

**Issue by tashF75** [otiai10/kanColleWidget#931]
改修工廠早見表の第二番艦カラム幅を少し大きくして欲しいです．
現状では微妙に小さく，Saratoga改とSaratogaMK.IIがどちらもSaratog...になってしまっており，区別がつかないです．

# 解決される問題

Saratog...が誰だかわからない問題

-------

環境

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

バージョン

> 2.1.3

**Comment by wifeofvillon** [comment]
@otiai10 

width: 68px
![2018-01-30 22 39 04](https://user-images.githubusercontent.com/24819529/35569307-3b975b8c-060f-11e8-95ad-e5b1ee7182f3.png)

width: 92px
![2018-01-30 22 43 44](https://user-images.githubusercontent.com/24819529/35569296-331ac840-060f-11e8-8cd9-1f86a2122eb8.png)

Material-UIのデフォルトのフォントサイズ(13px)だと`SaratogaMK.II`のwidthは86pxになるようです
