### ISSUE TITLE
改修工廠カタログ更新

### ISSUE THREAD

**Issue by wifeofvillon** [otiai10/kanColleWidget#932]
一部艦娘の改修可能装備が変更になっているのでデータを更新してほしい
ex.あきつ丸改(火): 一式戦隼II型/III型甲/特大発動艇

# 解決される問題

一部艦娘の改修可能装備がゲーム上データと合致しない問題

-------

環境

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

バージョン

> 2.1.3

**Comment by otiai10** [comment]
ありがとうございます。カタログは

```
npm run fetch-wiki
```

で更新できます。

**Comment by wifeofvillon** [comment]
改修工廠カタログを更新しました。

一応、遠征カタログのIDマッチ条件をWikiに合わせて`/^[AB]*[0-9]+/`に変えて動かしてみましたが、アルファベットつきの恒常遠征がイベント遠征の後に来るのが気持ち悪かったので、こっちはcommitしていません。
