### ISSUE TITLE
遠征帰投等の通知をタスクバーのアイコンで通知する

### ISSUE THREAD

**Issue by root-1-2** [otiai10/kanColleWidget#936]
右に出るトースト通知が大きくて邪魔になるのでウィンドウをアクティブにするまでタスクタスクバーのアイコンをオレンジ色に光らせるかアイコンを差し替えて通知するようなシンプルなものが欲しいです。
この通知の仕方だとトースト通知を消した後でも通知が残るので忘れずに帰還報告を見ることもできると考えました。

# 解決される問題

トースト通知でモニターが狭くなる問題

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

バージョン

> 2.1.4

**Comment by otiai10** [comment]
僕Mac使いなのでわからんのですが、タスクバーのアイコンって何が出てるんですかね。何をどう変えたら「タスクバーのアイコン」なるものが変わるのかも、今んとこ分からないです。まあたぶんfavicon部分なのかなと思いますが。「タスクバー」のスクリーンショットをいろいろとください。

**Comment by otiai10** [comment]
@root-1-2 コメントいただけないとcloseします

**Comment by otiai10** [comment]
コメントいただけないのでcloseします
