### ISSUE TITLE
敵泊地強襲反撃作戦に対応していないので直して欲しい

### ISSUE THREAD

**Issue by maroncoro** [otiai10/kanColleWidget#939]
他の遠征では帰投予定時刻が通知で出てくるのにもかかわらず
遠征の敵泊地強襲反撃作戦に出すと「遠征ID111?　知らない子ですね」と出てきて
タイムラインにも反映しません。
もちろん帰ってきたときにも通知が出てこず気が付いたらもう帰ってきていたというのも度々あります。
同時期に実装された南西方面航空偵察作戦には対応しているのにどうしてでしょうか。
改善をお願いします。

# 解決される問題

遠征の敵泊地強襲反撃作戦に出すと「遠征ID111?　知らない子ですね」と出てくる問題
敵泊地強襲反撃作戦がタイムラインに反映しない問題
敵泊地強襲反撃作戦の帰投時に通知が出てこない問題

-------

環境

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

バージョン

> 2.1.5

**Comment by otiai10** [comment]
なるほど、遠征ID `111` ではなく `B2` と記述されているから、 `fetch-wiki-missions` で取ってこれないんだ

- https://wikiwiki.jp/kancolle/%E9%81%A0%E5%BE%81
- https://github.com/otiai10/kanColleWidget/blob/develop/scripts/fetch-wiki-missions.coffee#L26

やっぱり共同編集可能などこかに記述してクライアント側からupdateできるようにするのがよさそう

**Comment by otiai10** [comment]
v3.0で対応
