### ISSUE TITLE
Twitter連携がリダイレクトで止まって連携できない

### ISSUE THREAD

**Issue by Elza1878** [otiai10/kanColleWidget#940]
# 画面

chrome-extension://iachoklpnnjfgmldgelflgifhdaebnol/dest/oauth/chrome_ex_oauth.html

# 観測される問題

Twitter連携をONすると、連携がリダイレクトページで止まってそこから先へ進まない

# 期待される挙動

連携が可能になる

# 再現方法

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36

バージョン

> 2.1.5

**Comment by wifeofvillon** [comment]
@otiai10 @Elza1878 6月後半にTwitterAPIの仕様変更があったようです。

[Twitter OAuthが403 Forbiddenを返すようになったので対応した - Akata Works](http://akataworks.hatenadiary.jp/entry/2018/06/14/121056)
