### ISSUE TITLE
課金できない

### ISSUE THREAD

**Issue by mizrenkov** [otiai10/kanColleWidget#941]
# 画面

アイテム屋さん

# 観測される問題

購入ボタン押下後、ポイントで購入！を押下しても画面遷移しない

# 期待される挙動

DMMの決済画面に遷移

# 再現方法

大型　で窓を開いて購入すると必ずこうなる

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

バージョン

> 2.1.5

**Comment by otiai10** [comment]
課金は `DEFAULT WHITE` でやってください

**Comment by otiai10** [comment]
v1のころは、APPモードでは課金できません、という文言を明示してたんですが、v2になってなくなっちゃってたみたいですね。すみません。どっかに追加しておきます。ありがとうございます。

**Comment by mizrenkov** [comment]
解決しました。
素早い対応ありがとうございます。

**Comment by otiai10** [comment]
こちらこそありがとうございます。ちいさくてもフィードバックいただけると開発者として嬉しいです。
