### ISSUE TITLE
ゲーム画面がウインドウサイズ内に収まらない

### ISSUE THREAD

**Issue by Guren3S** [otiai10/kanColleWidget#943]
# 問題の概要

WHITEモード：ゲーム画面がウインドウ内に収まらない
　　　　　　　(1期と2期でゲーム画面のサイズ/座標が異なることが原因？)
APPモード：ゲーム画面の上部に白い枠が表示される
　　　　　　ゲーム画面がウインドウサイズと同じサイズに縮小されない

Chromeのリセット/再インストールを試すも症状に変化なし

# 期待される挙動

1期同様にゲーム画面が表示できる

# 再現方法

初期設定のDEFAULT WHITE/小型でゲームを起動する

# 環境

- OS: Windows10　64bit
- Chrome: 68.0.3440.106
- 艦これウィジェット: 2.1.5

**Comment by otiai10** [comment]
Related #942
