### ISSUE TITLE
大破進撃防止窓周りの異常

### ISSUE THREAD

**Issue by hana99999** [otiai10/kanColleWidget#948]
# 画面

大破進撃防止窓

# 観測される問題

別窓表示の時、大破進撃防止窓の座標がズレて切り出される。
![zoom1 0](https://user-images.githubusercontent.com/30655022/44308336-9ad51580-a3ee-11e8-97f0-59407cccc78a.png)
左上表示で大破進撃防止窓が表示されない。

# 期待される挙動

艦隊の状況がきちんと表示される。

# 再現方法

大破進撃防止窓を出す設定でゲームをプレイする。

-------

環境

> Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

バージョン

> 2.1.6

**Comment by otiai10** [comment]
@yz777 

- 大破進撃防止窓の座標
- 編成キャプチャの座標
- 建造・修復の画像解析の座標

このあたり確認していただくことは可能ですか？

**Comment by otiai10** [comment]
@yz777 原因発見したので、こちらで巻き取ります。

**Comment by otiai10** [comment]
- [x] 編成キャプチャ
- [ ] 大破進撃防止窓
- [ ] 建造・修復の画像解析

**Comment by otiai10** [comment]
![image](https://user-images.githubusercontent.com/931554/44408456-5e92e800-a59b-11e8-99b5-d30f6f4c8c45.png)

**Comment by otiai10** [comment]
@hana99999 2.1.7 で直ったきがします
