### ISSUE TITLE
各タイマーの手動登録ができない

### ISSUE THREAD

**Issue by halkikanzaki** [otiai10/kanColleWidget#949]
# 画面

クロックモードにおいてドック順形式の残り時間表示の際に、各ドックをクリックした先の手動登録ウィンドウ。

# 観測される問題

『登録』ボタンが表示されず、手動でタイマーが設定できない。こんな感じ。
![kancolle_capt_20180820_0](https://user-images.githubusercontent.com/42529774/44321030-91948900-a480-11e8-9735-1f047cdf9d2a.PNG)

# 期待される挙動

『登録』ボタンが表示され、そのボタンのクリックによってタイマーの設定が可能であるべき？

# 再現方法

タイマーの表示が残り時間モードでも時刻モードでも同様に起こります。
タイマー時間のアップダウンは正常に行えます。登録できないだけ。自動で登録に成功した分の『解除』ボタンは正常に表示され、正常に動作するようです。あと『しません』ボタンも正常のように見えます。

V3の方優先でV3で直します、というのでも当方は問題ないですが、とりあえず見つけてしまったのでご報告です。

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

バージョン

> 2.1.6

**Comment by halkikanzaki** [comment]
昼の投稿は仕事場PCからでしたので、wifeofvillonさんの返答を元に自宅PCからも試してみたんですが、こちらだと正常に『登録』ボタンが働いています。

![kancolle_capt_20180820_1](https://user-images.githubusercontent.com/42529774/44337268-0d102d80-a4b5-11e8-8c75-e314df22517c.PNG)

自宅の方の環境：

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36


仕事場と変わりはないようです。

この投稿の為にもう一度仕事場PCの方を確認してみましたが、やはり投稿ボタンの表示がされず…。
よく分かりません。

**Comment by otiai10** [comment]
クロックモードの大きさじゃないっすかね

**Comment by otiai10** [comment]
![image](https://user-images.githubusercontent.com/931554/44350641-dc42ef00-a4da-11e8-80a0-b7feab75e3b4.png)

![image](https://user-images.githubusercontent.com/931554/44350655-e4029380-a4da-11e8-8ba8-85f9fdaa114f.png)

**Comment by halkikanzaki** [comment]
今、家PCの方で試してみました。
確かにクロックモードのサイズを変えると登録ボタンだけ消える場面がありますね。すごく微妙なサイズ感ではあるんですが。
クロックモードのサイズを変えられるのは知ってましたけど、登録ウィンドウがそれに合わせてサイズ変化するなんて、今の今まで気がつかなかったです…。

教えていただいてありがとうございます。

**Comment by wifeofvillon** [comment]
Macでも再現しました。

min-widthとmin-heightを決め打ちにしたら可視領域を確保できそうではあるんですが、ダイアログ開いてからクロックモードをリサイズすると中央配置がズレます。
![min-width:312px;min-width:142px;](https://user-images.githubusercontent.com/24819529/44363488-49687b80-a4ff-11e8-9c78-1dc1956e09db.png)

ちょっとこのへん試してみましたがやっぱり細かい数値いじらないといけないですね……
[MaterialUIのダイアログのサイズをコンテンツに合わせて伸縮させる - Qiita](https://qiita.com/shitake/items/213ba948729f39d133fa)

@otiai10 v2のうちに対応しますか？

**Comment by otiai10** [comment]
@wifeofvillon ありがとうございます。v2のうちに対応しなくていいかなと思ってます。 

@halkikanzaki 報告ありがとうございます。v3でガラッと変えると思うので、そこで修正したいです。いったんここはcloseします。
