### ISSUE TITLE
画面左側が表示されない

### ISSUE THREAD

**Issue by arizato** [otiai10/kanColleWidget#952]
# 画面

ゲーム起動後全般

# 観測される問題

DEFAULT WHITEで起動した際画面右側に余白ができ左側が見切れる、拡大縮小や手動でウィンドウサイズを変更しても変わらない

![2](https://user-images.githubusercontent.com/42591965/44434617-18fc0c80-a5e7-11e8-8bbf-e046f84de37a.PNG)

# 期待される挙動

画面が正常に表示される

# 再現方法

初期設定のDEFAULT WHITEで起動する（小型、大型で起動した場合はウィンドウサイズに問わず１２８０＊７２０で正常に表示される）

-------

環境

>  Chrome/68.0.3440.106 win10 ウィジェット2.1.7

バージョン

> 2.1.7

**Comment by otiai10** [comment]
`left` の値は0になってますか？

![image](https://user-images.githubusercontent.com/931554/44434950-cc193580-a5e8-11e8-9074-e9a3cd5df10c.png)

**Comment by arizato** [comment]
なぜか-１７７ぐらいになってたんで０にしたら治りました、ありがとうございます
