### ISSUE TITLE
左上表示の時の大破進撃防止窓のサイズを設定で調整できるようにする

### ISSUE THREAD

**Issue by UDON13** [otiai10/kanColleWidget#957]
左上表示の時の大破進撃防止窓が小さいです。表示を大きくして目立たせてもらえませんでしょうか？大きさが調整できたりするとより良いと思います。

# 解決される問題

左上表示の大破進撃防止窓が小さいという問題

-------

環境

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

バージョン

> 2.1.8

**Comment by otiai10** [comment]
大きすぎてもアレっすよね

**Comment by UDON13** [comment]
大きすぎてはいけないと思いますが今の表示は小さいと感じています。”大破進撃防止窓”なんですからもう少し大き目でも良いと思います。

**Comment by otiai10** [comment]
まあ設定で調整できたほうがいいですよね。たぶんv3で反映させます

**Comment by UDON13** [comment]
わかりました。ありがとうございます。

**Comment by otiai10** [comment]
#986 で実装
