### ISSUE TITLE
見慣れないエラー画面が表示される事がある

### ISSUE THREAD

**Issue by ninanka7843** [otiai10/kanColleWidget#960]
![2018-09-04 02 43 26](https://user-images.githubusercontent.com/42945210/44998504-19d26c80-aff1-11e8-9f88-0724c9b5a13c.png)
# 画面

真っ黒な画面の中央に、白い四角の小さな顔が出現。目はバツ、口はへの字

# 観測される問題

母港画面から補給ボタンを押した際、上のような画面になる事がある

# 期待される挙動

補給画面に移行する

# 再現方法

演習から帰投したすぐ後に補給ボタンを押す。素早く操作した際に起こりやすい。

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

バージョン

> 2.1.8

**Comment by wifeofvillon** [comment]
@ninanka7843 @otiai10 Macでの再現を確認できていないのですが、[同様の事象が起こっている人はいる](https://twitter.com/search?f=tweets&q=%E8%89%A6%E3%81%93%E3%82%8C%20%E3%82%AF%E3%83%A9%E3%83%83%E3%82%B7%E3%83%A5%20chrome&src=typd)ようです。見た感じAudio系がクラッシュしている気がします。

- マシンスペックの問題の可能性
- インストールしているShockwave/Flash Pluginなどと喧嘩している可能性

1) 演習終了(自動遷移)→2) 母港画面でクリック→3) 補給画面に遷移 の間にBGMが多くて3回切り替わりますが、(家具などで変更された)母港BGMと通常母港BGM、SEなど複数のmp3を同時に読み込もうとしているのかCPU使用率が瞬間的に上がるようです。

(Windowsでは事情が違うかもしれませんが)

**Comment by otiai10** [comment]
@wifeofvillon ありがとうございます。
@ninanka7843 いったんcloseします。やっぱり明らかに艦これウィジェットのせいでしょ！ってなったらreopenしていただいてかまいません 🙇
