### ISSUE TITLE
画面がずれる

### ISSUE THREAD

**Issue by gedachtnistauri34** [otiai10/kanColleWidget#970]
# 画面

ゲーム画面

# 観測される問題

カスタマイズしたゲーム画面がずれる（上に白い隙間が空き下が切れる）

# 期待される挙動

ゲーム画面ぴったりのウインドウ

# 再現方法

幅800縦480の画面で倍率は0.67です

-------

環境

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

バージョン

> 2.1.8

**Comment by otiai10** [comment]
offsetのtopいじったらどうなりますか

**Comment by gedachtnistauri34** [comment]
メンテ中で(メンテ中のゲーム画面の端が白いので）よくわかりませんが
topの調整でなんとかなりそうです　すみません

今までは「ゲームコンテンツを切り出してウインドウぴったりの大きさにする」でよかったのでそこに拘ってしまっていました
メンテが明けたら確認し　また報告させていただきます

**Comment by otiai10** [comment]
どうですか

**Comment by otiai10** [comment]
反応無いので閉じます
