### ISSUE TITLE
[連合艦隊編成]大破進撃窓のキャプチャタイミングがズレる

### ISSUE THREAD

**Issue by wifeofvillon** [otiai10/kanColleWidget#972]
# 画面

大破進撃窓(連合艦隊編成時・通常編成時もたまに)

# 観測される問題

特に連合艦隊編成時、大破進撃窓のキャプチャタイミングがズレているのか、艦隊の様子がわからない。

ゲーム画面上では

1. 戦闘終了
1. シャッター閉じる
1. (*)
1. 双方の第一艦隊が表示される
1. 勝利判定表示
1. 第一艦隊経験値表示
1. 第二艦隊経験値表示

の(*)のタイミングで大破進撃窓が開いているっぽい

[参考ツイート](https://twitter.com/Nuko_Lingga/status/1039328008950038531)

# 期待される挙動

第一第二艦隊の損傷状況を確認できる

# 再現方法

大破進撃窓を有効にして連合艦隊編成で出撃・戦闘する

-------

環境

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

バージョン

> 2.1.8

**Comment by wifeofvillon** [comment]
戦闘終了イベントを拾ってからonMousedownからの画像取得を都合2回繰り返さなきゃいけない気がする

[当該箇所](https://github.com/otiai10/kanColleWidget/blob/57891a0d7cacf0c0205a10f01d61f3b3c916dd14/src/js/Application/Controllers/RequestControllers/Battle.js#L62)

(同じソース中の通常艦隊の時に使う処理の中から画像取得する処理を外出しにして繰り返す…？)

**Comment by xia-sava** [comment]
連合艦隊の2艦隊目表示をトリガするマウスクリックのイベントを拾えていない気がします．

1期では Flash にイベント透過を仕込んで [embed タグにイベント登録していた](https://github.com/otiai10/kanColleWidget/blob/master/src/js/Application/Routine/DamageSnapshot.js#L66)んですが，
2期は embed の代わりに iframe#htmlWrap があり中に IP アドレス表記の別ドメイン，という
構造になっているようです．

この iframe の contentDocument.body 辺りに addEventListener() して確認してみたかったんですが，
クロスオリジン制約に引っかかってアウトでした．

postMessage() するコードを content_scripts で叩き込めば行けるとは思うんですが，
IPアドレス表記のドメインということは複数あったり下手したら大湊とかサーバごとに違う……？
今のところ解決策が思いつきません．ううむ．

**Comment by otiai10** [comment]
v3の大破進撃防止窓は、1艦隊でもマウスクリックを拾う実装になっています。
ということは、v3なら連合艦隊も対応可能ということですかね。

**Comment by xia-sava** [comment]
v3 alpha 16 で確認したら（タイミングがほんの少しだけ微妙かもですが）うまくいってました．
![ss_20180920_093347](https://user-images.githubusercontent.com/679532/45788969-65a33800-bcb8-11e8-8e7c-4b290c6d98b2.jpg)

`"http://*/kcs2/index.php?*"` への content_scripts みたいのを v2 に実装しないと v2 側での対応は難しそうですね．
つっても onclick で message 飛ばすだけなので実装は簡単なんですが，今から manifest にサイト権限増やすのもなー……

**Comment by otiai10** [comment]
osapiに読ませてるcontet_scriptをkcs2に読ませたら一発解決してくれないかな

**Comment by xia-sava** [comment]
manifest 変えずに embed を div#flashWrap にした箇所，osapi → kcs2 して embed を canvas にするのが正当でしたね……
でも manifest でドメイン変えると拡張アップデートの時に権限変更されましたみたいの出て，平均的ユーザーの皆さまが驚いちゃう（婉曲表現）んだ……

**Comment by otiai10** [comment]
`<all_urls>` だと思うので権限変更出るかわかんないです

**Comment by otiai10** [comment]
v2なのでcloseします
