### ISSUE TITLE
[Wiki]v3alphaテスター向けTipsページ

### ISSUE THREAD

**Issue by wifeofvillon** [otiai10/kanColleWidget#993]
# 問題の概要

「拡張機能をアップデートしたら一旦ウィジェットのウィンドウを閉じる」などのメモがグループ内のトピックに点在しているので溜めておいた方がいいと思う

# ひとこと

[v2移行の諸注意 · otiai10/kanColleWidget Wiki](https://github.com/otiai10/kanColleWidget/wiki/v2%E7%A7%BB%E8%A1%8C%E3%81%AE%E8%AB%B8%E6%B3%A8%E6%84%8F)みたいなページを作ろうと思います

**Comment by wifeofvillon** [comment]
作りました

https://github.com/otiai10/kanColleWidget/wiki/v3%E9%96%8B%E7%99%BA%E7%89%88%E4%BD%BF%E7%94%A8%E3%81%AB%E9%96%A2%E3%81%99%E3%82%8BTips

**Comment by otiai10** [comment]
ありがとうございます！たすかります！

**Comment by otiai10** [comment]
あ、closeでよかったっすか

**Comment by wifeofvillon** [comment]
@otiai10 よかったっす あれだったらグループのトップとかに貼ってもらえたら便利かもです
